/* c2py.h - Single-header c2py23 runtime
 *
 * Generated by merge_single_header.py -- do not edit by hand.
 * Source files: c2py_runtime.h, c2py_dlsym.h/c, c2py_pythonh.h/c
 *
 * Usage:
 *   #include "c2py.h"              // declarations only
 *   #define C2PY_IMPLEMENTATION
 *   #include "c2py.h"              // + implementation (exactly one TU)
 *
 * Backend selection (default: dlsym):
 *   #define C2PY_USE_PYTHON_H    // before include for --pythonh mode
 */

#ifndef C2PY_H
#define C2PY_H

/* ---- Pick one backend ---- */

#ifdef C2PY_USE_PYTHON_H
/* c2py_pythonh.h - pythonh backend (#include <Python.h> directly)
 *
 * Standard CPython extension.  No dlsym trick, no cross-version
 * portability.  The .so/.pyd is tied to one Python version.
 * Used for GraalPy, debugging, static builds.
 *
 * This header is NOT included directly.  Include c2py_runtime.h instead.
 */

#undef _GNU_SOURCE   /* runtime.c defines it; PyPy/GraalPy Python.h may redefine */
#undef _POSIX_C_SOURCE  /* Python 2.7 pyconfig.h may redefine */
#undef _XOPEN_SOURCE
#include <Python.h>
#include <stddef.h>
#include <stdint.h>
#ifdef _WIN32
#include <windows.h>
#endif

/* ---- Python 2.7 stubs (not available in Python.h) ---- */

#if PY_MAJOR_VERSION == 2
typedef struct {
    PyObject_HEAD
    void *m_init;
    Py_ssize_t m_index;
    void *m_copy;
    const char *m_name;
    const char *m_doc;
    Py_ssize_t m_size;
    PyMethodDef *m_methods;
    void *m_slots;
    void *m_traverse;
    void *m_clear;
    void *m_free;
} PyModuleDef;
#define PyModuleDef_HEAD_INIT 1, NULL, NULL, 0, NULL
#endif


/* ---- Common definitions ---- */

#ifdef _WIN32
#define C2PY_EXPORT __declspec(dllexport)
#else
#define C2PY_EXPORT
#endif

/* Buffer flags -- pythonh aliases for CPython constants */
#define C2PY_BUF_READ   PyBUF_READ
#define C2PY_BUF_WRITE  PyBUF_WRITE

/* Thin wrappers that call the real CPython API directly.
 * The same names are defined as inline functions in the dlsym backend;
 * in pythonh mode, these macros take precedence. */
#define c2py_acquire_buffer(o,b,w) \
    PyObject_GetBuffer((PyObject*)(o),(b), \
        ((w) ? (PyBUF_FORMAT|PyBUF_C_CONTIGUOUS|PyBUF_STRIDES|PyBUF_ND|PyBUF_WRITABLE) \
              : (PyBUF_FORMAT|PyBUF_C_CONTIGUOUS|PyBUF_STRIDES|PyBUF_ND)))
#define c2py_release_buffer(b)  PyBuffer_Release(b)

/* FT module defs are just standard ones in pythonh mode */
#define PyModuleDef_FT            PyModuleDef
#define PyModuleDef_HEAD_INIT_FT  PyModuleDef_HEAD_INIT

/* c2py_set_module_attr -- simple wrapper for pythonh mode */
#define c2py_set_module_attr(mod, name, val) \
    PyObject_SetAttrString((PyObject*)(mod), (name), (PyObject*)(val))

int c2py_runtime_init(void);

#else
/* c2py_dlsym.h - nimpy-style dlsym backend
 *
 * Hand-declared CPython type definitions and system includes.
 * All CPython API is resolved at runtime via dlopen(NULL) + dlsym().
 * One .so works on Python 2.7 through 3.15 without recompilation.
 *
 * This header is NOT included directly.  Include c2py_runtime.h instead.
 */

/* ---- System includes ---- */

#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#include <stdio.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#endif

/* Symbol resolution helper -- dlsym on Unix, GetProcAddress on Windows */
#ifdef _WIN32
#define C2PY_RESOLVE(handle, name) GetProcAddress((HMODULE)(handle), (name))
#else
#define C2PY_RESOLVE(handle, name) dlsym((handle), (name))
#endif

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#else
#include <time.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* MSVC C mode does not recognise the inline keyword (C++ only).
 * __inline is the MSVC equivalent (also recognised by MinGW). */
#ifdef _MSC_VER
#define inline __inline
#endif

/* DLL export attribute for module init functions.
 * On Windows the PyInit_<name> symbol must be in the .pyd export
 * table or Python cannot load the module. */
#ifdef _WIN32
#define C2PY_EXPORT __declspec(dllexport)
#else
#define C2PY_EXPORT
#endif

/* ------------------------------------------------------------------ */
/* Py_ssize_t - must be defined before any struct using it            */
/* ------------------------------------------------------------------ */

#if defined(__LP64__) || defined(_WIN64)
typedef long long Py_ssize_t;
#else
typedef long Py_ssize_t;
#endif

/* sizeof(Py_buffer) differs across CPython versions:
 * < 3.12: includes smalltable[2]  (96 bytes LP64, 52 bytes ILP32)
 * >= 3.12: smalltable removed for PEP 697 stable ABI (80 / 44)
 */
#if defined(__LP64__) || defined(_WIN64)
#define C2PY_PYBUFFER_SZ_PRE312   96
#define C2PY_PYBUFFER_SZ_POST312  80
#else
#define C2PY_PYBUFFER_SZ_PRE312   52
#define C2PY_PYBUFFER_SZ_POST312  44
#endif

/* ------------------------------------------------------------------ */
/* CPython type definitions (stable layouts across versions)          */
/* ------------------------------------------------------------------ */

/* PyObject layout: differs between GIL-enabled and free-threaded builds.
 *
 * GIL-enabled (CPython 2.7 - 3.14 standard):
 *   LP64:    16 bytes.  ob_refcnt at 0, ob_type at 8.
 *   ILP32:    8 bytes.  ob_refcnt at 0, ob_type at 4.
 *
 * Free-threaded (CPython 3.13t+ --disable-gil, LP64 only):
 *   32 bytes.   ob_ref_shared at 16, ob_type at 24.
 *   FT does not exist on ILP32.
 *
 * We define both layouts.  Generated code uses macros (C2PY_SET_MNAME,
 * C2PY_SET_MDOC, etc.) that work with either layout via C2PY offsets.
 */

/* GIL-enabled PyObject layout (standard CPython) */
typedef struct _c2py_object {
    Py_ssize_t ob_refcnt;
#ifdef C2PY_TARGET_PYPY
    void *ob_pypy_link;  /* PyPy cpyext inserts this field */
#endif
    void *ob_type;
} PyObject;

/* Free-threaded PyObject layout (CPython --disable-gil) */
/* PyMutex: per-object lock, uint8_t with two-bit state (private) */
typedef struct { uint8_t _bits; } PyMutex;

typedef struct _c2py_object_ft {
    uintptr_t ob_tid;
    uint16_t ob_flags;
    PyMutex ob_mutex;
    uint8_t ob_gc_bits;
    uint32_t ob_ref_local;
    Py_ssize_t ob_ref_shared;
    void *ob_type;
} PyObject_FT;

/* Shorthand for embedding PyObject at the head of a struct (GIL layout) */
#define PyObject_HEAD \
    Py_ssize_t ob_refcnt; \
    void *ob_type;

typedef void *(*PyCFunction)(PyObject*, PyObject*);

/* Py_buffer: stable since Python 2.6 (PEP 3118).
 * NOTE: includes smalltable[2] field present in CPython 2.7-3.11.
 * In CPython 3.12+ this was removed (PEP 697 stable ABI);
 * we use C2PY.pybuffer_size (set at init) for correct sizeof.
 */
typedef struct {
    void *buf;
    PyObject *obj;
    Py_ssize_t len;
    Py_ssize_t itemsize;
    int readonly;
    int ndim;
    char *format;
    Py_ssize_t *shape;
    Py_ssize_t *strides;
    Py_ssize_t *suboffsets;
    Py_ssize_t smalltable[2];  /* present on CPython 2.7-3.11 */
    void *internal;
} Py_buffer;

/* PyMethodDef: stable layout across all Python versions */
typedef struct {
    const char *ml_name;
    PyCFunction ml_meth;
    int ml_flags;
    const char *ml_doc;
} PyMethodDef;

/* PyModuleDef_Base: standard GIL-enabled layout (Python 3.0+) */
typedef struct PyModuleDef_Base {
    PyObject ob_base;
    PyObject *(*m_init)(void);
    Py_ssize_t m_index;
    PyObject *m_copy;
} PyModuleDef_Base;

/* PyModuleDef_Base for free-threaded builds (PyObject is 32 bytes) */
typedef struct PyModuleDef_Base_FT {
    PyObject_FT ob_base;
    PyObject *(*m_init)(void);
    Py_ssize_t m_index;
    PyObject *m_copy;
} PyModuleDef_Base_FT;

/* PyModuleDef for Python 3.x standard GIL layout */
typedef struct PyModuleDef {
    PyModuleDef_Base m_base;
    const char *m_name;
    const char *m_doc;
    Py_ssize_t m_size;
    PyMethodDef *m_methods;
    void *m_slots;
    void *m_traverse;
    void *m_clear;
    void *m_free;
} PyModuleDef;

/* PyModuleDef for free-threaded builds (PyModuleDef_Base is 56 bytes) */
typedef struct PyModuleDef_FT {
    PyModuleDef_Base_FT m_base;
    const char *m_name;
    const char *m_doc;
    Py_ssize_t m_size;
    PyMethodDef *m_methods;
    void *m_slots;
    void *m_traverse;
    void *m_clear;
    void *m_free;
} PyModuleDef_FT;

/* PyModuleDef_Slot: free-threading/extension slots (PEP 384, PEP 489) */
typedef struct {
    int slot;
    void *value;
} PyModuleDef_Slot;

/* Py_MOD_GIL_NOT_USED: signal that this module supports free-threading.
 * Value is (void*)1 (stable across CPython 3.13+).
 * c2py23 uses PyUnstable_Module_SetGIL() (resolved at runtime) to
 * declare free-threading support on the module object, rather than
 * the older PyModuleDef_Slot / Py_mod_gil slot-number mechanism
 * (whose slot number changed from 4 in 3.13-3.14 to 87 in 3.15+). */
#define Py_MOD_GIL_NOT_USED  ((void*)1)

/* ------------------------------------------------------------------ */
/* Constants                                                          */
/* ------------------------------------------------------------------ */

/* Py_buffer flags */
#define PyBUF_SIMPLE   0
#define PyBUF_WRITABLE 0x0001
#define PyBUF_FORMAT   0x0004
#define PyBUF_ND       0x0008
#define PyBUF_STRIDES  (0x0010 | PyBUF_ND)
#define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

/* PyMethodDef flags */
#define METH_VARARGS   0x0001
#define METH_KEYWORDS  0x0002
#define METH_NOARGS    0x0004
#define METH_O         0x0008
#define METH_CLASS     0x0010
#define METH_STATIC    0x0020
#define METH_FASTCALL  0x0080

/* Module init macro - initializes the PyModuleDef_Base embedded in PyModuleDef. */
#ifdef C2PY_TARGET_PYPY
#define PyModuleDef_HEAD_INIT { {1, NULL, NULL}, NULL, 0, NULL }
#else
#define PyModuleDef_HEAD_INIT { {1, NULL}, NULL, 0, NULL }
#endif

/* Module init macro for free-threaded builds (PyObject is 32 bytes).
 * ob_type = NULL, m_init = NULL, m_index = 0, m_copy = NULL.
 * ob_mutex is zeroed via {0} (PyMutex is struct { uint8_t _bits; }).
 * ob_flags = _Py_STATICALLY_ALLOCATED_FLAG (4), ob_ref_local =
 * _Py_IMMORTAL_REFCNT_LOCAL (UINT32_MAX), ob_ref_shared = 0.
 * These match the actual CPython 3.14t/3.15t PyModuleDef_HEAD_INIT(NULL)
 * expansion.  Earlier versions used 0/0/1 which 3.14t tolerated but 3.15t
 * hard-rejects. */
#define _Py_STATICALLY_ALLOCATED_FLAG (1 << 2)
#define _Py_IMMORTAL_REFCNT_LOCAL     0xFFFFFFFFU
#define PyModuleDef_HEAD_INIT_FT \
    { {0, _Py_STATICALLY_ALLOCATED_FLAG, {0}, 0, \
       _Py_IMMORTAL_REFCNT_LOCAL, 0, NULL}, NULL, 0, NULL}

#endif


/* ------------------------------------------------------------------ */
/* Function pointer table - populated by c2py_runtime_init()          */
/* Identical for both backends.                                       */
/* ------------------------------------------------------------------ */

typedef struct {
    void *dl_handle;
    int version_major;
    int version_minor;

    int use_fastcall;               /* 1 = use METH_FASTCALL wrappers (Python >= 3.12) */
    int is_free_threaded;           /* 1 = Python built with --disable-gil */
    int is_pypy;                    /* 1 = running on PyPy (cpyext, PyPy_* symbols) */
    Py_ssize_t pybuffer_size;      /* actual sizeof(Py_buffer) for this Python version */
    Py_ssize_t pyobject_size;      /* actual sizeof(PyObject) for this Python version */
    Py_ssize_t pyobject_size_ft;   /* sizeof(PyObject) for free-threaded builds (32 LP64) */
    Py_ssize_t pymoduledef_max_size; /* max(sizeof(PyModuleDef), sizeof(PyModuleDef_FT)) */
    ptrdiff_t ob_refcnt_offset;    /* offset of ob_refcnt (or ob_ref_shared on FT) in PyObject */
    ptrdiff_t ob_type_offset;      /* offset of ob_type field in PyObject */

    /* Buffer protocol */
    int (*GetBuffer)(PyObject*, Py_buffer*, int);
    void (*ReleaseBuffer)(Py_buffer*);

    /* Old buffer protocol (Python 2.x only, NULL on Python 3) */
    int (*AsReadBuffer)(PyObject*, const void**, Py_ssize_t*);
    int (*AsWriteBuffer)(PyObject*, void**, Py_ssize_t*);
    void (*Err_Clear)(void);
    int buffer_api_is_pep3118;  /* 0 = old API only, 1 = PEP 3118 available */

    /* Argument parsing (positional-only, no keyword support) */
    int (*ParseTuple)(PyObject*, const char*, ...);

    /* Value construction */
    PyObject* (*Long_FromLong)(long);
    PyObject* (*Long_FromLongLong)(long long);
    PyObject* (*Long_FromUnsignedLongLong)(unsigned long long);
    PyObject* (*Float_FromDouble)(double);

    /* Tuple construction */
    PyObject* (*Tuple_New)(Py_ssize_t);
    int (*Tuple_SetItem)(PyObject*, Py_ssize_t, PyObject*);

    /* String construction (ASCII bytes only, no unicode/encodings) */
    PyObject* (*Bytes_FromStringAndSize)(const char*, Py_ssize_t);

    /* Scalar conversion from objects */
    long (*Long_AsLong)(PyObject*);
    long long (*Long_AsLongLong)(PyObject*);
    double (*Float_AsDouble)(PyObject*);

    /* Exception objects (pointers to the actual exception types) */
    void *exc_TypeError;
    void *exc_ValueError;
    void *exc_RuntimeError;
    void *exc_MemoryError;
    void *exc_BufferError;    /* PyExc_BufferError (optional, may be NULL) */
    void (*Err_SetString)(PyObject*, const char*);
    PyObject* (*Err_Occurred)(void);
    PyObject* (*Err_Format)(PyObject*, const char*, ...);

    /* None singleton (immortal on CPython 3.12+, INCREF/DECREF unnecessary) */
    PyObject *none_obj;
    int none_immortal;  /* 1 if IncRef on None is a no-op (3.12+ immortal None) */

    /* Module creation */
    PyObject* (*Module_Create2)(PyModuleDef*, int);
    PyObject* (*InitModule_2_7)(const char*, PyMethodDef*);

    /* Reference counting */
    void (*IncRef)(PyObject*);
    void (*DecRef)(PyObject*);

    /* Object attribute access */
    int (*SetAttrString)(PyObject*, const char*, PyObject*);
    PyObject* (*GetAttrString)(PyObject*, const char*);
    PyObject* (*Module_GetDict)(PyObject*);    /* for perf attr registration */
    void *_ds_set_item_string;  /* PyDict_SetItemString, resolved at init */
    int _ds_pypy_workaround;   /* 1 if PyPy 2.7-style dict-based attr set */

    /* General call support (optional, used by DLPack) */
    PyObject* (*CallObject)(PyObject*, PyObject*);

    /* Capsule API (optional, used by DLPack) */
    void* (*Capsule_GetPointer)(PyObject*, const char*);

    /* Pointer-to-int conversion (for exposing perf struct addresses) */
    PyObject* (*Long_FromVoidPtr)(void*);

    /* GIL management */
    void* (*SaveThread)(void);
    void (*RestoreThread)(void*);
    /* Free-threading: set Py_MOD_GIL_NOT_USED on module (optional, may be NULL) */
    void (*Unstable_Module_SetGIL)(PyObject*, void*);

} c2py_api_t;

/* The global API table */
extern c2py_api_t C2PY;

/* ------------------------------------------------------------------ */
/* Nimpy-only convenience macros  (Python.h provides these in pythonh mode) */
/* ------------------------------------------------------------------ */

#ifndef C2PY_USE_PYTHON_H

#define PyObject_GetBuffer(o, b, f)    C2PY.GetBuffer((PyObject*)(o), (b), (f))
#define PyBuffer_Release(b)            C2PY.ReleaseBuffer(b)

/* MSVC traditional preprocessor auto-removes the comma before an empty
 * __VA_ARGS__; GCC/Clang require the ## token-paste to do so.
 * MSVC 2022+ (conformant preprocessor) behaves like GCC and also needs ##. */
#ifdef _MSC_VER
#define PyArg_ParseTuple(a, f, ...)    C2PY.ParseTuple((PyObject*)(a), (f), ##__VA_ARGS__)
#define PyErr_Format(e, f, ...)        C2PY.Err_Format((PyObject*)(e), (f), ##__VA_ARGS__)
#else
#define PyArg_ParseTuple(a, f, ...)    C2PY.ParseTuple((PyObject*)(a), (f), ##__VA_ARGS__)
#define PyErr_Format(e, f, ...)        C2PY.Err_Format((PyObject*)(e), (f), ##__VA_ARGS__)
#endif

#define PyLong_FromLong(v)             C2PY.Long_FromLong(v)
#define PyLong_FromLongLong(v)         C2PY.Long_FromLongLong(v)
#define PyLong_FromUnsignedLongLong(v) C2PY.Long_FromUnsignedLongLong(v)
#define PyFloat_FromDouble(v)          C2PY.Float_FromDouble(v)
#define PyBytes_FromStringAndSize(s, n) C2PY.Bytes_FromStringAndSize((s), (n))
#define PyLong_AsLong(o)               C2PY.Long_AsLong((PyObject*)(o))
#define PyLong_AsLongLong(o)           C2PY.Long_AsLongLong((PyObject*)(o))
#define PyFloat_AsDouble(o)            C2PY.Float_AsDouble((PyObject*)(o))
#define PyErr_SetString(e, m)          C2PY.Err_SetString((PyObject*)(e), (m))
#define PyErr_Clear()                  C2PY.Err_Clear()
#define PyErr_Occurred()               C2PY.Err_Occurred()
#define Py_RETURN_NONE                 do { \
    if (C2PY.none_immortal) { return C2PY.none_obj; } \
    C2PY.IncRef(C2PY.none_obj); return C2PY.none_obj; \
} while(0)
#define Py_INCREF(o)                   C2PY.IncRef((PyObject*)(o))
#define Py_DECREF(o)                   C2PY.DecRef((PyObject*)(o))
#define PyObject_SetAttrString(o, n, v) C2PY.SetAttrString((PyObject*)(o), (n), (PyObject*)(v))
#define PyObject_GetAttrString(o, n)   C2PY.GetAttrString((PyObject*)(o), (n))
#define PyModule_GetDict(m)            C2PY.Module_GetDict((PyObject*)(m))

/* Set a module attribute.  PyObject_SetAttrString silently fails
 * on PyPy 2.7 cpyext modules; C2PY._ds_pypy_workaround gates the
 * dict-based fallback (resolved once at init, zero runtime dlsym). */
#define c2py_set_module_attr(m, name, val) do { \
    if (C2PY._ds_pypy_workaround) { \
        PyObject *_d = C2PY.Module_GetDict((PyObject*)(m)); \
        if (_d && C2PY._ds_set_item_string) { \
            typedef int (*_ds_fn)(PyObject*, const char*, PyObject*); \
            ((_ds_fn)C2PY._ds_set_item_string)(_d, (name), (PyObject*)(val)); \
        } \
    } else { \
        C2PY.SetAttrString((PyObject*)(m), (name), (PyObject*)(val)); \
    } \
} while(0)
#define PyLong_FromVoidPtr(p)          C2PY.Long_FromVoidPtr((void*)(p))
#define PyTuple_New(s)                 C2PY.Tuple_New(s)
#define PyTuple_SetItem(t, i, o)       C2PY.Tuple_SetItem((PyObject*)(t), (i), (PyObject*)(o))
#define PyEval_SaveThread()            C2PY.SaveThread()
#define PyEval_RestoreThread(s)        C2PY.RestoreThread((void*)(s))

#define PyExc_TypeError                ((PyObject*)C2PY.exc_TypeError)
#define PyExc_ValueError               ((PyObject*)C2PY.exc_ValueError)
#define PyExc_RuntimeError             ((PyObject*)C2PY.exc_RuntimeError)
#define PyExc_MemoryError              ((PyObject*)C2PY.exc_MemoryError)
#define PyExc_BufferError              ((PyObject*)C2PY.exc_BufferError)
#define PyObject_CallObject(c, a)      C2PY.CallObject((PyObject*)(c), (PyObject*)(a))
#define PyCapsule_GetPointer(c, n)     C2PY.Capsule_GetPointer((PyObject*)(c), (n))
#define Py_XDECREF(o)                  do { if (o) C2PY.DecRef((PyObject*)(o)); } while(0)

/* ------------------------------------------------------------------ */
/* Reference counting fallbacks (for CPython < 3.12 where Py_IncRef   */
/* is not an exported symbol)                                         */
/* ------------------------------------------------------------------ */

/* Manual refcount increment - accesses ob_refcnt via the correct offset
 * for the Python build (ob_refcnt on GIL, ob_ref_shared on free-threaded).
 * Safe on GIL-enabled builds where refcount is a simple Py_ssize_t field.
 * On free-threaded builds this fallback is UNSAFE (ob_ref_shared requires
 * atomic operations); always prefer Py_IncRef / Py_DecRef on 3.12+. */
static inline void _c2py_inc_ref_manual(PyObject *op)
{
    Py_ssize_t *refcnt = (Py_ssize_t*)((char*)op + C2PY.ob_refcnt_offset);
    ++(*refcnt);
}

/*
 * _c2py_dec_ref_manual: Fallback dec-ref for pre-3.12 Python where
 * Py_DecRef is not resolvable via dlsym. On those versions CPython uses
 * shared refcounts where zero-is-special does not apply -- refcounts
 * never reach zero through normal INCREF/DECREF alone.
 *
 * WARNING: This is a diagnostic-only fallback. When refcount hits zero
 * it prints a warning but does NOT call tp_dealloc destructor.
 * This is acceptable because the fallback is only active on Python < 3.12
 * where the zero-refcount invariant holds. If porting to a platform where
 * this invariant does not hold, implement proper deallocation.
 */
static inline void _c2py_dec_ref_manual(PyObject *op)
{
    Py_ssize_t *refcnt = (Py_ssize_t*)((char*)op + C2PY.ob_refcnt_offset);
    --(*refcnt);
    if (*refcnt == 0) {
        fprintf(stderr, "c2py_runtime: _c2py_dec_ref_manual reached zero "
                "refcount for %p -- possible leak\n", (void*)op);
    }
}

/* ------------------------------------------------------------------ */
/* Buffer acquisition helper with old-API fallback for Python 2.7     */
/* ------------------------------------------------------------------ */

/* Flags for c2py_acquire_buffer */
#define C2PY_BUF_READ   0
#define C2PY_BUF_WRITE  1

/* Returns 0 on success, -1 on failure (with Python exception set) */
static inline int
c2py_acquire_buffer(PyObject *obj, Py_buffer *buf, int want_writable)
{
    int flags = PyBUF_STRIDES | PyBUF_FORMAT;
    if (want_writable) flags |= PyBUF_WRITABLE;

    memset(buf, 0, C2PY.pybuffer_size);

    if (C2PY.buffer_api_is_pep3118) {
        return PyObject_GetBuffer(obj, buf, flags);
    }

    /* Python 2.7: try PEP 3118 first, fall back to old API */
    if (PyObject_GetBuffer(obj, buf, flags) == 0)
        return 0;

    PyErr_Clear();

    if (want_writable) {
        if (C2PY.AsWriteBuffer &&
            C2PY.AsWriteBuffer(obj, (void**)&buf->buf, &buf->len) == 0) {
            buf->readonly = 0;
        } else {
            return -1;
        }
    } else {
        if (C2PY.AsReadBuffer &&
            C2PY.AsReadBuffer(obj, (const void**)&buf->buf, &buf->len) == 0) {
            buf->readonly = 1;
        } else {
            return -1;
        }
    }

    buf->ndim = 1;
    buf->itemsize = 1;
    buf->format = NULL;
    buf->shape = NULL;
    buf->strides = NULL;
    return 0;
}

/* Release a buffer acquired by c2py_acquire_buffer */
static inline void
c2py_release_buffer(Py_buffer *buf)
{
    if (buf->obj != NULL) {
        PyBuffer_Release(buf);
    }
     /* Old buffer API (PyObject_AsRead/WriteBuffer) needs no release */
}
#endif /* !C2PY_USE_PYTHON_H */

/* ------------------------------------------------------------------ */
/* Unified buffer info struct -- the common interface for all         */
/* acquisition backends (PEP 3118, ndarray struct cast, DLPack).     */
/* Generated wrappers operate on c2py_ptr_info; the underlying       */
/* acquisition mechanism is hidden behind pin/unpin.                  */
/* ------------------------------------------------------------------ */

/* Maximum supported dimensions for DLPack stride computation.
 * Matches numpy's practical limit; arrays with >16D are vanishingly rare. */
#define C2PY_MAX_NDIM 32

/* c2py_ptr_info mirrors the leading fields of Py_buffer exactly so that
 * c2py_pin_buffer can memcpy the acquired Py_buffer straight into it.
 * Field order MUST match PEP 3118 Py_buffer layout (offset, type):
 *   0: buf     (void*)       -> ptr
 *   8: obj     (PyObject*)   -> _pin_buf_obj (unused by info, reserved)
 *  16: len     (Py_ssize_t)
 *  24: itemsize (Py_ssize_t)
 *  32: readonly (int)        -> _ro (unused)
 *  36: ndim    (int)
 *  40: format  (char*)
 *  48: shape   (Py_ssize_t*)
 *  56: strides (Py_ssize_t*)
 * Add reserved padding if the struct grows beyond what we memcpy. */
typedef struct {
    void *ptr;                /* data pointer (matches Py_buffer.buf) */
    PyObject *_pin_buf_obj;   /* reserved: maps to Py_buffer.obj, never accessed */
    Py_ssize_t len;           /* total length in bytes */
    Py_ssize_t itemsize;      /* size of one element */
    int _ro;                  /* reserved: maps to Py_buffer.readonly */
    int ndim;                 /* number of dimensions */
    char *format;             /* PEP 3118 format string (may be NULL) */
    Py_ssize_t *shape;        /* per-dimension sizes (may be NULL for 1D) */
    Py_ssize_t *strides;      /* per-dimension strides (may be NULL) */
} c2py_ptr_info;

/* Backend tags for c2py_buf_pin.kind -- tells c2py_unpin_buffer
 * which release path to use.  Zero-init = C2PY_PIN_NONE = no-op. */
#define C2PY_PIN_NONE     0
#define C2PY_PIN_PEP3118  1   /* pin->buf is valid; call PyBuffer_Release */
#define C2PY_PIN_NDARRAY  2   /* struct-cast; pin->buf.obj is the INCREF'd ndarray */
#define C2PY_PIN_DLPACK   3   /* DLPack; pin->ctx is the DLManagedTensor* */

typedef struct {
    Py_buffer buf;          /* opaque Py_buffer, valid when kind == PEP3118 */
    char _buf_pad[1200];    /* extra space: PyPy's Py_buffer is up to 1112 bytes
                               (PyBUF_MAX_NDIM=64 with inline arrays), but we
                               compiled with CPython's sizeof(~80) */
    int kind;               /* C2PY_PIN_* tag */
    void *ctx;              /* back-end context (DLManagedTensor* for DLPack) */
    char format_buf[8];     /* stack-local format string storage (non-PEP3118) */
    Py_ssize_t stride_buf[C2PY_MAX_NDIM]; /* stride buffer */
} c2py_buf_pin;

/* ------------------------------------------------------------------ */
/* NumPy ndarray struct-cast fast path (lazy-probed, no import)       */
/* ------------------------------------------------------------------ */

/* Minimal PyTypeObject overlay to read tp_name without importing numpy.
 * Layout (GIL-only LP64): ob_refcnt(8) + ob_type(8) + ob_size(8) +
 * tp_name(8).  Free-threaded builds skip the fast path.
 * On PyPy, ob_pypy_link sits between ob_refcnt and ob_type. */
typedef struct {
    Py_ssize_t ob_refcnt;
#ifdef C2PY_TARGET_PYPY
    void     *ob_pypy_link;
#endif
    void     *ob_type;
    Py_ssize_t ob_size;
    const char *tp_name;
} c2py_type_min_t;

/* Runtime-discovered ndarray layout cache.
 * data_off is the offset of the data pointer from the PyObject base.
 * The remaining fields live at fixed relative offsets from data_off
 * (stable since numpy 1.0 through 2.x):
 *   data_off + 8:  nd          (int)
 *   data_off + 16: dimensions  (npy_intp*)
 *   data_off + 24: strides     (npy_intp*)
 *   data_off + 40: descr       (PyArray_Descr*)
 *   data_off + 48: flags       (int)      */
typedef struct {
    void *ndarray_type;     /* cached ob_type of numpy.ndarray, NULL if unknown */
    int data_off;           /* offset of data ptr from PyObject base */
    int probed;             /* 1 = layout known, 0 = probing deferred */
} c2py_ndarray_layout_t;

extern c2py_ndarray_layout_t C2PY_NDARRAY;

/* NPY_ARRAY_WRITEABLE = 0x0400 (stable since numpy 1.0) */
#define C2PY_NPY_WRITEABLE  0x0400

/* Map a PEP 3118 type character to itemsize.
 * Excludes 'l'/'L' (platform-sized -- callers use sizeof(long) at
 * the expression level).  Used by both ndarray and DLPack backends. */
static inline int
c2py_format_itemsize(char type_char)
{
    switch (type_char) {
    case 'b': case 'B': case '?': return 1;
    case 'h': case 'H':          return 2;
    case 'i': case 'I':          return 4;
    case 'l': case 'L':          return (int)sizeof(long);
    case 'q': case 'Q':          return 8;
    case 'f':                    return 4;
    case 'd':                    return 8;
    case 'g':                    return (int)sizeof(long double);
    default:                     return 1;
    }
}

/* ------------------------------------------------------------------ */
/* DLPack struct definitions (hard-coded, no external headers)        */
/* ------------------------------------------------------------------ */

#define C2PY_DLCPU  1
#define C2PY_DLCUDA 2

typedef struct {
    uint8_t code;
    uint8_t bits;
    uint16_t lanes;
} c2py_dl_dtype_t;

typedef struct {
    int32_t device_type;
    int32_t device_id;
} c2py_dl_device_t;

typedef struct {
    void *data;
    c2py_dl_device_t device;
    int32_t ndim;
    c2py_dl_dtype_t dtype;
    int64_t *shape;
    int64_t *strides;
    int64_t byte_offset;
} c2py_dl_tensor_t;

typedef struct c2py_dl_managed_tensor {
    c2py_dl_tensor_t dl_tensor;
    void *manager_ctx;
    void (*deleter)(struct c2py_dl_managed_tensor *);
} c2py_dl_managed_tensor;

/* DLPack type codes */
#define C2PY_DL_INT    0
#define C2PY_DL_UINT   1
#define C2PY_DL_FLOAT  2
#define C2PY_DL_BFLOAT 4
#define C2PY_DL_COMPLEX 5
#define C2PY_DL_BOOL   6

/* Map a DLPack dtype to PEP 3118 format character.
 * Returns 0 for unsupported types. */
static inline char
c2py_dl_format_char(c2py_dl_dtype_t *dt)
{
    int bits = dt->bits;
    if (dt->lanes != 1) return 0;
    switch (dt->code) {
    case C2PY_DL_INT:
        if (bits == 8)  return 'b';
        if (bits == 16) return 'h';
        if (bits == 32) return 'i';
        if (bits == 64) return 'q';
        return 0;
    case C2PY_DL_UINT:
        if (bits == 8)  return 'B';
        if (bits == 16) return 'H';
        if (bits == 32) return 'I';
        if (bits == 64) return 'Q';
        return 0;
    case C2PY_DL_FLOAT:
        if (bits == 16) return 0; /* no PEP 3118 half-float char */
        if (bits == 32) return 'f';
        if (bits == 64) return 'd';
        return 0;
    case C2PY_DL_BOOL:
        if (bits == 8) return '?';
        return 0;
    default: return 0;
    }
}

/* ------------------------------------------------------------------ */
/* Acquisition functions                                              */
/* ------------------------------------------------------------------ */

/* Acquire via the standard PEP 3118 path. */
static inline int
c2py_pin_buffer(PyObject *obj, c2py_buf_pin *pin, c2py_ptr_info *info,
                int want_writable)
{
    if (c2py_acquire_buffer(obj, &pin->buf, want_writable) == -1)
        return -1;

    memcpy(info, &pin->buf, sizeof(c2py_ptr_info));

    pin->kind = C2PY_PIN_PEP3118;
    return 0;
}

/* Acquire via numpy ndarray struct-cast (no PyObject_GetBuffer).
 * Returns 0 on success, -1 to signal "try next backend" or real failure.
 * On first encounter of a numpy.ndarray, probes the data-pointer
 * offset by acquiring a buffer then scanning object memory.  All
 * subsequent calls use a ~1 ns type-pointer comparison. */
static inline int
c2py_pin_ndarray(PyObject *obj, c2py_buf_pin *pin, c2py_ptr_info *info,
                 int want_writable)
{
    c2py_ndarray_layout_t *L = &C2PY_NDARRAY;
    void *tp;
    char *base;
    void *dptr, *descr;
    int nd, flags;
    Py_ssize_t nelem, i;
    char type_char;

    /* Free-threaded Python and PyPy: type-object layout differs from
     * standard GIL CPython.  PyPy cpyext wraps ndarray objects in
     * proxies -- the data pointer is not at a fixed offset from id().
     * Skip the fast path and fall through to buffer protocol. */
    if (C2PY.is_free_threaded || C2PY.is_pypy)
        return -1;

    tp = *(void**)((char*)obj + C2PY.ob_type_offset);

    if (L->ndarray_type && tp == L->ndarray_type) {
        goto fill;
    }

    if (!L->probed && tp) {
        const char *name = ((c2py_type_min_t*)tp)->tp_name;
        if (name && strcmp(name, "numpy.ndarray") == 0) {
            /* First encounter: validate via buffer protocol, then
             * scan object memory to locate the data pointer at runtime.
             * Note: PyObject_GetBuffer COPIES shape/strides to temporary
             * arrays for numpy, so we cannot verify against buf.shape. */
            if (c2py_acquire_buffer(obj, &pin->buf, want_writable) != 0)
                return -1;

            base = (char*)obj;
            {
                int off;
                dptr = pin->buf.buf;
                for (off = (int)C2PY.pyobject_size;
                     off < (int)C2PY.pyobject_size + 80;
                     off += (int)sizeof(void*)) {
                    if (*(void**)(base + off) == dptr) {
                        L->data_off = off;
                        break;
                    }
                }
            }

            /* Verify the layout against known numpy struct:
             * data_off+8  -> nd   (int, 0 <= nd <= 32)
             * data_off+16 -> shape ptr (reasonable pointer)
             * data_off+40 -> descr (non-NULL pointer) */
            nd    = *(int*)(base + L->data_off + 8);
            descr = *(void**)(base + L->data_off + 40);
            if (nd < 0 || nd > C2PY_MAX_NDIM || descr == NULL)
                goto probe_fail;
            /* Sanity: shape pointer should be non-NULL if nd>0 */
            if (nd > 0 && *(void**)(base + L->data_off + 16) == NULL)
                goto probe_fail;

            L->ndarray_type = tp;
            L->probed = 1;


            /* First call: info already filled via c2py_acquire_buffer.
             * Return via pep3118 path so unpin releases the buffer. */
            memcpy(info, &pin->buf, sizeof(c2py_ptr_info));
            pin->kind = C2PY_PIN_PEP3118;
            return 0;

        probe_fail:
            c2py_release_buffer(&pin->buf);
            return -1;
        }
    }

    return -1;

fill:
    base = (char*)obj;

    dptr  = *(void**)(base + L->data_off);
    nd    = *(int*)(base + L->data_off + 8);
    flags = *(int*)(base + L->data_off + 48);

    if (want_writable && !(flags & C2PY_NPY_WRITEABLE)) {
        PyErr_SetString(PyExc_TypeError,
                        "numpy array is not writeable");
        return -1;
    }

    descr = *(void**)(base + L->data_off + 40);
    if (descr) {
        /* type char at offset 25 within PyArray_Descr
         * (stable since numpy 1.0 through 2.x on GIL builds) */
        type_char = ((char*)descr)[25];
        pin->format_buf[0] = type_char;
        pin->format_buf[1] = '\0';
        info->format = pin->format_buf;
        info->itemsize = c2py_format_itemsize(type_char);
    } else {
        info->format = NULL;
        info->itemsize = 1;
    }

    info->ptr     = dptr;
    info->ndim    = nd;
    info->shape   = *(Py_ssize_t**)(base + L->data_off + 16);
    info->strides = *(Py_ssize_t**)(base + L->data_off + 24);

    nelem = 1;
    if (info->shape) {
        for (i = 0; i < nd && info->shape[i] >= 0; i++)
            nelem *= info->shape[i];
    }
    info->len = nelem * (Py_ssize_t)(info->itemsize > 0 ? info->itemsize : 1);

    /* Hold a reference on the ndarray: we skipped PyObject_GetBuffer
     * which normally INCREFs the exporter.  Store it in buf.obj so
     * unpin can DECREF it. */
    C2PY.IncRef(obj);
    pin->buf.obj = obj;
    pin->kind = C2PY_PIN_NDARRAY;
    return 0;
}

/* Acquire via DLPack capsule extraction.
 * Calls obj.__dlpack__() to get the capsule, then reads the DLTensor
 * struct fields directly.  CPU-only; GPU tensors are rejected.
 * All DLPack API symbols (CallObject, Capsule_GetPointer)
 * are optional: if any is NULL, this function returns -1 immediately,
 * falling through to the next backend.
 * Returns 0 on success, -1 to fall through to next backend. */
static inline int
c2py_pin_dlpack(PyObject *obj, c2py_buf_pin *pin, c2py_ptr_info *info,
                int want_writable)
{
    PyObject *dl_method = NULL;
    PyObject *dl_args = NULL;
    PyObject *capsule = NULL;
    c2py_dl_managed_tensor *managed;
    c2py_dl_tensor_t *t;
    char format_char;
    Py_ssize_t nelem;
    int i;

    (void)want_writable;

    /* DLPack symbols are optional; if not resolved, skip this backend. */
    if (!C2PY.CallObject || !C2PY.Capsule_GetPointer)
        return -1;

    dl_method = PyObject_GetAttrString(obj, "__dlpack__");
    if (!dl_method) { PyErr_Clear(); return -1; }

    dl_args = PyTuple_New(0);
    if (!dl_args) goto fail;

    capsule = PyObject_CallObject(dl_method, dl_args);
    if (!capsule) { PyErr_Clear(); goto fail; }

    managed = (c2py_dl_managed_tensor*)PyCapsule_GetPointer(capsule, "dltensor");
    if (!managed) {
        PyErr_Clear();
        managed = (c2py_dl_managed_tensor*)PyCapsule_GetPointer(capsule, "dltensor_versioned");
    }
    if (!managed) { PyErr_Clear(); goto fail; }

    t = &managed->dl_tensor;

    if (t->device.device_type != C2PY_DLCPU) {
        PyErr_SetString(PyExc_TypeError,
            "DLPack: unsupported device (expected CPU)");
        goto fail;
    }

    format_char = c2py_dl_format_char(&t->dtype);
    if (!format_char) {
        PyErr_SetString(PyExc_TypeError,
            "DLPack: unsupported dtype");
        goto fail;
    }

    pin->format_buf[0] = format_char;
    pin->format_buf[1] = '\0';
    info->format   = pin->format_buf;
    info->itemsize = (t->dtype.bits / 8) * (t->dtype.lanes > 0 ? t->dtype.lanes : 1);
    info->ptr      = (char*)t->data + t->byte_offset;
    info->ndim     = t->ndim;

    nelem = 1;
    if (t->shape && t->ndim > 0) {
        info->shape   = (Py_ssize_t*)t->shape;
        if (t->strides) {
            /* DLPack strides are in elements; convert to bytes. */
            int d;
            for (d = 0; d < t->ndim; d++) {
                pin->stride_buf[d] = (Py_ssize_t)t->strides[d] * info->itemsize;
            }
            info->strides = pin->stride_buf;
        } else if (t->ndim <= C2PY_MAX_NDIM) {
            /* Implied C-contiguous strides: last dim = itemsize,
             * each preceding dim = product of later dims * itemsize */
            Py_ssize_t st = info->itemsize;
            int d;
            for (d = t->ndim - 1; d >= 0; d--) {
                pin->stride_buf[d] = st;
                st *= (Py_ssize_t)t->shape[d];
            }
            info->strides = pin->stride_buf;
        } else {
            /* >8D with NULL strides: reject (would need dynamic alloc) */
            PyErr_SetString(PyExc_ValueError,
                "DLPack: >8 dimensions without explicit strides");
            goto fail;
        }
        for (i = 0; i < t->ndim; i++)
            nelem *= (Py_ssize_t)t->shape[i];
    } else {
        info->shape   = NULL;
        info->strides = NULL;
    }
    info->len = nelem * info->itemsize;

    pin->ctx  = managed;
    pin->kind = C2PY_PIN_DLPACK;

    /* Keep the capsule alive: decref'ing it would invoke the
     * capsule destructor, which might call managed->deleter
     * prematurely.  Store it in buf.obj for later release. */
    pin->buf.obj = capsule;
    capsule = NULL;  /* ownership transferred to pin */

    Py_DECREF(dl_method);
    Py_DECREF(dl_args);
    /* capsule NOT decref'd -- stored in pin->buf.obj */
    return 0;

fail:
    Py_XDECREF(dl_method);
    Py_XDECREF(dl_args);
    Py_XDECREF(capsule);
    pin->kind = C2PY_PIN_NONE;
    return -1;
}

/* Release any backend acquired via c2py_pin_buffer/ndarray/dlpack.
 * No-op if kind == C2PY_PIN_NONE. */
static inline void
c2py_unpin_buffer(c2py_buf_pin *pin)
{
    switch (pin->kind) {
    case C2PY_PIN_PEP3118:
        c2py_release_buffer(&pin->buf);
        break;
    case C2PY_PIN_NDARRAY:
        /* We INCREF'd the ndarray in c2py_pin_ndarray;
         * release that reference now. */
        if (pin->buf.obj) {
            C2PY.DecRef(pin->buf.obj);
            pin->buf.obj = NULL;
        }
        break;
    case C2PY_PIN_DLPACK:
        /* Release the capsule we kept alive -- its destructor
         * called via Py_DECREF will invoke DLManagedTensor.deleter. */
        if (pin->buf.obj) {
            C2PY.DecRef(pin->buf.obj);
            pin->buf.obj = NULL;
        }
        pin->ctx = NULL;
        break;
    default:
        break;
    }
    pin->kind = C2PY_PIN_NONE;
}

/* Multi-source acquisition: tries each backend in order.
 * src_order is a uint8_t[] emitted by the generator from the
 * acquire: key in the .c2py file.  0 on success, -1 on failure
 * (Python exception set). */
static inline int
c2py_pin(PyObject *obj, c2py_buf_pin *pin, c2py_ptr_info *info,
         int want_writable, const uint8_t *src_order, int n_src)
{
    int i;
    for (i = 0; i < n_src; i++) {
        switch (src_order[i]) {
        case C2PY_PIN_NDARRAY:
            if (!C2PY.is_pypy) {
                if (c2py_pin_ndarray(obj, pin, info, want_writable) == 0)
                    return 0;
            }
            break;
        case C2PY_PIN_DLPACK:
            if (c2py_pin_dlpack(obj, pin, info, want_writable) == 0)
                return 0;
            break;
        case C2PY_PIN_PEP3118:
            if (c2py_pin_buffer(obj, pin, info, want_writable) == 0)
                return 0;
            break;
        default:
            break;
        }
    }
    PyErr_SetString(PyExc_TypeError,
                    "buffer acquisition failed (all backends exhausted)");
    return -1;
}

/* ------------------------------------------------------------------ */
/* Performance timing (optional, enabled via timing: true in .c2py)   */
/* ------------------------------------------------------------------ */

typedef struct {
    uint64_t call_count;

    uint64_t t_enter;          /* last call: wrapper entry */
    uint64_t t_pre_c;          /* last call: just before C code */
    uint64_t t_post_c;         /* last call: just after C returns */
    uint64_t t_exit;           /* last call: before return to Python */

    uint64_t t_c_min;          /* min C-call wall time (ns) */
    uint64_t t_c_max;          /* max C-call wall time (ns) */
    uint64_t t_c_total;        /* accumulated C wall time */

    uint64_t t_wrap_min;       /* min wrapper overhead (ns) */
    uint64_t t_wrap_max;       /* max wrapper overhead (ns) */
    uint64_t t_wrap_total;     /* accumulated wrapper overhead */

    int variant;               /* active variant index (0-based), -1 if unset */
    int group_idx;             /* active outer group index, -1 if flat */
    const char *variant_name;  /* points to static string, NULL if unset */
} c2py_perf_t;

/* Tick source: wall clock by default, cycle counter on request.
 *
 * Default mode returns nanoseconds via clock_gettime() (Unix) or
 * QueryPerformanceCounter (Windows).  Set _c2py_use_cycle_counter=1
 * at runtime to switch to the CPU cycle counter (rdtsc on x86,
 * CNTVCT_EL0 on aarch64, timebase on POWER).
 *
 * The cycle counter returns raw platform-dependent ticks.  Convert
 * deltas to nanoseconds with c2py_ticks_to_ns().
 *
 * All tick calls are guarded by _c2py_do_time so there is zero cost
 * when timing is not enabled in the .c2py interface.
 */

/* Runtime tick source selection.
 * 0 = wall clock (default): nanosecond ticks, freq = 1e9
 * 1 = CPU cycle counter: raw cycles, converted to ns via c2py_ticks_to_ns()
 *     Requires c2py_cycle_counter_frequency_hz > 0. */
extern int _c2py_use_cycle_counter;

/* Detected CPU cycle counter frequency in Hz, probed once at init.
 * 0 if the platform does not support cycle counters or detection failed.
 * When the cycle counter is selected (use_cycle_counter=1), the active
 * frequency is copied to c2py_tick_frequency_hz. */
extern uint64_t c2py_cycle_counter_frequency_hz;

/* Helper: raw cycle counter read (used internally by c2py_ticks when
 * _c2py_use_cycle_counter is set). */
static inline uint64_t c2py_cycle_counter_ticks(void) {
#if defined(_MSC_VER) && (defined(_M_X64) || defined(_M_IX86))
    return __rdtsc();
#elif (defined(__x86_64__) || defined(__i386__)) \
      && (defined(__GNUC__) || defined(__clang__))
    {
        unsigned int lo, hi;
        __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
        return ((uint64_t)hi << 32) | lo;
    }
#elif defined(__aarch64__) && (defined(__GNUC__) || defined(__clang__))
    {
        uint64_t cnt;
        __asm__ __volatile__("mrs %0, CNTVCT_EL0" : "=r"(cnt));
        return cnt;
    }
#elif defined(__powerpc64__) || defined(__powerpc__)
#if defined(__GNUC__) || defined(__clang__)
    return __builtin_ppc_get_timebase();
#else
    return 0;
#endif
#else
    return 0;
#endif
}

/* Monotonic timestamp, always returns nanoseconds.
 *
 * When _c2py_use_cycle_counter == 0 (default):
 *   Returns ns from clock_gettime() on Unix or QueryPerformanceCounter
 *   on Windows.  c2py_tick_frequency_hz == 1e9.
 *
 * When _c2py_use_cycle_counter == 1:
 *   Returns raw cycles from rdtsc/CNTVCT_EL0/timebase.  Convert to ns
 *   via c2py_ticks_to_ns(delta, c2py_tick_frequency_hz) where
 *   c2py_tick_frequency_hz is set to c2py_cycle_counter_frequency_hz.
 *
 * If the cycle counter is requested but the platform does not support
 * it (c2py_cycle_counter_ticks() returns 0), silently falls back to
 * wall-clock nanoseconds. */
static inline uint64_t c2py_ticks(void) {
    if (_c2py_use_cycle_counter) {
        uint64_t c = c2py_cycle_counter_ticks();
        if (c != 0) return c;
    }
#ifdef _WIN32
    {
        LARGE_INTEGER freq, counter;
        QueryPerformanceFrequency(&freq);
        QueryPerformanceCounter(&counter);
        return (uint64_t)(counter.QuadPart * 1000000000ULL / freq.QuadPart);
    }
#elif !defined(__STRICT_ANSI__)
    {
        struct timespec ts;
        clock_gettime(CLOCK_MONOTONIC, &ts);
        return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
    }
#else
    /* no clock_gettime -- fall back to 0 */
    return 0;
#endif
}

/* Convert cycle counter ticks to nanoseconds given the counter frequency
 * in Hz.  Returns ticks * 1e9 / freq_hz.
 * Safe against freq_hz == 0 (returns 0).  May overflow if ticks exceeds
 * ~1.8e10 (18 seconds at 1 GHz), which is well beyond any per-call timing.
 */
static inline uint64_t c2py_ticks_to_ns(uint64_t ticks, uint64_t freq_hz) {
    if (freq_hz == 0) return 0;
    return ticks * 1000000000ULL / freq_hz;
}

/* Active tick source frequency in Hz, set at init and updated when
 * _c2py_use_cycle_counter is toggled via __c2py_set_tick_source().
 * Default (wall clock): 1,000,000,000 (ns ticks).
 * Cycle counter mode: detected cycle counter frequency, or 0 if
 * the platform cannot be probed. */
extern uint64_t c2py_tick_frequency_hz;

/* Returns the active tick source frequency in Hz.  Generated wrapper
 * code uses this to convert tick deltas to nanoseconds. */
static inline uint64_t c2py_tick_frequency(void) {
    return c2py_tick_frequency_hz;
}

/* Update a perf record with one call's tick measurements.
 * t_enter:  wrapper entry
 * t_pre_c:  just before C call
 * t_post_c: just after C returns
 * t_exit:   just before returning to Python
 */
static inline void c2py_perf_record(c2py_perf_t *p,
    uint64_t t_enter, uint64_t t_pre_c, uint64_t t_post_c, uint64_t t_exit)
{
    uint64_t c_dur = t_post_c - t_pre_c;
    uint64_t w_dur = (t_pre_c - t_enter) + (t_exit - t_post_c);

    p->call_count++;
    p->t_enter  = t_enter;
    p->t_pre_c  = t_pre_c;
    p->t_post_c = t_post_c;
    p->t_exit   = t_exit;

    p->t_c_total += c_dur;
    p->t_wrap_total += w_dur;

    if (p->call_count == 1) {
        p->t_c_min = c_dur;
        p->t_c_max = c_dur;
        p->t_wrap_min = w_dur;
        p->t_wrap_max = w_dur;
    } else {
        if (c_dur < p->t_c_min) p->t_c_min = c_dur;
        if (c_dur > p->t_c_max) p->t_c_max = c_dur;
        if (w_dur < p->t_wrap_min) p->t_wrap_min = w_dur;
        if (w_dur > p->t_wrap_max) p->t_wrap_max = w_dur;
    }
}

/* Update a perf record for a single C call (no wrapper overhead).
 * Used for per-overload timing inside _impl functions. */
static inline void c2py_perf_record_call(c2py_perf_t *p,
    uint64_t t_pre, uint64_t t_post)
{
    uint64_t c_dur = t_post - t_pre;

    p->call_count++;
    p->t_pre_c  = t_pre;
    p->t_post_c = t_post;

    p->t_c_total += c_dur;

    if (p->call_count == 1) {
        p->t_c_min = c_dur;
        p->t_c_max = c_dur;
    } else {
        if (c_dur < p->t_c_min) p->t_c_min = c_dur;
        if (c_dur > p->t_c_max) p->t_c_max = c_dur;
    }
}

/* Zero a c2py_perf_t struct, resetting all counters to their
 * initial state.  Safe to call with timing enabled or disabled. */
static inline void c2py_perf_reset(c2py_perf_t *p)
{
    if (p != NULL) {
        memset(p, 0, sizeof(c2py_perf_t));
        p->variant = -1;       /* unset */
        p->group_idx = -1;     /* flat */
        p->t_c_min = UINT64_MAX;
        p->t_wrap_min = UINT64_MAX;
    }
}

/* Copy all uint64_t fields from a c2py_perf_t into a caller-provided
 * array.  buf must have room for 11 elements:
 *   [0] call_count,     [1] t_enter,        [2] t_pre_c,
 *   [3] t_post_c,       [4] t_exit,
 *   [5] t_c_min,        [6] t_c_max,        [7] t_c_total,
 *   [8] t_wrap_min,     [9] t_wrap_max,     [10] t_wrap_total
 *
 * The variant, group_idx, and variant_name fields are NOT included
 * here (they are not uint64_t).  Use c2py_perf_t members directly
 * for those, or a separate helper. */
static inline void c2py_perf_extract_u64(const c2py_perf_t *p,
                                         uint64_t *buf)
{
    buf[0] = p->call_count;
    buf[1] = p->t_enter;
    buf[2] = p->t_pre_c;
    buf[3] = p->t_post_c;
    buf[4] = p->t_exit;
    buf[5] = p->t_c_min;
    buf[6] = p->t_c_max;
    buf[7] = p->t_c_total;
    buf[8] = p->t_wrap_min;
    buf[9] = p->t_wrap_max;
    buf[10] = p->t_wrap_total;
}

/* ------------------------------------------------------------------ */
/* CPU feature probing (for user extensibility, callable from         */
/* __attribute__((constructor)) functions)                            */
/* ------------------------------------------------------------------ */

#ifdef __x86_64__
#if defined(_MSC_VER)
#include <intrin.h>
static inline unsigned int c2py_cpuid_reg(int leaf, int subleaf, int reg) {
    int info[4];
    __cpuidex(info, leaf, subleaf);
    switch (reg & 3) {
    case 0: return (unsigned int)info[0];
    case 1: return (unsigned int)info[1];
    case 2: return (unsigned int)info[2];
    default: return (unsigned int)info[3];
    }
}
#elif defined(__GNUC__) || defined(__clang__)
static inline unsigned int c2py_cpuid_reg(int leaf, int subleaf, int reg) {
    unsigned int eax = 0, ebx = 0, ecx = 0, edx = 0;
    __asm__ __volatile__(
        "cpuid"
        : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
        : "a"(leaf), "c"(subleaf));
    switch (reg & 3) {
    case 0: return eax;
    case 1: return ebx;
    case 2: return ecx;
    default: return edx;
    }
}
#else
static inline unsigned int c2py_cpuid_reg(int leaf, int subleaf, int reg) {
    (void)leaf; (void)subleaf; (void)reg;
    return 0;
}
#endif

static inline int c2py_cpuid_bit(int leaf, int subleaf, int reg, int bit) {
    return (c2py_cpuid_reg(leaf, subleaf, reg) >> bit) & 1;
}

/* Do NOT call cpu_supports from constructors; it may malloc internally.
 * Use c2py_cpuid_bit() instead for custom feature probes. */
#endif

/* ------------------------------------------------------------------ */
/* Init function                                                      */
/* ------------------------------------------------------------------ */

int c2py_runtime_init(void);

#ifdef __cplusplus
}
#endif



#endif /* C2PY_H */

/* ================================================================ */
/* Implementation section (only compiled when C2PY_IMPLEMENTATION     */
/* is defined)                                                       */
/* ================================================================ */

#ifdef C2PY_IMPLEMENTATION
/* c2py_runtime.c - CPython C-extension runtime loader
 *
 * Uses dlopen(NULL, ...) + dlsym() to resolve all CPython C API
 * function pointers at module load time (nimpy trick).  This eliminates
 * the need to link against -lpython, allowing one .so to work across
 * Python 2.7 through 3.15.
 *
 * In --pythonh mode (C2PY_USE_PYTHON_H defined), includes <Python.h>
 * directly.  No cross-version portability; one .so per Python version.
 *
 * Compile: gcc -c c2py_runtime.c -o c2py_runtime.o
 * Link:    gcc -shared ... c2py_runtime.o -ldl -o module.so
 */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <assert.h>
#include <stdio.h>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#elif defined(__linux__)
#include <dlfcn.h>
#include <sys/auxv.h> /* Linux: getauxval for CPU feature detection on ARM64/POWER */
#include <pthread.h>
#else
#include <dlfcn.h>
#include <pthread.h>
#endif


#ifdef _MSC_VER
#include <intrin.h>
#endif


#ifdef _WIN32
#define C2PY_RESOLVE(handle, name) GetProcAddress((HMODULE)(handle), (name))
#else
#define C2PY_RESOLVE(handle, name) dlsym((handle), (name))
#endif

/* ---- Shared globals (visible to both backends) ---- */

/* CPU feature flags  --  always defined so .c2py files can reference
 * any arch features without link errors.  Non-matching arches stay 0. */

int c2py_amd64_mmx = 0;
int c2py_amd64_sse = 0;
int c2py_amd64_sse2 = 0;
int c2py_amd64_sse3 = 0;
int c2py_amd64_ssse3 = 0;
int c2py_amd64_sse4_1 = 0;
int c2py_amd64_sse4_2 = 0;
int c2py_amd64_avx = 0;
int c2py_amd64_avx2 = 0;
int c2py_amd64_fma = 0;
int c2py_amd64_avx512f = 0;
int c2py_amd64_avx512bw = 0;
int c2py_amd64_avx512dq = 0;
int c2py_amd64_avx512vl = 0;
int c2py_amd64_bmi1 = 0;
int c2py_amd64_bmi2 = 0;
int c2py_amd64_popcnt = 0;
int c2py_amd64_lzcnt = 0;

int c2py_arm64_fp = 0;
int c2py_arm64_asimd = 0;
int c2py_arm64_aes = 0;
int c2py_arm64_pmull = 0;
int c2py_arm64_sha1 = 0;
int c2py_arm64_sha2 = 0;
int c2py_arm64_crc32 = 0;
int c2py_arm64_sve = 0;
int c2py_arm64_sve2 = 0;

int c2py_ppc64_altivec = 0;
int c2py_ppc64_vsx = 0;
int c2py_ppc64_power8 = 0;
int c2py_ppc64_power9 = 0;

/* Tick source: 0 = wall clock (default), 1 = CPU cycle counter */
int _c2py_use_cycle_counter = 0;

/* Detected cycle counter frequency, or 0 if unknown (probed at init). */
uint64_t c2py_cycle_counter_frequency_hz = 0;

/* Active tick source frequency in Hz. */
uint64_t c2py_tick_frequency_hz = 0;

/* Runtime-discovered numpy ndarray layout (zero = not yet probed).
 * Shared by both backends (extern in c2py_runtime.h). */
c2py_ndarray_layout_t C2PY_NDARRAY = {0};

/* ---- Shared CPU feature probing (called by both backends) ---- */

static void _c2py_probe_cpu_features(void)
{
#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)
    unsigned int eax1, ebx1, ecx1, edx1;
    unsigned int eax7, ebx7, ecx7, edx7;
    unsigned int eax81, ebx81, ecx81, edx81;
    unsigned int max_std;

#if defined(_MSC_VER)
    {
        int info[4];
        __cpuidex(info, 0, 0);
        max_std = (unsigned int)info[0];

        if (max_std >= 1) {
            __cpuidex(info, 1, 0);
            eax1 = (unsigned int)info[0];
            ebx1 = (unsigned int)info[1];
            ecx1 = (unsigned int)info[2];
            edx1 = (unsigned int)info[3];
            c2py_amd64_mmx    = (edx1 >> 23) & 1;
            c2py_amd64_sse    = (edx1 >> 25) & 1;
            c2py_amd64_sse2   = (edx1 >> 26) & 1;
            c2py_amd64_sse3   = (ecx1 >>  0) & 1;
            c2py_amd64_ssse3  = (ecx1 >>  9) & 1;
            c2py_amd64_sse4_1 = (ecx1 >> 19) & 1;
            c2py_amd64_sse4_2 = (ecx1 >> 20) & 1;
            c2py_amd64_avx    = (ecx1 >> 28) & 1;
            c2py_amd64_fma    = (ecx1 >> 12) & 1;
            c2py_amd64_popcnt = (ecx1 >> 23) & 1;
        }
        if (max_std >= 7) {
            __cpuidex(info, 7, 0);
            ebx7 = (unsigned int)info[1];
            ecx7 = (unsigned int)info[2];
            edx7 = (unsigned int)info[3];
            c2py_amd64_bmi1    = (ebx7 >>  3) & 1;
            c2py_amd64_avx2    = (ebx7 >>  5) & 1;
            c2py_amd64_bmi2    = (ebx7 >>  8) & 1;
            c2py_amd64_avx512f = (ebx7 >> 16) & 1;
            c2py_amd64_avx512dq = (ebx7 >> 17) & 1;
            c2py_amd64_avx512bw = (ebx7 >> 30) & 1;
            c2py_amd64_avx512vl = (ebx7 >> 31) & 1;
        }
        __cpuidex(info, 0x80000000, 0);
        if ((unsigned int)info[0] >= 0x80000001) {
            __cpuidex(info, 0x80000001, 0);
            ecx81 = (unsigned int)info[2];
            c2py_amd64_lzcnt = (ecx81 >> 5) & 1;
        }
    }
#elif defined(__GNUC__) || defined(__clang__)
    /* Determine max standard leaf */
    __asm__ __volatile__("cpuid"
        : "=a"(eax1) : "a"(0) : "ebx", "ecx", "edx");
    max_std = eax1;

    /* Leaf 1: baseline features */
    if (max_std >= 1) {
        __asm__ __volatile__("cpuid"
            : "=a"(eax1), "=b"(ebx1), "=c"(ecx1), "=d"(edx1)
            : "a"(1) : );
        c2py_amd64_mmx    = (edx1 >> 23) & 1;
        c2py_amd64_sse    = (edx1 >> 25) & 1;
        c2py_amd64_sse2   = (edx1 >> 26) & 1;
        c2py_amd64_sse3   = (ecx1 >>  0) & 1;
        c2py_amd64_ssse3  = (ecx1 >>  9) & 1;
        c2py_amd64_sse4_1 = (ecx1 >> 19) & 1;
        c2py_amd64_sse4_2 = (ecx1 >> 20) & 1;
        c2py_amd64_avx    = (ecx1 >> 28) & 1;
        c2py_amd64_fma    = (ecx1 >> 12) & 1;
        c2py_amd64_popcnt = (ecx1 >> 23) & 1;
    }

    /* Leaf 7, subleaf 0: extended features */
    if (max_std >= 7) {
        __asm__ __volatile__("cpuid"
            : "=a"(eax7), "=b"(ebx7), "=c"(ecx7), "=d"(edx7)
            : "a"(7), "c"(0));
        c2py_amd64_bmi1    = (ebx7 >>  3) & 1;
        c2py_amd64_avx2    = (ebx7 >>  5) & 1;
        c2py_amd64_bmi2    = (ebx7 >>  8) & 1;
        c2py_amd64_avx512f = (ebx7 >> 16) & 1;
        c2py_amd64_avx512dq = (ebx7 >> 17) & 1;
        c2py_amd64_avx512bw = (ebx7 >> 30) & 1;
        c2py_amd64_avx512vl = (ebx7 >> 31) & 1;
    }

    /* Leaf 0x80000001: extended feature bits (LZCNT) */
    /* Check extended leaf max first */
    __asm__ __volatile__("cpuid"
        : "=a"(eax81) : "a"(0x80000000) : "ebx", "ecx", "edx");
    if (eax81 >= 0x80000001) {
        __asm__ __volatile__("cpuid"
            : "=a"(eax81), "=b"(ebx81), "=c"(ecx81), "=d"(edx81)
            : "a"(0x80000001));
        c2py_amd64_lzcnt = (ecx81 >> 5) & 1;
    }
#else
    /* no inline assembly  --  CPU features stay 0 */
#endif /* _MSC_VER / __GNUC__ */
#endif

#if (defined(__aarch64__) || defined(__arm64__)) && !defined(_WIN32) && !defined(__APPLE__)
    {
        /* getauxval is Linux-specific; macOS ARM64 uses a separate path below. */
        unsigned long hwcap = getauxval(AT_HWCAP);
        unsigned long hwcap2 = getauxval(AT_HWCAP2);

        /* ARM64 HWCAP bits (stable kernel ABI) */
        c2py_arm64_fp    = (hwcap >> 0) & 1;
        c2py_arm64_asimd = (hwcap >> 1) & 1;
        c2py_arm64_aes   = (hwcap >> 3) & 1;
        c2py_arm64_pmull = (hwcap >> 4) & 1;
        c2py_arm64_sha1  = (hwcap >> 5) & 1;
        c2py_arm64_sha2  = (hwcap >> 6) & 1;
        c2py_arm64_crc32 = (hwcap >> 7) & 1;
        c2py_arm64_sve   = (hwcap >> 22) & 1;
        c2py_arm64_sve2  = (hwcap2 >> 1) & 1;
    }
#endif
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    {
        /* Apple Silicon: NEON (asimd) and FP are baseline on all chips.
         * sysctlbyname() can query optional features (AES, SHA, etc.),
         * but for now we set the baseline flags only. */
        c2py_arm64_fp    = 1;
        c2py_arm64_asimd = 1;
    }
#endif

#if (defined(__powerpc64__) || defined(__powerpc__)) && !defined(_WIN32) && !defined(__APPLE__)
    {
        unsigned long hwcap = getauxval(AT_HWCAP);
        unsigned long hwcap2 = getauxval(AT_HWCAP2);

        c2py_ppc64_altivec = (hwcap >> 28) & 1;        /* PPC_FEATURE_HAS_ALTIVEC = 0x10000000 */
        c2py_ppc64_vsx     = (hwcap >>  7) & 1;         /* PPC_FEATURE_HAS_VSX     = 0x00000080 */
        c2py_ppc64_power8  = (hwcap2 >> 31) & 1;        /* PPC_FEATURE2_ARCH_2_07  = 0x80000000 */
        c2py_ppc64_power9  = (hwcap2 >> 23) & 1;        /* PPC_FEATURE2_ARCH_3_00  = 0x00800000 */
    }
#endif

/* ---- Tick source frequency detection ---- */

    /* Default: wall clock returns nanoseconds, frequency is 1e9 Hz.
     * Cycle counter frequency is probed separately below and stored
     * in c2py_cycle_counter_frequency_hz; it is only used when the
     * caller toggles _c2py_use_cycle_counter to 1. */
    c2py_tick_frequency_hz = 1000000000ULL;

    /* Always attempt to detect CPU cycle counter frequency.
     * On platforms without a readable cycle counter this remains 0. */
#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)
    {
#if defined(_MSC_VER)
        int info[4];
        int got_freq = 0;
        __cpuidex(info, 0, 0);
        if ((unsigned int)info[0] >= 0x15) {
            __cpuidex(info, 0x15, 0);
            unsigned int eax = (unsigned int)info[0];
            unsigned int ebx = (unsigned int)info[1];
            unsigned int ecx = (unsigned int)info[2];
            if (ebx != 0 && eax != 0 && ecx != 0) {
                c2py_cycle_counter_frequency_hz =
                    (uint64_t)ecx * (uint64_t)ebx / (uint64_t)eax;
                got_freq = 1;
            }
        }
        if (!got_freq) {
            LARGE_INTEGER qpf;
            if (QueryPerformanceFrequency(&qpf) && qpf.QuadPart > 0) {
                c2py_cycle_counter_frequency_hz = (uint64_t)qpf.QuadPart;
            }
        }
#elif defined(__GNUC__) || defined(__clang__)
        unsigned int eax, ebx, ecx, edx;
        unsigned int max_std;
        int got_freq = 0;
        __asm__ __volatile__("cpuid" : "=a"(max_std) : "a"(0) : "ebx", "ecx", "edx");
        if (max_std >= 0x15) {
            __asm__ __volatile__("cpuid"
                : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
                : "a"(0x15));
            if (ebx != 0 && eax != 0 && ecx != 0) {
                c2py_cycle_counter_frequency_hz =
                    (uint64_t)ecx * (uint64_t)ebx / (uint64_t)eax;
                got_freq = 1;
            }
        }
        if (!got_freq) {
            FILE *f = fopen("/proc/cpuinfo", "r");
            if (f) {
                char line[256];
                while (fgets(line, sizeof(line), f)) {
                    double mhz;
                    if (sscanf(line, "cpu MHz : %lf", &mhz) == 1) {
                        c2py_cycle_counter_frequency_hz =
                            (uint64_t)(mhz * 1000000.0 + 0.5);
                        break;
                    }
                }
                fclose(f);
            }
        }
#else
        /* no inline assembly  --  cycle counter frequency stays 0 */
#endif /* _MSC_VER / __GNUC__ */
    }
#elif (defined(__aarch64__) || defined(__arm64__)) && !defined(_MSC_VER) \
      && (defined(__GNUC__) || defined(__clang__))
    {
        uint64_t freq;
        __asm__ __volatile__("mrs %0, CNTFRQ_EL0" : "=r"(freq));
        if (freq != 0) {
            c2py_cycle_counter_frequency_hz = freq;
        }
    }
#elif defined(__powerpc64__) || defined(__powerpc__)
    {
#ifdef _WIN32
        c2py_cycle_counter_frequency_hz = 0;
#else
        FILE *f = fopen("/proc/device-tree/cpus/timebase-frequency", "r");
        if (f) {
            unsigned char buf[8] = {0};
            size_t r = fread(buf, 1, 8, f);
            fclose(f);
            if (r == 4) {
                c2py_cycle_counter_frequency_hz =
                    ((uint64_t)buf[0] << 24) |
                    ((uint64_t)buf[1] << 16) |
                    ((uint64_t)buf[2] << 8)  |
                     (uint64_t)buf[3];
            } else if (r >= 8) {
                c2py_cycle_counter_frequency_hz =
                    ((uint64_t)buf[0] << 56) |
                    ((uint64_t)buf[1] << 48) |
                    ((uint64_t)buf[2] << 40) |
                    ((uint64_t)buf[3] << 32) |
                    ((uint64_t)buf[4] << 24) |
                    ((uint64_t)buf[5] << 16) |
                    ((uint64_t)buf[6] << 8)  |
                     (uint64_t)buf[7];
            }
        }
#endif /* _WIN32 */
    }
#endif
    /* If detection failed, c2py_cycle_counter_frequency_hz remains 0. */
}

/* ---- Backend selection ---- */
#ifdef C2PY_USE_PYTHON_H

/* c2py_pythonh.c - pythonh backend (runtime init)
 *
 * This file is #included by c2py_runtime.c when C2PY_USE_PYTHON_H is
 * defined.  Do NOT compile this file directly.
 */

/* ---- C2PY global ---- */

c2py_api_t C2PY = {0};

/* ---- Python 2.7 module init helper ---- */

#if PY_MAJOR_VERSION == 2
static PyObject*
_c2py_pythonh_init_module(const char *name, PyMethodDef *methods)
{
    PyObject *m = Py_InitModule3(name, methods, "");
    if (m != NULL) {
        C2PY._ds_set_item_string = (void *)PyDict_SetItemString;
        C2PY._ds_pypy_workaround = 1;
    }
    return m;
}
#endif

/* ---- c2py_runtime_init ---- */

int c2py_runtime_init(void)
{
    /* CPU feature probing (shared with dlsym backend) */
    _c2py_probe_cpu_features();

    /* ---- Both Python 2 and 3 (common) ---- */

    C2PY.GetBuffer     = PyObject_GetBuffer;
    C2PY.ReleaseBuffer = PyBuffer_Release;
    C2PY.Err_Clear     = PyErr_Clear;
    C2PY.buffer_api_is_pep3118 = 1;
    C2PY.ParseTuple    = (int (*)(PyObject*, const char*, ...))PyArg_ParseTuple;
    C2PY.Long_FromLong      = PyLong_FromLong;
    C2PY.Float_FromDouble   = PyFloat_FromDouble;
    C2PY.Tuple_New          = PyTuple_New;
    C2PY.Tuple_SetItem      = PyTuple_SetItem;
    C2PY.Bytes_FromStringAndSize = PyBytes_FromStringAndSize;
    C2PY.Long_AsLong        = PyLong_AsLong;
    C2PY.Float_AsDouble     = PyFloat_AsDouble;
    C2PY.Err_SetString      = PyErr_SetString;
    C2PY.Err_Occurred       = PyErr_Occurred;
    C2PY.Err_Format         = (PyObject*(*)(PyObject*,const char*,...))PyErr_Format;
    C2PY.none_obj           = Py_None;
    C2PY.SetAttrString      = PyObject_SetAttrString;
    C2PY.GetAttrString      = PyObject_GetAttrString;
    C2PY.Module_GetDict     = PyModule_GetDict;
    C2PY._ds_set_item_string = (void *)PyDict_SetItemString;
    C2PY.CallObject         = PyObject_CallObject;
    C2PY.Long_FromVoidPtr   = PyLong_FromVoidPtr;
    C2PY.SaveThread         = (void*(*)(void))PyEval_SaveThread;
    C2PY.RestoreThread      = (void(*)(void*))PyEval_RestoreThread;
    C2PY.exc_TypeError      = (void *)PyExc_TypeError;
    C2PY.exc_ValueError     = (void *)PyExc_ValueError;
    C2PY.exc_RuntimeError   = (void *)PyExc_RuntimeError;
    C2PY.exc_MemoryError    = (void *)PyExc_MemoryError;

    C2PY.version_major      = PY_MAJOR_VERSION;
    C2PY.version_minor      = PY_MINOR_VERSION;
    C2PY.pybuffer_size      = sizeof(Py_buffer);
    C2PY.pyobject_size      = sizeof(PyObject);
    C2PY.pyobject_size_ft   = sizeof(PyObject);

#if defined(Py_GIL_DISABLED) && Py_GIL_DISABLED
    C2PY.ob_refcnt_offset   = offsetof(PyObject, ob_ref_shared);
#else
    C2PY.ob_refcnt_offset   = offsetof(PyObject, ob_refcnt);
#endif
    C2PY.ob_type_offset     = offsetof(PyObject, ob_type);

    c2py_tick_frequency_hz          = 1000000000ULL;

    /* ---- Python 2 defaults (overridden below for Python 3) ---- */

    C2PY.Long_FromLongLong         = NULL;
    C2PY.Long_FromUnsignedLongLong = NULL;
    C2PY.Long_AsLongLong           = NULL;
    C2PY.exc_BufferError           = NULL;
    C2PY.none_immortal             = 0;
    C2PY.Module_Create2            = NULL;
    C2PY.use_fastcall              = 0;
    C2PY.is_free_threaded          = 0;
    C2PY.Capsule_GetPointer        = NULL;
    C2PY.is_pypy                   = 0;
    C2PY.Unstable_Module_SetGIL    = NULL;
    C2PY._ds_pypy_workaround       = 0;
    C2PY.pymoduledef_max_size      = 0;
    c2py_cycle_counter_frequency_hz = 0;

#if PY_MAJOR_VERSION == 2
    C2PY.InitModule_2_7            = _c2py_pythonh_init_module;
    C2PY.IncRef                    = NULL;   /* manual refcount on 2.7 */
    C2PY.DecRef                    = NULL;
#else
    C2PY.InitModule_2_7            = NULL;
#endif

    /* ---- Python 3 overrides ---- */

#if PY_MAJOR_VERSION >= 3
    C2PY.Long_FromLongLong         = (PyObject*(*)(long long))PyLong_FromLongLong;
    C2PY.Long_FromUnsignedLongLong = (PyObject*(*)(unsigned long long))PyLong_FromUnsignedLongLong;
    C2PY.Long_AsLongLong           = (long long(*)(PyObject*))PyLong_AsLongLong;
    C2PY.Module_Create2            = (PyObject*(*)(PyModuleDef*,int))PyModule_Create2;
    C2PY.Capsule_GetPointer        = PyCapsule_GetPointer;
    C2PY.pymoduledef_max_size      = sizeof(PyModuleDef);

    if (PY_MINOR_VERSION >= 3) {
        C2PY.exc_BufferError       = (void *)PyExc_BufferError;
    }
    if (PY_MINOR_VERSION >= 7) {
        C2PY.use_fastcall          = 1;
    }
    if (PY_MINOR_VERSION >= 12) {
        C2PY.none_immortal         = 1;
#if defined(Py_IncRef)
        C2PY.IncRef                = Py_IncRef;
        C2PY.DecRef                = Py_DecRef;
#endif
    }

# if defined(Py_GIL_DISABLED)
    C2PY.is_free_threaded          = Py_GIL_DISABLED;
# endif
#endif /* PY_MAJOR_VERSION >= 3 */

    return 0;
}

#else

/* ---- Nimpy/dlsym backend ---- */

/* Global API table */
c2py_api_t C2PY = {0};

static volatile int _c2py_runtime_initialized = 0;
static int _c2py_init_result = 0;

#ifndef _WIN32
static pthread_once_t _c2py_init_once = PTHREAD_ONCE_INIT;
#else
static CRITICAL_SECTION _c2py_init_cs;
static BOOL _c2py_init_cs_ready = FALSE;
#endif

/* c2py_dlsym.c - nimpy-style dlsym backend (runtime init)
 *
 * This file is #included by c2py_runtime.c when C2PY_USE_PYTHON_H is
 * NOT defined.  Do NOT compile this file directly.
 *
 * Contains: symbol resolution helpers, CPU feature probe, module init
 * helpers, and the main _c2py_runtime_init_once() function.
 */

/* ---- Private helpers ---- */

/* On Windows GetProcAddress returns a function-pointer type;
 * casting it to void* and back is inherent to the nimpy trick. */
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4152)
#endif
static int _resolve(void **ptr, const char *name)
{
    *ptr = C2PY_RESOLVE(C2PY.dl_handle, name);
    if (*ptr == NULL) {
        /* Try PyPy symbol prefix: "Py_Xxx" -> "PyPy_Xxx",
         *                           "_Py_Xxx" -> "_PyPy_Xxx".
         * PyPy's cpyext exports all CPython API symbols under
         * the PyPy_* prefix from libpypy3.X-c.so.  This
         * fallback lets a single .so work on both runtimes. */
        char pypy_name[256];
        int prefix_len = (name[0] == '_') ? 3 : 2;
        snprintf(pypy_name, sizeof(pypy_name), "%.*sPy%s",
                 prefix_len, name, name + prefix_len);
        *ptr = C2PY_RESOLVE(C2PY.dl_handle, pypy_name);
        if (*ptr == NULL) {
            return -1;
        }
    }
    return 0;
}

/* Same as _resolve but returns the pointer directly (for raw C2PY_RESOLVE
 * call sites that need the PyPy fallback). */
static void *_resolve_raw(const char *name)
{
    void *p = C2PY_RESOLVE(C2PY.dl_handle, name);
    if (p) return p;
    char pypy_name[256];
    int prefix_len = (name[0] == '_') ? 3 : 2;
    snprintf(pypy_name, sizeof(pypy_name), "%.*sPy%s",
             prefix_len, name, name + prefix_len);
    return C2PY_RESOLVE(C2PY.dl_handle, pypy_name);
}
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#define RESOLVE(ptr, name) _resolve((void**)&(ptr), name)
#define RESOLVE_REQ(ptr, name) do { \
    if (_resolve((void**)&(ptr), name) != 0) { \
        fprintf(stderr, "c2py_runtime: FATAL - missing symbol: %s\n", name); \
        return; \
    } \
} while(0)

/* Python 2.7 module init helper */
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4152)
#endif
static PyObject*
_init_module_2_7(const char *name, PyMethodDef *methods)
{
    /* Try Py_InitModule4 first (Python 2.7 preferred) */
    typedef PyObject* (*init4_fn)(const char*, PyMethodDef*, const char*,
                                   PyObject*, int);
    init4_fn fn4 = (init4_fn)_resolve_raw("Py_InitModule4_64");
    if (fn4 == NULL) fn4 = (init4_fn)_resolve_raw("Py_InitModule4");
    if (fn4 != NULL) {
        return fn4(name, methods, NULL, NULL, 1013 /* PYTHON_API_VERSION */);
    }

    /* Fallback: Py_InitModule3 */
    typedef PyObject* (*init3_fn)(const char*, PyMethodDef*, const char*);
    init3_fn fn3 = (init3_fn)_resolve_raw("Py_InitModule3");
    if (fn3 != NULL) {
        return fn3(name, methods, NULL);
    }

    /* PyPy 2.7 cpyext: no Py_InitModule*, use PyModule_New + manual
     * method registration via PyModule_GetDict + PyDict_SetItemString.
     * Resolve these symbols on demand (only needed for this fallback). */
    {
        typedef PyObject* (*mod_new_fn)(const char*);
        typedef PyObject* (*mod_dict_fn)(PyObject*);
        typedef PyObject* (*cfn_new_fn)(PyMethodDef*, PyObject*, PyObject*);
        typedef PyObject* (*imp_add_fn)(const char*);

        imp_add_fn imp_add = (imp_add_fn)_resolve_raw("PyImport_AddModule");
        mod_new_fn mnew = imp_add
            ? NULL : (mod_new_fn)_resolve_raw("PyModule_New");
        mod_dict_fn mdict = (mod_dict_fn)_resolve_raw("PyModule_GetDict");
        cfn_new_fn cfn_new = (cfn_new_fn)_resolve_raw("PyCFunction_NewEx");

        /* Prefer PyImport_AddModule: it registers in sys.modules
         * and returns a module that supports attribute setting.
         * On PyPy 2.7 cpyext, PyModule_New creates a module that
         * cannot have attributes set via SetAttrString. */
        PyObject *module = imp_add ? imp_add(name) : (mnew ? mnew(name) : NULL);
        if (module && mdict && cfn_new) {
            PyObject *dict = mdict(module);
            if (dict) {
                while (methods && methods->ml_name) {
                PyObject *fn = cfn_new(methods, NULL, NULL);
                if (fn) {
                    if (C2PY._ds_set_item_string) {
                        typedef int (*dset_fn)(PyObject*, const char*, PyObject*);
                        ((dset_fn)C2PY._ds_set_item_string)(dict, methods->ml_name, fn);
                    }
                    Py_DECREF(fn);
                }
                    methods++;
                }
                return module;
            }
        }
    }

    fprintf(stderr, "c2py_runtime: could not find module init function\n");
    return NULL;
}
#ifdef _MSC_VER
#pragma warning(pop)
#endif




/* ---- Main init function ---- */

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4152)  /* GetProcAddress fn/data ptr cast */
#endif
static void _c2py_runtime_init_once(void)
{
    _c2py_init_result = -1;  /* assume failure until full success */

    /* CPU feature probing runs first -- does not depend on Python */
    _c2py_probe_cpu_features();

#ifdef _WIN32
    {
        static const char *candidates[] = {
            "python315.dll", "python314.dll", "python313.dll",
            "python312.dll", "python311.dll", "python310.dll",
            "python39.dll", "python38.dll", "python37.dll",
            "python36.dll", "python27.dll",
            "python3.dll",
            /* Free-threaded builds may use 't' suffix DLL names */
            "python315t.dll", "python314t.dll", "python313t.dll",
            "python3t.dll",
            /* PyPy on Windows exports cpyext symbols from libpypy3.X-c.dll */
            "libpypy3.11-c.dll", "libpypy3.10-c.dll",
            "libpypy3.9-c.dll",  "libpypy3-c.dll",
            "libpypy2.7-c.dll",  "libpypy-c.dll",
            NULL
        };
        int i;
        for (i = 0; candidates[i]; i++) {
            C2PY.dl_handle = (void*)GetModuleHandleA(candidates[i]);
            if (C2PY.dl_handle) break;
        }
        /* On free-threaded and some embedded builds, Python symbols
         * may be exported from the .exe itself rather than a separate
         * DLL.  GetModuleHandleA(NULL) returns the .exe handle. */
        if (C2PY.dl_handle == NULL) {
            C2PY.dl_handle = (void*)GetModuleHandleA(NULL);
        }
        /* Last resort: try to load python3.dll or python3XX.dll
         * explicitly via LoadLibraryA.  This works when the DLL exists
         * on disk but was not loaded as a dependency of the main
         * executable (e.g. free-threaded Python 3.14t/3.15t on Windows
         * where the executable may have a non-standard import table). */
        if (C2PY.dl_handle == NULL) {
            static const char *load_candidates[] = {
                "python3.dll",
                "python315.dll", "python314.dll",
                "python3t.dll",
                "python315t.dll", "python314t.dll",
                NULL
            };
            for (i = 0; load_candidates[i]; i++) {
                C2PY.dl_handle = (void*)LoadLibraryA(load_candidates[i]);
                if (C2PY.dl_handle) break;
            }
        }
        if (C2PY.dl_handle == NULL) {
            fprintf(stderr, "c2py_runtime: GetModuleHandle / LoadLibrary failed "
                    "(python3.dll not found). "
                    "GetLastError=%lu\n", GetLastError());
            fprintf(stderr, "c2py_runtime: interpreter may be statically "
                    "linked or embedded in an unusual host.\n");
            return;
        }
    }
#else
    C2PY.dl_handle = dlopen(NULL, RTLD_LAZY | RTLD_GLOBAL);
    if (C2PY.dl_handle == NULL) {
        fprintf(stderr, "c2py_runtime: dlopen(NULL) failed: %s\n", dlerror());
        fprintf(stderr, "c2py_runtime: interpreter may be statically linked "
                "(requires --enable-shared or export-dynamic).\n");
        return;
    }
    /* If no CPython symbols found, try PyPy's separate C library.
     * PyPy exports cpyext symbols with a PyPy_* prefix from
     * libpypy3.X-c.so rather than the main executable. */
    {
        void *test = dlsym(C2PY.dl_handle, "Py_GetVersion");
        test = test ? test : dlsym(C2PY.dl_handle, "PyPy_GetVersion");
        if (test == NULL) {
            static const char *pypy_libs[] = {
                "libpypy3.11-c.so", "libpypy3.10-c.so",
                "libpypy3.9-c.so",  "libpypy3-c.so",
                "libpypy2.7-c.so",  "libpypy-c.so", NULL
            };
            int i;
            for (i = 0; pypy_libs[i]; i++) {
                void *h = dlopen(pypy_libs[i], RTLD_LAZY | RTLD_GLOBAL);
                if (h) {
                    C2PY.dl_handle = h;
                    break;
                }
            }
        }
    }
#endif

    void *dl = C2PY.dl_handle;

    /* --- Detect Python version --- */
    {
        typedef const char* (*ver_fn)(void);
        ver_fn getver = (ver_fn)_resolve_raw("Py_GetVersion");
        if (getver) {
            const char *v = getver();
#ifdef _MSC_VER
            if (v) sscanf_s(v, "%d.%d", &C2PY.version_major, &C2PY.version_minor);
#else
            if (v) sscanf(v, "%d.%d", &C2PY.version_major, &C2PY.version_minor);
#endif
        }
        if (C2PY.version_major == 0) {
            /* Fallback: check for Py3-only symbol */
            if (_resolve_raw("PyModule_Create2")) {
                C2PY.version_major = 3;
            } else {
                C2PY.version_major = 2;
            }
            C2PY.version_minor = 0;
        }
    }

    /* --- Detect PyPy cpyext ---
     * PyPy's cpyext emulates the CPython C API but with different struct
     * layouts: PyObject is 24 bytes (ob_pypy_link at +8, ob_type at +16),
     * and manual ob_refcnt manipulation is unsafe (must use PyPy_IncRef). */
    {
        void *test = C2PY_RESOLVE(dl, "PyPy_IncRef");
        C2PY.is_pypy = (test != NULL) ? 1 : 0;
    }
    if (C2PY.is_pypy) {
        C2PY.pyobject_size = 24;
        C2PY.ob_refcnt_offset = 0;
        C2PY.ob_type_offset = 16;  /* ob_pypy_link at 8 pushes ob_type to 16 */
    }

    /* --- Reject unsupported Python versions --- */
#ifdef _WIN32
    if (C2PY.version_major >= 3 && C2PY.version_minor > 15) {
        fprintf(stderr,
                "c2py_runtime: Python %d.%d on Windows is not yet supported.\n"
                "Supported versions: 2.7, 3.6-3.15.\n"
                "To add Windows support for a new Python version, audit the CPython\n"
                "headers for ABI changes and update checks in c2py_runtime.c.\n",
                C2PY.version_major, C2PY.version_minor);
        return;
    }
#else
    if (C2PY.version_major >= 3 && C2PY.version_minor > 15) {
        fprintf(stderr,
                "c2py_runtime: Python %d.%d is not supported.\n"
                "Supported versions: 2.7, 3.6-3.15.\n"
                "To add support for a new Python version, audit the CPython\n"
                "headers for ABI changes and update checks in c2py_runtime.c.\n",
                C2PY.version_major, C2PY.version_minor);
        return;
    }
#endif

    /* --- Detect free-threaded build --- */
    if (C2PY.is_pypy) goto ft_detection_done;
    {
        int found_ft = 0;
        const char *force_ft = getenv("C2PY_FORCE_FT");
        if (force_ft != NULL) {
            if (force_ft[0] == '1') {
                found_ft = 1;
            }
            C2PY.is_free_threaded = found_ft;
            goto ft_detection_done;
        }
        {
            typedef const char* (*ver_fn)(void);
            ver_fn getver = (ver_fn)C2PY_RESOLVE(dl, "Py_GetVersion");
            const char *vstr = getver ? getver() : "";
            if (vstr && strstr(vstr, "free-threading") != NULL)
                found_ft = 1;
        }
        if (!found_ft) {
            typedef int (*gil_check_fn)(void);
            gil_check_fn gilchk = (gil_check_fn)C2PY_RESOLVE(dl, "_Py_IsGILEnabled");
            if (gilchk && gilchk() == 0)
                found_ft = 1;
        }
        C2PY.is_free_threaded = found_ft;
    }
    ft_detection_done:
        /* Nothing to do here */

    /* --- Set ABI layout --- */
    if (C2PY.is_pypy) {
        /* already set above */
    } else if (C2PY.is_free_threaded) {
        C2PY.pyobject_size = 32;
        C2PY.ob_refcnt_offset = 16;
        C2PY.ob_type_offset = 24;
    } else {
        C2PY.pyobject_size = sizeof(PyObject);
        C2PY.ob_refcnt_offset = 0;
        C2PY.ob_type_offset = sizeof(Py_ssize_t);
    }
    C2PY.pyobject_size_ft = 32;

    assert(C2PY.pyobject_size > 0);
    assert(C2PY.ob_refcnt_offset >= 0);
    assert(C2PY.ob_type_offset >= 0);
    assert(C2PY.ob_type_offset + (Py_ssize_t)sizeof(void*) <= C2PY.pyobject_size);

    {
        Py_ssize_t sz_gil = sizeof(PyModuleDef);
        Py_ssize_t sz_ft  = sizeof(PyModuleDef_FT);
        C2PY.pymoduledef_max_size = (sz_gil > sz_ft) ? sz_gil : sz_ft;
    }

    /* --- Buffer protocol (required) --- */
    RESOLVE_REQ(C2PY.GetBuffer, "PyObject_GetBuffer");
    RESOLVE_REQ(C2PY.ReleaseBuffer, "PyBuffer_Release");
    if (C2PY.GetBuffer == NULL || C2PY.ReleaseBuffer == NULL) return;

    C2PY.AsReadBuffer = (int (*)(PyObject*, const void**, Py_ssize_t*))
        _resolve_raw("PyObject_AsReadBuffer");
    C2PY.AsWriteBuffer = (int (*)(PyObject*, void**, Py_ssize_t*))
        _resolve_raw("PyObject_AsWriteBuffer");
    C2PY.Err_Clear = (void (*)(void))_resolve_raw("PyErr_Clear");
    RESOLVE_REQ(C2PY.Err_Clear, "PyErr_Clear");
    if (C2PY.Err_Clear == NULL) return;
    C2PY.buffer_api_is_pep3118 = (C2PY.version_major >= 3);

    C2PY.pybuffer_size = (C2PY.version_major >= 3)
        ? C2PY_PYBUFFER_SZ_POST312 : C2PY_PYBUFFER_SZ_PRE312;

    C2PY.use_fastcall = (C2PY.version_major >= 3 && C2PY.version_minor >= 12);

    RESOLVE_REQ(C2PY.ParseTuple, "PyArg_ParseTuple");
    if (C2PY.ParseTuple == NULL) return;

    RESOLVE_REQ(C2PY.Err_Occurred, "PyErr_Occurred");
    if (C2PY.Err_Occurred == NULL) return;

    RESOLVE_REQ(C2PY.Long_FromLong, "PyLong_FromLong");
    RESOLVE_REQ(C2PY.Long_FromLongLong, "PyLong_FromLongLong");
    RESOLVE_REQ(C2PY.Long_FromUnsignedLongLong, "PyLong_FromUnsignedLongLong");
    RESOLVE_REQ(C2PY.Float_FromDouble, "PyFloat_FromDouble");
    if (C2PY.Long_FromLong == NULL || C2PY.Float_FromDouble == NULL) return;

    /* Runtime PyObject layout probe */
    {
        PyObject *tmp = C2PY.Long_FromLong(1);
        if (tmp) {
            void *p_type = *(void**)((char*)tmp + sizeof(Py_ssize_t));
            if (p_type != NULL && (uintptr_t)p_type >= 0x100000) {
                /* GIL layout confirmed */
            } else {
                C2PY.is_free_threaded = 1;
                C2PY.pyobject_size = 32;
                C2PY.ob_refcnt_offset = 16;
                C2PY.ob_type_offset = 24;
            }
            {
                typedef void (*dref_fn)(PyObject*);
                dref_fn dref = (dref_fn)_resolve_raw("Py_DecRef");
                if (!dref) dref = (dref_fn)_resolve_raw("_Py_DecRef");
                if (dref) dref(tmp);
            }
        }
    }

    RESOLVE_REQ(C2PY.Tuple_New, "PyTuple_New");
    RESOLVE_REQ(C2PY.Tuple_SetItem, "PyTuple_SetItem");
    if (C2PY.Tuple_New == NULL || C2PY.Tuple_SetItem == NULL) return;

    RESOLVE(C2PY.Bytes_FromStringAndSize, "PyBytes_FromStringAndSize");

    RESOLVE_REQ(C2PY.Long_AsLong, "PyLong_AsLong");
    RESOLVE_REQ(C2PY.Long_AsLongLong, "PyLong_AsLongLong");
    RESOLVE_REQ(C2PY.Float_AsDouble, "PyFloat_AsDouble");
    if (C2PY.Long_AsLong == NULL || C2PY.Long_AsLongLong == NULL ||
        C2PY.Float_AsDouble == NULL) return;

    RESOLVE_REQ(C2PY.exc_TypeError, "PyExc_TypeError");
    RESOLVE_REQ(C2PY.exc_ValueError, "PyExc_ValueError");
    RESOLVE_REQ(C2PY.exc_RuntimeError, "PyExc_RuntimeError");
    RESOLVE_REQ(C2PY.exc_MemoryError, "PyExc_MemoryError");
    RESOLVE_REQ(C2PY.Err_SetString, "PyErr_SetString");
    RESOLVE_REQ(C2PY.Err_Format, "PyErr_Format");
    if (C2PY.exc_TypeError   == NULL || C2PY.exc_ValueError  == NULL ||
        C2PY.exc_RuntimeError == NULL || C2PY.exc_MemoryError == NULL ||
        C2PY.Err_SetString    == NULL || C2PY.Err_Format      == NULL) return;

    C2PY.exc_TypeError = *(void **)C2PY.exc_TypeError;
    C2PY.exc_ValueError = *(void **)C2PY.exc_ValueError;
    C2PY.exc_RuntimeError = *(void **)C2PY.exc_RuntimeError;
    C2PY.exc_MemoryError = *(void **)C2PY.exc_MemoryError;
    C2PY.exc_BufferError = C2PY.exc_BufferError ? *(void **)C2PY.exc_BufferError : NULL;

    {
        void *mc = _resolve_raw("PyModule_Create2");
        C2PY.Module_Create2 = (PyObject* (*)(PyModuleDef*, int))mc;
    }
    C2PY.InitModule_2_7 = _init_module_2_7;

    {
        if (_resolve((void**)&C2PY.IncRef, "Py_IncRef") != 0)
            _resolve((void**)&C2PY.IncRef, "_Py_IncRef");
        if (_resolve((void**)&C2PY.DecRef, "Py_DecRef") != 0)
            _resolve((void**)&C2PY.DecRef, "_Py_DecRef");

        if (C2PY.is_free_threaded) {
            if (C2PY.IncRef == NULL || C2PY.DecRef == NULL) {
                fprintf(stderr, "c2py_runtime: FATAL - free-threaded build "
                        "requires Py_IncRef / Py_DecRef symbols\n");
                return;
            }
        } else {
            if (C2PY.IncRef == NULL)
                C2PY.IncRef = _c2py_inc_ref_manual;
            if (C2PY.DecRef == NULL)
                C2PY.DecRef = _c2py_dec_ref_manual;
        }
    }

    RESOLVE_REQ(C2PY.SetAttrString, "PyObject_SetAttrString");
    if (C2PY.SetAttrString == NULL) return;
    RESOLVE_REQ(C2PY.GetAttrString, "PyObject_GetAttrString");
    if (C2PY.GetAttrString == NULL) return;
    RESOLVE(C2PY.Module_GetDict, "PyModule_GetDict");

    {
        void *p = C2PY_RESOLVE(dl, "PyPyDict_SetItemString");
        if (!p) p = C2PY_RESOLVE(dl, "PyDict_SetItemString");
        C2PY._ds_set_item_string = p;
    }
    C2PY._ds_pypy_workaround = (C2PY._ds_set_item_string != NULL
                                && C2PY.version_major < 3) ? 1 : 0;

    C2PY.CallObject = (PyObject*(*)(PyObject*, PyObject*))
        _resolve_raw("PyObject_CallObject");
    C2PY.Capsule_GetPointer = (void*(*)(PyObject*, const char*))
        _resolve_raw("PyCapsule_GetPointer");
    C2PY.exc_BufferError = (void*)_resolve_raw("PyExc_BufferError");

    RESOLVE_REQ(C2PY.Long_FromVoidPtr, "PyLong_FromVoidPtr");
    if (C2PY.Long_FromVoidPtr == NULL) return;

    RESOLVE_REQ(C2PY.SaveThread, "PyEval_SaveThread");
    RESOLVE_REQ(C2PY.RestoreThread, "PyEval_RestoreThread");
    if (C2PY.SaveThread == NULL || C2PY.RestoreThread == NULL) return;
    RESOLVE(C2PY.Unstable_Module_SetGIL, "PyUnstable_Module_SetGIL");

    {
        void *none = _resolve_raw("_Py_NoneStruct");
        if (none == NULL) {
            void **pnone = (void**)_resolve_raw("Py_None");
            if (pnone) none = *pnone;
        }
        C2PY.none_obj = (PyObject*)none;
        if (C2PY.none_obj == NULL) {
            fprintf(stderr, "c2py_runtime: could not resolve Py_None\n");
            return;
        }
        {
            Py_ssize_t before, after;
            before = *(Py_ssize_t*)((char*)C2PY.none_obj + C2PY.ob_refcnt_offset);
            C2PY.IncRef(C2PY.none_obj);
            after = *(Py_ssize_t*)((char*)C2PY.none_obj + C2PY.ob_refcnt_offset);
            C2PY.none_immortal = (before == after) ? 1 : 0;
            if (!C2PY.none_immortal) {
                C2PY.DecRef(C2PY.none_obj);
            }
        }
    }

    /* Runtime Py_buffer size probe */
    if (!C2PY.is_pypy) {
        unsigned char probe[96];
        Py_buffer *pb = (Py_buffer*)probe;
        typedef PyObject* (*bytes_fn)(const char*, Py_ssize_t);
        bytes_fn mkbytes = (bytes_fn)_resolve_raw("PyBytes_FromStringAndSize");
        if (!mkbytes)
            mkbytes = (bytes_fn)_resolve_raw("PyString_FromStringAndSize");
        PyObject *by = mkbytes ? mkbytes("x", 1) : NULL;
        if (by) {
            memset(probe, 0xAA, sizeof(probe));
            if (C2PY.GetBuffer(by, pb, PyBUF_STRIDES | PyBUF_FORMAT) == 0) {
                {
                    Py_ssize_t internal_off;
#if defined(__LP64__) || defined(_WIN64)
                    internal_off = 72;
#else
                    internal_off = 40;
#endif
                    if (*((char*)pb + internal_off) == 0)
                        C2PY.pybuffer_size = C2PY_PYBUFFER_SZ_POST312;
                    else
                        C2PY.pybuffer_size = C2PY_PYBUFFER_SZ_PRE312;
                }
                C2PY.ReleaseBuffer(pb);
            }
            C2PY.DecRef(by);
        }
    }

    _c2py_init_result = 0;
    _c2py_runtime_initialized = 1;
}
#ifdef _MSC_VER
#pragma warning(pop)
#endif

/* ---- Public init wrapper ---- */

int c2py_runtime_init(void)
{
#ifndef _WIN32
    pthread_once(&_c2py_init_once, _c2py_runtime_init_once);
    return _c2py_init_result;
#else
    if (!_c2py_runtime_initialized) {
        if (!_c2py_init_cs_ready) {
            InitializeCriticalSection(&_c2py_init_cs);
            _c2py_init_cs_ready = TRUE;
        }
        EnterCriticalSection(&_c2py_init_cs);
        if (!_c2py_runtime_initialized) {
            _c2py_runtime_init_once();
        }
        LeaveCriticalSection(&_c2py_init_cs);
    }
    return _c2py_init_result;
#endif
}

#endif /* C2PY_USE_PYTHON_H */

#endif /* C2PY_IMPLEMENTATION */
