"""Merge runtime source files into a single stb-style header c2py.h.

Usage:
    python runtime/merge_single_header.py

Output: runtime/c2py.h  (overwritten if it exists)

The resulting header works in two modes:
  #include "c2py.h"              -> declarations only (include anywhere)
  #define C2PY_IMPLEMENTATION
  #include "c2py.h"              -> + implementation (exactly one TU)

Backend selection (default: dlsym):
  #define C2PY_USE_PYTHON_H      -> before include for --pythonh mode
"""

from __future__ import print_function

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def read(path):
    with open(os.path.join(HERE, path), "r") as f:
        return f.read()


def strip_include_guard(text):
    """Remove #ifndef/#define/#endif include guard from a header."""
    lines = text.split("\n")
    # Find first #ifndef that is the file's own guard
    guard_start = None
    guard_name = None
    for i, line in enumerate(lines):
        m = re.match(r"^#ifndef\s+(\w+)", line)
        if m:
            guard_start = i
            guard_name = m.group(1)
            # Next line should be #define GUARD_NAME
            if i + 1 < len(lines) and re.match(r"^#define\s+" + re.escape(guard_name) + r"\b", lines[i + 1]):
                # Find matching #endif
                depth = 1
                for j in range(i + 2, len(lines)):
                    if re.match(r"^#if", lines[j]):
                        depth += 1
                    elif re.match(r"^#endif", lines[j]):
                        depth -= 1
                        if depth == 0:
                            # Content between #define line and matching #endif
                            content_start = i + 2
                            content_end = j
                            before = lines[:guard_start]
                            content = lines[content_start:content_end]
                            after = lines[content_end + 1 :]
                            return "\n".join(before + content + after)
            break
    return text  # no guard found


def resolve_local_includes(text, processed_files=None):
    """Replace #include "local_file" with file contents (recursive)."""
    if processed_files is None:
        processed_files = set()
    result = []
    for line in text.split("\n"):
        m = re.match(r'^\s*#include\s+"([^"]+)"', line)
        if m:
            inc = m.group(1)
            if inc not in processed_files:
                processed_files.add(inc)
                content = strip_include_guard(read(inc))
                content = resolve_local_includes(content, processed_files)
                result.append(content)
            # else: skip (already inlined)
        else:
            result.append(line)
    return "\n".join(result)


def build_single_header():
    # Read source files
    dlsym_h = read("c2py_dlsym.h")
    pythonh_h = read("c2py_pythonh.h")
    runtime_h = read("c2py_runtime.h")
    runtime_c = read("c2py_runtime.c")
    dlsym_c = read("c2py_dlsym.c")
    pythonh_c = read("c2py_pythonh.c")

    # ---- Strip include guards from backends ----
    dlsym_h_body = strip_include_guard(dlsym_h)
    pythonh_h_body = strip_include_guard(pythonh_h)

    # ---- Build header section ----
    # Strip c2py_runtime.h's own include guard, then replace its
    # backend include gate with the inline backend content.
    runtime_h_body = strip_include_guard(runtime_h)
    runtime_h_lines = runtime_h_body.split("\n")
    # The backend include gate is now at lines 0-7 (the gate was near the
    # top of the original file).  Find it by looking for the comment.
    gate_start = None
    gate_end = None
    for i, line in enumerate(runtime_h_lines):
        if "Pick one backend" in line:
            gate_start = i
        if gate_start is not None and line.strip().startswith("#endif"):
            gate_end = i
            break
    if gate_start is not None and gate_end is not None:
        before_gate = "\n".join(runtime_h_lines[:gate_start])
        after_gate = "\n".join(runtime_h_lines[gate_end + 1 :])
    else:
        before_gate = ""
        after_gate = "\n".join(runtime_h_lines)

    header = []
    header.append("/* c2py.h - Single-header c2py23 runtime")
    header.append(" *")
    header.append(" * Generated by merge_single_header.py -- do not edit by hand.")
    header.append(" * Source files: c2py_runtime.h, c2py_dlsym.h/c, c2py_pythonh.h/c")
    header.append(" *")
    header.append(" * Usage:")
    header.append(' *   #include "c2py.h"              // declarations only')
    header.append(" *   #define C2PY_IMPLEMENTATION")
    header.append(' *   #include "c2py.h"              // + implementation (exactly one TU)')
    header.append(" *")
    header.append(" * Backend selection (default: dlsym):")
    header.append(" *   #define C2PY_USE_PYTHON_H    // before include for --pythonh mode")
    header.append(" */")
    header.append("")
    header.append("#ifndef C2PY_H")
    header.append("#define C2PY_H")
    header.append("")
    header.append("/* ---- Pick one backend ---- */")
    header.append("")
    header.append("#ifdef C2PY_USE_PYTHON_H")
    header.append(pythonh_h_body)
    header.append("#else")
    header.append(dlsym_h_body)
    header.append("#endif")
    header.append("")
    header.append(after_gate)
    header.append("")
    header.append("#endif /* C2PY_H */")

    # ---- Build implementation section ----
    impl = []
    impl.append("")
    impl.append("/* ================================================================ */")
    impl.append("/* Implementation section (only compiled when C2PY_IMPLEMENTATION     */")
    impl.append("/* is defined)                                                       */")
    impl.append("/* ================================================================ */")
    impl.append("")
    impl.append("#ifdef C2PY_IMPLEMENTATION")

    # System includes from c2py_runtime.c (lines 0-38, skipping line 34 = #include "c2py_runtime.h")
    runtime_c_lines = runtime_c.split("\n")
    skip_include_line = None
    for i, line in enumerate(runtime_c_lines):
        if line.strip() == '#include "c2py_runtime.h"':
            skip_include_line = i
            break

    for i, line in enumerate(runtime_c_lines):
        if skip_include_line is not None and i == skip_include_line:
            continue
        if i >= 39:  # past the system includes and C2PY_RESOLVE section
            break
        impl.append(line)

    # Shared globals from c2py_runtime.c lines 40-352
    # Line 40 is the comment "/* ---- Shared globals (visible to both backends) ---- */"
    # Up to line 352 (end of _c2py_probe_cpu_features)
    # We stop before line 354 "/* ---- Backend selection ---- */"
    impl.append("")
    for i, line in enumerate(runtime_c_lines):
        if i < 40:
            continue
        if i >= 354:
            break
        impl.append(line)

    # Backend selection block
    # Pythonh backend
    impl.append("#ifdef C2PY_USE_PYTHON_H")
    impl.append("")
    impl.append(pythonh_c.strip())
    impl.append("")

    # Dlsym backend
    impl.append("#else")
    impl.append("")
    impl.append("/* ---- Nimpy/dlsym backend ---- */")
    impl.append("")
    impl.append("/* Global API table */")
    impl.append("c2py_api_t C2PY = {0};")
    impl.append("")
    impl.append("static volatile int _c2py_runtime_initialized = 0;")
    impl.append("static int _c2py_init_result = 0;")
    impl.append("")
    impl.append("#ifndef _WIN32")
    impl.append("static pthread_once_t _c2py_init_once = PTHREAD_ONCE_INIT;")
    impl.append("#else")
    impl.append("static CRITICAL_SECTION _c2py_init_cs;")
    impl.append("static BOOL _c2py_init_cs_ready = FALSE;")
    impl.append("#endif")
    impl.append("")

    # Inline dlsym.c content
    # Strip any top-level #include lines from dlsym.c (it has none)
    # Also preserve the MSVC pragma wrapping
    dlsym_c_text = dlsym_c
    impl.append(dlsym_c_text.strip())
    impl.append("")

    # Public init wrapper
    impl.append("/* ---- Public init wrapper ---- */")
    impl.append("")
    impl.append("int c2py_runtime_init(void)")
    impl.append("{")
    impl.append("#ifndef _WIN32")
    impl.append("    pthread_once(&_c2py_init_once, _c2py_runtime_init_once);")
    impl.append("    return _c2py_init_result;")
    impl.append("#else")
    impl.append("    if (!_c2py_runtime_initialized) {")
    impl.append("        if (!_c2py_init_cs_ready) {")
    impl.append("            InitializeCriticalSection(&_c2py_init_cs);")
    impl.append("            _c2py_init_cs_ready = TRUE;")
    impl.append("        }")
    impl.append("        EnterCriticalSection(&_c2py_init_cs);")
    impl.append("        if (!_c2py_runtime_initialized) {")
    impl.append("            _c2py_runtime_init_once();")
    impl.append("        }")
    impl.append("        LeaveCriticalSection(&_c2py_init_cs);")
    impl.append("    }")
    impl.append("    return _c2py_init_result;")
    impl.append("#endif")
    impl.append("}")

    impl.append("")
    impl.append("#endif /* C2PY_USE_PYTHON_H */")
    impl.append("")
    impl.append("#endif /* C2PY_IMPLEMENTATION */")

    # Combine
    full = "\n".join(header) + "\n" + "\n".join(impl) + "\n"

    # Write output
    out_path = os.path.join(HERE, "c2py.h")
    with open(out_path, "w") as f:
        f.write(full)
    print("Written: {}".format(out_path))
    n_lines = full.count("\n")
    print("  {} lines".format(n_lines))


if __name__ == "__main__":
    build_single_header()
