/* Generated by c2py23 cast - do not edit by hand */
#include <stdio.h>
#include "c2py_runtime.h"

extern int array_sum(const double * a, const double * b, double * result, int n);

/* Wrapper for: array_sum */

static PyObject* _array_sum_impl(Py_buffer *buf_a, Py_buffer *buf_b, Py_buffer *buf_result)
{
    /* check: a.format == 'd' */
    /* check: b.format == 'd' */
    /* check: result.format == 'd' */
    /* check: a.n == b.n */
    /* check: a.n == result.n */
    /* overload 0 (always) */
    {
        /* array_sum(const double *a, const double *b, double *result, int n) -> int */
        if (((buf_a->len / buf_a->itemsize)) > (Py_ssize_t)INT_MAX)
        {
            PyErr_SetString(PyExc_ValueError, "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        int _ret = array_sum(buf_a->buf, buf_b->buf, buf_result->buf, (buf_a->len / buf_a->itemsize));
        return PyLong_FromLong((long)_ret);
    }

    /* should not reach here */
    return NULL;
}

static PyObject* _array_sum_wrapper(PyObject *self, PyObject *args)
{
    PyObject* py_a = NULL;
    PyObject* py_b = NULL;
    PyObject* py_result = NULL;
    PyObject* ret = NULL;
    Py_buffer buf_a;
    int acq_a = 0;
    Py_buffer buf_b;
    int acq_b = 0;
    Py_buffer buf_result;
    int acq_result = 0;

    if (!PyArg_ParseTuple(args, "OOO", &py_a, &py_b, &py_result))
    {
        return NULL;
    }
    memset(&buf_a, 0, C2PY.pybuffer_size);
    memset(&buf_b, 0, C2PY.pybuffer_size);
    memset(&buf_result, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_a, &buf_a, C2PY_BUF_READ) == -1)
    return NULL;
    acq_a = 1;

    if (c2py_acquire_buffer(py_b, &buf_b, C2PY_BUF_READ) == -1)
    goto cleanup;
    acq_b = 1;

    if (c2py_acquire_buffer(py_result, &buf_result, C2PY_BUF_WRITE) == -1)
    goto cleanup;
    acq_result = 1;
    /* restrict check: result vs a */
    if (buf_result.buf >= buf_a.buf && 
    buf_result.buf < buf_a.buf + buf_a.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    if (buf_a.buf >= buf_result.buf && 
    buf_a.buf < buf_result.buf + buf_result.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    
    /* restrict check: result vs b */
    if (buf_result.buf >= buf_b.buf && 
    buf_result.buf < buf_b.buf + buf_b.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    if (buf_b.buf >= buf_result.buf && 
    buf_b.buf < buf_result.buf + buf_result.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    
    /* contiguity check: a */
    do {
    int _ok = 1;
    if (buf_a.strides == NULL && buf_a.ndim <= 1) break;
    if (buf_a.ndim >= 1) {
    Py_ssize_t _expected = buf_a.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_a.ndim; _d++) {
    if (buf_a.strides[_d] < 0) { _ok = 0; break; }
    if (buf_a.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_a.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_a.itemsize;
    for (_d = buf_a.ndim - 1; _d >= 0; _d--) {
    if (buf_a.strides[_d] < 0) { _ok = 0; break; }
    if (buf_a.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_a.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    
    /* contiguity check: b */
    do {
    int _ok = 1;
    if (buf_b.strides == NULL && buf_b.ndim <= 1) break;
    if (buf_b.ndim >= 1) {
    Py_ssize_t _expected = buf_b.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_b.ndim; _d++) {
    if (buf_b.strides[_d] < 0) { _ok = 0; break; }
    if (buf_b.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_b.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_b.itemsize;
    for (_d = buf_b.ndim - 1; _d >= 0; _d--) {
    if (buf_b.strides[_d] < 0) { _ok = 0; break; }
    if (buf_b.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_b.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    
    /* contiguity check: result */
    do {
    int _ok = 1;
    if (buf_result.strides == NULL && buf_result.ndim <= 1) break;
    if (buf_result.ndim >= 1) {
    Py_ssize_t _expected = buf_result.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_result.ndim; _d++) {
    if (buf_result.strides[_d] < 0) { _ok = 0; break; }
    if (buf_result.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_result.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_result.itemsize;
    for (_d = buf_result.ndim - 1; _d >= 0; _d--) {
    if (buf_result.strides[_d] < 0) { _ok = 0; break; }
    if (buf_result.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_result.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    

    ret = _array_sum_impl(&buf_a, &buf_b, &buf_result);
    cleanup:
    if (acq_result) c2py_release_buffer(&buf_result);
    if (acq_b) c2py_release_buffer(&buf_b);
    if (acq_a) c2py_release_buffer(&buf_a);
    return ret;
}
static PyObject* _array_sum_wrapper_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject* py_a = NULL;
    PyObject* py_b = NULL;
    PyObject* py_result = NULL;
    PyObject* ret = NULL;
    Py_buffer buf_a;
    int acq_a = 0;
    Py_buffer buf_b;
    int acq_b = 0;
    Py_buffer buf_result;
    int acq_result = 0;

    if (nargs != 3)
    {
        PyErr_SetString(PyExc_TypeError, "array_sum expects 3 arguments");
        return NULL;
    }
    py_a = args[0];
    py_b = args[1];
    py_result = args[2];

    memset(&buf_a, 0, C2PY.pybuffer_size);
    memset(&buf_b, 0, C2PY.pybuffer_size);
    memset(&buf_result, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_a, &buf_a, C2PY_BUF_READ) == -1)
    return NULL;
    acq_a = 1;

    if (c2py_acquire_buffer(py_b, &buf_b, C2PY_BUF_READ) == -1)
    goto cleanup;
    acq_b = 1;

    if (c2py_acquire_buffer(py_result, &buf_result, C2PY_BUF_WRITE) == -1)
    goto cleanup;
    acq_result = 1;
    /* restrict check: result vs a */
    if (buf_result.buf >= buf_a.buf && 
    buf_result.buf < buf_a.buf + buf_a.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    if (buf_a.buf >= buf_result.buf && 
    buf_a.buf < buf_result.buf + buf_result.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    
    /* restrict check: result vs b */
    if (buf_result.buf >= buf_b.buf && 
    buf_result.buf < buf_b.buf + buf_b.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    if (buf_b.buf >= buf_result.buf && 
    buf_b.buf < buf_result.buf + buf_result.len) {
    PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
    goto cleanup;
    }
    
    /* contiguity check: a */
    do {
    int _ok = 1;
    if (buf_a.strides == NULL && buf_a.ndim <= 1) break;
    if (buf_a.ndim >= 1) {
    Py_ssize_t _expected = buf_a.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_a.ndim; _d++) {
    if (buf_a.strides[_d] < 0) { _ok = 0; break; }
    if (buf_a.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_a.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_a.itemsize;
    for (_d = buf_a.ndim - 1; _d >= 0; _d--) {
    if (buf_a.strides[_d] < 0) { _ok = 0; break; }
    if (buf_a.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_a.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    
    /* contiguity check: b */
    do {
    int _ok = 1;
    if (buf_b.strides == NULL && buf_b.ndim <= 1) break;
    if (buf_b.ndim >= 1) {
    Py_ssize_t _expected = buf_b.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_b.ndim; _d++) {
    if (buf_b.strides[_d] < 0) { _ok = 0; break; }
    if (buf_b.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_b.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_b.itemsize;
    for (_d = buf_b.ndim - 1; _d >= 0; _d--) {
    if (buf_b.strides[_d] < 0) { _ok = 0; break; }
    if (buf_b.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_b.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    
    /* contiguity check: result */
    do {
    int _ok = 1;
    if (buf_result.strides == NULL && buf_result.ndim <= 1) break;
    if (buf_result.ndim >= 1) {
    Py_ssize_t _expected = buf_result.itemsize;
    int _d;
    /* check F-contiguous (column-major): first dim varies fastest */
    for (_d = 0; _d < buf_result.ndim; _d++) {
    if (buf_result.strides[_d] < 0) { _ok = 0; break; }
    if (buf_result.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_result.shape[_d];
    }
    if (_ok) break;
    /* check C-contiguous (row-major): last dim varies fastest */
    _ok = 1;
    _expected = buf_result.itemsize;
    for (_d = buf_result.ndim - 1; _d >= 0; _d--) {
    if (buf_result.strides[_d] < 0) { _ok = 0; break; }
    if (buf_result.strides[_d] != _expected) { _ok = 0; break; }
    _expected *= buf_result.shape[_d];
    }
    }
    if (!_ok) {
    PyErr_SetString(PyExc_ValueError,
    "buffer not contiguous (C or Fortran contiguous required)");
    goto cleanup;
    }
    } while(0);
    

    ret = _array_sum_impl(&buf_a, &buf_b, &buf_result);
    cleanup:
    if (acq_result) c2py_release_buffer(&buf_result);
    if (acq_b) c2py_release_buffer(&buf_b);
    if (acq_a) c2py_release_buffer(&buf_a);
    return ret;
}

/* Module definition */

static PyMethodDef _methods_varargs[] = {
    {"array_sum", (PyCFunction)_array_sum_wrapper, METH_VARARGS, "array_sum(a, b, result)\n--\n\narray_sum(a: buffer, b: buffer, result: buffer) -> int\n\nParameters\n----------\na : buffer\n    Type: float64 (format 'd')\n    Size must equal b\n    Size must equal result\nb : buffer\n    Type: float64 (format 'd')\nresult : buffer\n    Type: float64 (format 'd')\n    Writable\n\nChecks\n------\n  a.format == 'd'  [ValueError]\n  b.format == 'd'  [ValueError]\n  result.format == 'd'  [ValueError]\n  a.n == b.n  [ValueError]\n  a.n == result.n  [ValueError]\n\nOverloads\n---------\n  array_sum(const double *a, const double *b, double *result, int n) -> int\n    Map: a = a.ptr (const double *)\n         b = b.ptr (const double *)\n         result = result.ptr (double *)\n         n = a.n (int)"},
    {NULL, NULL, 0, NULL}
};

static PyMethodDef _methods_fastcall[] = {
    {"array_sum", (PyCFunction)_array_sum_wrapper_fastcall, METH_FASTCALL, "array_sum(a, b, result)\n--\n\narray_sum(a: buffer, b: buffer, result: buffer) -> int\n\nParameters\n----------\na : buffer\n    Type: float64 (format 'd')\n    Size must equal b\n    Size must equal result\nb : buffer\n    Type: float64 (format 'd')\nresult : buffer\n    Type: float64 (format 'd')\n    Writable\n\nChecks\n------\n  a.format == 'd'  [ValueError]\n  b.format == 'd'  [ValueError]\n  result.format == 'd'  [ValueError]\n  a.n == b.n  [ValueError]\n  a.n == result.n  [ValueError]\n\nOverloads\n---------\n  array_sum(const double *a, const double *b, double *result, int n) -> int\n    Map: a = a.ptr (const double *)\n         b = b.ptr (const double *)\n         result = result.ptr (double *)\n         n = a.n (int)"},
    {NULL, NULL, 0, NULL}
};

static PyModuleDef _module_def = {
    PyModuleDef_HEAD_INIT,
    "arraysum",
    "Module: arraysum\nSource: ['arraysum.c']\nTiming: no\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

static PyModuleDef_FT _module_def_ft = {
    PyModuleDef_HEAD_INIT_FT,
    "arraysum",
    "Module: arraysum\nSource: ['arraysum.c']\nTiming: no\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

PyObject* PyInit_arraysum(void)
{
    c2py_runtime_init();

    PyObject* module = NULL;
    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;

    if (C2PY.is_free_threaded)
    {
        _module_def_ft.m_methods = methods;
        if (C2PY.Module_Create2 != NULL)
        {
            module = C2PY.Module_Create2((PyModuleDef*)&_module_def_ft, 3);
        }
    }
    else
    {
        _module_def.m_methods = methods;
        if (C2PY.Module_Create2 != NULL)
        {
            module = C2PY.Module_Create2(&_module_def, 3);
        }
        else
        {
            module = C2PY.InitModule_2_7("arraysum", methods);
        }
    }

    if (module != NULL)
    {}
    return module;
}

void initarraysum(void)
{
    c2py_runtime_init();
    PyObject *module = C2PY.InitModule_2_7("arraysum", C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);
    if (module != NULL)
    {}
}
