/* Generated by c2py23 - do not edit by hand */
#include <stdio.h>
#include "c2py_runtime.h"

extern void transform_aos(double * points, intptr_t n, double * out);
extern void transform_soa(double * points, intptr_t n, double * out);

/* -------------------------------------------- */
/* Wrapper for: transform */
/* -------------------------------------------- */

static PyObject*
_transform_impl(Py_buffer *buf_points, Py_buffer *buf_out)
{
    int _c2py_slow_axis_buf_points = -1;
    int _c2py_fast_axis_buf_points = -1;
    (void)_c2py_slow_axis_buf_points;
    (void)_c2py_fast_axis_buf_points;
    /* contiguity check: points */
    do {
        int _ok = 1;
        if (buf_points->strides == NULL && buf_points->ndim <= 1) break;
        if (buf_points->ndim >= 1) {
            Py_ssize_t _expected = buf_points->itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_points->ndim; _d++) {
                if (buf_points->strides[_d] < 0) { _ok = 0; break; }
                if (buf_points->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_points->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_points = (int)(buf_points->ndim - 1); _c2py_fast_axis_buf_points = 0; break; }
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_points->itemsize;
            for (_d = buf_points->ndim - 1; _d >= 0; _d--) {
                if (buf_points->strides[_d] < 0) { _ok = 0; break; }
                if (buf_points->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_points->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_points = 0; _c2py_fast_axis_buf_points = (int)(buf_points->ndim - 1); }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            return NULL;
        }
    } while(0);

    int _c2py_slow_axis_buf_out = -1;
    int _c2py_fast_axis_buf_out = -1;
    (void)_c2py_slow_axis_buf_out;
    (void)_c2py_fast_axis_buf_out;
    /* contiguity check: out */
    do {
        int _ok = 1;
        if (buf_out->strides == NULL && buf_out->ndim <= 1) break;
        if (buf_out->ndim >= 1) {
            Py_ssize_t _expected = buf_out->itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_out->ndim; _d++) {
                if (buf_out->strides[_d] < 0) { _ok = 0; break; }
                if (buf_out->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_out->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_out = (int)(buf_out->ndim - 1); _c2py_fast_axis_buf_out = 0; break; }
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_out->itemsize;
            for (_d = buf_out->ndim - 1; _d >= 0; _d--) {
                if (buf_out->strides[_d] < 0) { _ok = 0; break; }
                if (buf_out->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_out->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_out = 0; _c2py_fast_axis_buf_out = (int)(buf_out->ndim - 1); }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            return NULL;
        }
    } while(0);

    /* check: points.format == 'd' */
    if (!((!buf_points->format || buf_points->format[strlen(buf_points->format) - 1] == 'd'))) {
        char _c2py_err[256];
        const char *_fmt = buf_points->format ? buf_points->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.format == 'd' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: out.format == 'd' */
    if (!((!buf_out->format || buf_out->format[strlen(buf_out->format) - 1] == 'd'))) {
        char _c2py_err[256];
        const char *_fmt = buf_out->format ? buf_out->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: out.format == 'd' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: out.n == points.n */
    if (!(((buf_out->len / buf_out->itemsize)) == ((buf_points->len / buf_points->itemsize)))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: out.n == points.n (got %ld vs %ld)", (long)((buf_out->len / buf_out->itemsize)), (long)((buf_points->len / buf_points->itemsize)));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: points.ndim == 2 */
    if (!((buf_points->ndim) == (2))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.ndim == 2 (got %ld vs %ld)", (long)(buf_points->ndim), (long)(2));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: points.slow_axis == 0 */
    if (!((_c2py_slow_axis_buf_points) == (0))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.slow_axis == 0 (got %ld vs %ld)", (long)(_c2py_slow_axis_buf_points), (long)(0));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    if ((buf_points->shape[1]) == (3)) {
        /* transform_aos(double *points, intptr_t n, double *out) */
        transform_aos((double *)buf_points->buf, (intptr_t)(buf_points->shape[0]), (double *)buf_out->buf);
        Py_RETURN_NONE;
    } else if ((buf_points->shape[0]) == (3)) {
        /* transform_soa(double *points, intptr_t n, double *out) */
        transform_soa((double *)buf_points->buf, (intptr_t)(buf_points->shape[1]), (double *)buf_out->buf);
        Py_RETURN_NONE;
    } else {
        PyErr_SetString(PyExc_ValueError, "expected [N,3] or [3,N] buffer");
        return NULL;
    }

#ifdef _MSC_VER
__pragma(warning(push))
__pragma(warning(disable:4702)) /* unreachable code */
#endif
    return NULL;
#ifdef _MSC_VER
__pragma(warning(pop))
#endif
}

static PyObject*
_transform_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_points = NULL;
    PyObject *py_out = NULL;
    Py_buffer buf_points;
    int acq_points = 0;
    Py_buffer buf_out;
    int acq_out = 0;
    PyObject *ret = NULL;

    if (!PyArg_ParseTuple(args, "OO", &py_points, &py_out))
        return NULL;

    memset(&buf_points, 0, C2PY.pybuffer_size);
    memset(&buf_out, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_points, &buf_points, C2PY_BUF_WRITE) == -1)
        return NULL;
    acq_points = 1;

    if (c2py_acquire_buffer(py_out, &buf_out, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_out = 1;

    /* restrict check: points vs out */
    if ((char*)buf_points.buf >= (char*)buf_out.buf && 
        (char*)buf_points.buf < (char*)buf_out.buf + buf_out.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if ((char*)buf_out.buf >= (char*)buf_points.buf && 
        (char*)buf_out.buf < (char*)buf_points.buf + buf_points.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    ret = _transform_impl(&buf_points, &buf_out);

cleanup:
    if (acq_out) c2py_release_buffer(&buf_out);
    if (acq_points) c2py_release_buffer(&buf_points);
    return ret;
}

static PyObject*
_transform_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_points = NULL;
    PyObject *py_out = NULL;
    Py_buffer buf_points;
    int acq_points = 0;
    Py_buffer buf_out;
    int acq_out = 0;
    PyObject *ret = NULL;

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "transform expects 2 arguments");
        return NULL;
    }

    py_points = args[0];
    py_out = args[1];

    memset(&buf_points, 0, C2PY.pybuffer_size);
    memset(&buf_out, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_points, &buf_points, C2PY_BUF_WRITE) == -1)
        return NULL;
    acq_points = 1;

    if (c2py_acquire_buffer(py_out, &buf_out, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_out = 1;

    /* restrict check: points vs out */
    if ((char*)buf_points.buf >= (char*)buf_out.buf && 
        (char*)buf_points.buf < (char*)buf_out.buf + buf_out.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if ((char*)buf_out.buf >= (char*)buf_points.buf && 
        (char*)buf_out.buf < (char*)buf_points.buf + buf_points.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    ret = _transform_impl(&buf_points, &buf_out);

cleanup:
    if (acq_out) c2py_release_buffer(&buf_out);
    if (acq_points) c2py_release_buffer(&buf_points);
    return ret;
}


/* -------------------------------------------- */
/* Module definition                          */
/* -------------------------------------------- */

static PyMethodDef _methods_varargs[] = {
    {"transform", (PyCFunction)_transform_wrapper, METH_VARARGS, "transform(points, out)\n--\n\ntransform(points: buffer, out: buffer) -> void\n\nParameters\n----------\npoints : buffer\n    Type: float64 (format 'd')\n    Writable\n    Shape: 2D\nout : buffer\n    Type: float64 (format 'd')\n    Writable\n    Size must equal points\n\nChecks\n------\n  points.format == 'd'  [ValueError]\n  out.format == 'd'  [ValueError]\n  out.n == points.n  [ValueError]\n  points.ndim == 2  [ValueError]\n  points.slow_axis == 0  [ValueError]\n\nOverloads\n---------\n  transform_aos(double *points, intptr_t n, double *out) (When: points.shape[1] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[0] (intptr_t)\n         out = out.ptr (double *)\n  transform_soa(double *points, intptr_t n, double *out) (When: points.shape[0] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[1] (intptr_t)\n         out = out.ptr (double *)\n\nValueError: expected [N,3] or [3,N] buffer"},
    {NULL, NULL, 0, NULL}
};

static PyMethodDef _methods_fastcall[] = {
    {"transform", (PyCFunction)_transform_fastcall, METH_FASTCALL, "transform(points, out)\n--\n\ntransform(points: buffer, out: buffer) -> void\n\nParameters\n----------\npoints : buffer\n    Type: float64 (format 'd')\n    Writable\n    Shape: 2D\nout : buffer\n    Type: float64 (format 'd')\n    Writable\n    Size must equal points\n\nChecks\n------\n  points.format == 'd'  [ValueError]\n  out.format == 'd'  [ValueError]\n  out.n == points.n  [ValueError]\n  points.ndim == 2  [ValueError]\n  points.slow_axis == 0  [ValueError]\n\nOverloads\n---------\n  transform_aos(double *points, intptr_t n, double *out) (When: points.shape[1] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[0] (intptr_t)\n         out = out.ptr (double *)\n  transform_soa(double *points, intptr_t n, double *out) (When: points.shape[0] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[1] (intptr_t)\n         out = out.ptr (double *)\n\nValueError: expected [N,3] or [3,N] buffer"},
    {NULL, NULL, 0, NULL}
};

static PyModuleDef _module_def = {
    PyModuleDef_HEAD_INIT,
    "xfrm",
    "Module: xfrm\nSource: ['transform.c']\nTiming: no\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

static PyModuleDef_FT _module_def_ft = {
    PyModuleDef_HEAD_INIT_FT,
    "xfrm",
    "Module: xfrm\nSource: ['transform.c']\nTiming: no\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL,  /* m_slots = NULL (single-phase init; PyUnstable_Module_SetGIL handles FT) */
    NULL, NULL, NULL
};

C2PY_EXPORT PyObject* PyInit_xfrm(void) {
    c2py_runtime_init();

    PyObject *module = NULL;
    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;

    if (C2PY.is_free_threaded) {
        _module_def_ft.m_methods = methods;
        if (C2PY.Module_Create2 != NULL) {
            module = C2PY.Module_Create2((PyModuleDef*)&_module_def_ft, 3);
        }
    } else {
        _module_def.m_methods = methods;
        if (C2PY.Module_Create2 != NULL) {
            module = C2PY.Module_Create2(&_module_def, 3);
        } else {
            module = C2PY.InitModule_2_7("xfrm", methods);
        }
    }

    if (module != NULL) {
    }
    return module;
}

C2PY_EXPORT void initxfrm(void) {
    c2py_runtime_init();

    PyObject *module = C2PY.InitModule_2_7("xfrm",
        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);
    if (module != NULL) {
    }
}
