/* Generated by c2py23 - do not edit by hand */
#include <stdio.h>
#include "c2py_runtime.h"

extern void transform_aos(double * points, intptr_t n, double * out);
extern void transform_soa(double * points, intptr_t n, double * out);

/* ---- Performance timing ---- */
static int _c2py_timing_enabled = 1;

static c2py_perf_t _perf_transform;
static c2py_perf_t _perf_transform__transform_aos;
static c2py_perf_t _perf_transform__transform_soa;

/* Python-callable: return tick source frequency in Hz */
static PyObject*
__c2py_tick_frequency(PyObject *self, PyObject *args) {
    (void)self;
    if (!PyArg_ParseTuple(args, ""))
        return NULL;
    return PyLong_FromUnsignedLongLong(c2py_tick_frequency());
}

/* Python-callable: convert ticks to nanoseconds at given frequency */
static PyObject*
__c2py_ticks_to_ns(PyObject *self, PyObject *args) {
    unsigned long long ticks, freq_hz;
    (void)self;
    if (!PyArg_ParseTuple(args, "KK", &ticks, &freq_hz))
        return NULL;
    return PyLong_FromUnsignedLongLong(
        c2py_ticks_to_ns((uint64_t)ticks, (uint64_t)freq_hz));
}

/* Python-callable: select tick source ("clock" or "cycle").
 * Returns (old_freq_hz, new_freq_hz) tuple. */
static PyObject*
__c2py_set_tick_source(PyObject *self, PyObject *args) {
    const char *source = NULL;
    (void)self;
    if (!PyArg_ParseTuple(args, "s", &source))
        return NULL;

    uint64_t old_freq = c2py_tick_frequency_hz;
    uint64_t new_freq;
    int new_mode;

    if (source != NULL && strcmp(source, "cycle") == 0) {
        new_mode = 1;
        new_freq = c2py_cycle_counter_frequency_hz;
        if (new_freq == 0) {
            PyErr_SetString(PyExc_RuntimeError,
                "cycle counter frequency not detected on this platform");
            return NULL;
        }
    } else {
        new_mode = 0;
        new_freq = 1000000000ULL;
    }

    _c2py_use_cycle_counter = new_mode;
    c2py_tick_frequency_hz = new_freq;

    PyObject *tup = PyTuple_New(2);
    if (tup == NULL) return NULL;
    PyTuple_SetItem(tup, 0, PyLong_FromUnsignedLongLong(old_freq));
    PyTuple_SetItem(tup, 1, PyLong_FromUnsignedLongLong(new_freq));
    return tup;
}

/* ---- Perf accessor functions (no ctypes needed) ---- */

/* Fill a uint64 array with perf fields from the given pointer. */
static PyObject*
_c2py_perf_read(PyObject *self, PyObject *args) {
    unsigned long long ptr_val;
    Py_buffer buf;
    (void)self;
    if (!PyArg_ParseTuple(args, "Kw*", &ptr_val, &buf))
        return NULL;
    if (buf.len < (Py_ssize_t)(11 * sizeof(uint64_t))) {
        PyErr_SetString(PyExc_ValueError,
            "buffer too small for perf data (need 11 uint64)");
        return NULL;
    }
    c2py_perf_extract_u64((c2py_perf_t*)(uintptr_t)ptr_val,
                           (uint64_t*)buf.buf);
    PyBuffer_Release(&buf);
    Py_RETURN_NONE;
}

/* Return (variant, group_idx, variant_name) metadata tuple. */
static PyObject*
_c2py_perf_meta(PyObject *self, PyObject *args) {
    unsigned long long ptr_val;
    c2py_perf_t *p;
    PyObject *tuple;
    const char *vn;
    (void)self;
    if (!PyArg_ParseTuple(args, "K", &ptr_val))
        return NULL;
    p = (c2py_perf_t*)(uintptr_t)ptr_val;
    tuple = PyTuple_New(3);
    if (!tuple) return NULL;
    PyTuple_SetItem(tuple, 0, PyLong_FromLong((long)p->variant));
    PyTuple_SetItem(tuple, 1, PyLong_FromLong((long)p->group_idx));
    vn = p->variant_name;
    if (!vn) vn = "";
    if (C2PY.version_major >= 3) {
        PyTuple_SetItem(tuple, 2, C2PY.Unicode_FromString(vn));
    } else {
        PyTuple_SetItem(tuple, 2, C2PY.String_FromString(vn));
    }
    return tuple;
}

/* Reset a perf counter to initial state. */
static PyObject*
_c2py_perf_reset(PyObject *self, PyObject *args) {
    unsigned long long ptr_val;
    (void)self;
    if (!PyArg_ParseTuple(args, "K", &ptr_val))
        return NULL;
    c2py_perf_reset((c2py_perf_t*)(uintptr_t)ptr_val);
    Py_RETURN_NONE;
}

/* Read timing enabled flag (0 or 1). */
static PyObject*
_c2py_perf_get_enabled(PyObject *self, PyObject *args) {
    (void)self;
    if (!PyArg_ParseTuple(args, ""))
        return NULL;
    return PyLong_FromLong((long)_c2py_timing_enabled);
}

/* Set timing enabled flag. */
static PyObject*
_c2py_perf_set_enabled(PyObject *self, PyObject *args) {
    int val;
    (void)self;
    if (!PyArg_ParseTuple(args, "i", &val))
        return NULL;
    _c2py_timing_enabled = val;
    Py_RETURN_NONE;
}

/* -------------------------------------------- */
/* Wrapper for: transform */
/* -------------------------------------------- */

static PyObject*
_transform_impl(Py_buffer *buf_points, Py_buffer *buf_out)
{
    int _c2py_slow_axis_buf_points = -1;
    int _c2py_fast_axis_buf_points = -1;
    (void)_c2py_slow_axis_buf_points;
    (void)_c2py_fast_axis_buf_points;
    /* contiguity check: points */
    do {
        int _ok = 1;
        if (buf_points->strides == NULL && buf_points->ndim <= 1) {
            _c2py_slow_axis_buf_points = 0;
            _c2py_fast_axis_buf_points = (int)(buf_points->ndim - 1);
            break;
        }
        if (buf_points->ndim >= 1) {
            Py_ssize_t _expected = buf_points->itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_points->ndim; _d++) {
                if (buf_points->strides[_d] < 0) { _ok = 0; break; }
                if (buf_points->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_points->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_points = (int)(buf_points->ndim - 1); _c2py_fast_axis_buf_points = 0; break; }
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_points->itemsize;
            for (_d = buf_points->ndim - 1; _d >= 0; _d--) {
                if (buf_points->strides[_d] < 0) { _ok = 0; break; }
                if (buf_points->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_points->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_points = 0; _c2py_fast_axis_buf_points = (int)(buf_points->ndim - 1); }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            return NULL;
        }
    } while(0);

    int _c2py_slow_axis_buf_out = -1;
    int _c2py_fast_axis_buf_out = -1;
    (void)_c2py_slow_axis_buf_out;
    (void)_c2py_fast_axis_buf_out;
    /* contiguity check: out */
    do {
        int _ok = 1;
        if (buf_out->strides == NULL && buf_out->ndim <= 1) {
            _c2py_slow_axis_buf_out = 0;
            _c2py_fast_axis_buf_out = (int)(buf_out->ndim - 1);
            break;
        }
        if (buf_out->ndim >= 1) {
            Py_ssize_t _expected = buf_out->itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_out->ndim; _d++) {
                if (buf_out->strides[_d] < 0) { _ok = 0; break; }
                if (buf_out->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_out->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_out = (int)(buf_out->ndim - 1); _c2py_fast_axis_buf_out = 0; break; }
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_out->itemsize;
            for (_d = buf_out->ndim - 1; _d >= 0; _d--) {
                if (buf_out->strides[_d] < 0) { _ok = 0; break; }
                if (buf_out->strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_out->shape[_d];
            }
            if (_ok) { _c2py_slow_axis_buf_out = 0; _c2py_fast_axis_buf_out = (int)(buf_out->ndim - 1); }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            return NULL;
        }
    } while(0);

    int _c2py_do_time = _c2py_timing_enabled;
    uint64_t _c2py_ct0 = 0, _c2py_ct1 = 0;

    /* check: points.format == 'd' */
    if (!((!buf_points->format || buf_points->format[strlen(buf_points->format) - 1] == 'd'))) {
        char _c2py_err[256];
        const char *_fmt = buf_points->format ? buf_points->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.format == 'd' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: out.format == 'd' */
    if (!((!buf_out->format || buf_out->format[strlen(buf_out->format) - 1] == 'd'))) {
        char _c2py_err[256];
        const char *_fmt = buf_out->format ? buf_out->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: out.format == 'd' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: out.n == points.n */
    if (!(((buf_out->len / buf_out->itemsize)) == ((buf_points->len / buf_points->itemsize)))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: out.n == points.n (got %ld vs %ld)", (long)((buf_out->len / buf_out->itemsize)), (long)((buf_points->len / buf_points->itemsize)));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: points.ndim == 2 */
    if (!((buf_points->ndim) == (2))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.ndim == 2 (got %ld vs %ld)", (long)(buf_points->ndim), (long)(2));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: points.slow_axis == 0 */
    if (!((_c2py_slow_axis_buf_points) == (0))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: points.slow_axis == 0 (got %ld). Buffer must be C-contiguous (use slow_axis=0 or [][] notation).", (long)(_c2py_slow_axis_buf_points));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    if ((buf_points->shape[1]) == (3)) {
        /* transform_aos(double *points, intptr_t n, double *out) */
        if (_c2py_do_time) _c2py_ct0 = c2py_ticks();
        transform_aos((double *)buf_points->buf, (intptr_t)(buf_points->shape[0]), (double *)buf_out->buf);
        if (_c2py_do_time) {
            _c2py_ct1 = c2py_ticks();
            c2py_perf_record_call(&_perf_transform__transform_aos, _c2py_ct0, _c2py_ct1);
        }
        Py_RETURN_NONE;
    } else if ((buf_points->shape[0]) == (3)) {
        /* transform_soa(double *points, intptr_t n, double *out) */
        if (_c2py_do_time) _c2py_ct0 = c2py_ticks();
        transform_soa((double *)buf_points->buf, (intptr_t)(buf_points->shape[1]), (double *)buf_out->buf);
        if (_c2py_do_time) {
            _c2py_ct1 = c2py_ticks();
            c2py_perf_record_call(&_perf_transform__transform_soa, _c2py_ct0, _c2py_ct1);
        }
        Py_RETURN_NONE;
    } else {
        PyErr_SetString(PyExc_ValueError, "expected [N,3] or [3,N] buffer");
        return NULL;
    }

#ifdef _MSC_VER
__pragma(warning(push))
__pragma(warning(disable:4702)) /* unreachable code */
#endif
    return NULL;
#ifdef _MSC_VER
__pragma(warning(pop))
#endif
}

static PyObject*
_transform_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_points = NULL;
    PyObject *py_out = NULL;
    Py_buffer buf_points;
    int acq_points = 0;
    Py_buffer buf_out;
    int acq_out = 0;
    PyObject *ret = NULL;
    int _c2py_do_time = _c2py_timing_enabled;
    uint64_t _c2py_t0 = 0, _c2py_t1 = 0, _c2py_t2 = 0;
    if (_c2py_do_time) _c2py_t0 = c2py_ticks();

    if (!PyArg_ParseTuple(args, "OO", &py_points, &py_out))
        return NULL;

    memset(&buf_points, 0, C2PY.pybuffer_size);
    memset(&buf_out, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_points, &buf_points, C2PY_BUF_WRITE) == -1)
        return NULL;
    acq_points = 1;

    if (c2py_acquire_buffer(py_out, &buf_out, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_out = 1;

    /* restrict check: out vs points */
    if ((char*)buf_out.buf >= (char*)buf_points.buf && 
        (char*)buf_out.buf < (char*)buf_points.buf + buf_points.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if ((char*)buf_points.buf >= (char*)buf_out.buf && 
        (char*)buf_points.buf < (char*)buf_out.buf + buf_out.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    if (_c2py_do_time) _c2py_t1 = c2py_ticks();
    ret = _transform_impl(&buf_points, &buf_out);
    if (_c2py_do_time) _c2py_t2 = c2py_ticks();

cleanup:
    if (acq_out) c2py_release_buffer(&buf_out);
    if (acq_points) c2py_release_buffer(&buf_points);

    if (_c2py_do_time) {
        c2py_perf_record(&_perf_transform, _c2py_t0, _c2py_t1, _c2py_t2, c2py_ticks());
    }
    return ret;
}

static PyObject*
_transform_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_points = NULL;
    PyObject *py_out = NULL;
    Py_buffer buf_points;
    int acq_points = 0;
    Py_buffer buf_out;
    int acq_out = 0;
    PyObject *ret = NULL;
    int _c2py_do_time = _c2py_timing_enabled;
    uint64_t _c2py_t0 = 0, _c2py_t1 = 0, _c2py_t2 = 0;
    if (_c2py_do_time) _c2py_t0 = c2py_ticks();

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "transform expects 2 arguments");
        return NULL;
    }

    py_points = args[0];
    py_out = args[1];

    memset(&buf_points, 0, C2PY.pybuffer_size);
    memset(&buf_out, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_points, &buf_points, C2PY_BUF_WRITE) == -1)
        return NULL;
    acq_points = 1;

    if (c2py_acquire_buffer(py_out, &buf_out, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_out = 1;

    /* restrict check: out vs points */
    if ((char*)buf_out.buf >= (char*)buf_points.buf && 
        (char*)buf_out.buf < (char*)buf_points.buf + buf_points.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if ((char*)buf_points.buf >= (char*)buf_out.buf && 
        (char*)buf_points.buf < (char*)buf_out.buf + buf_out.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    if (_c2py_do_time) _c2py_t1 = c2py_ticks();
    ret = _transform_impl(&buf_points, &buf_out);
    if (_c2py_do_time) _c2py_t2 = c2py_ticks();

cleanup:
    if (acq_out) c2py_release_buffer(&buf_out);
    if (acq_points) c2py_release_buffer(&buf_points);

    if (_c2py_do_time) {
        c2py_perf_record(&_perf_transform, _c2py_t0, _c2py_t1, _c2py_t2, c2py_ticks());
    }
    return ret;
}


/* -------------------------------------------- */
/* Module definition                          */
/* -------------------------------------------- */

static PyMethodDef _methods_varargs[] = {
    {"transform", (PyCFunction)_transform_wrapper, METH_VARARGS, "transform(points, out)\n--\n\ntransform(points: buffer, out: buffer) -> void\n\nParameters\n----------\npoints : buffer\n    Type: float64 (format 'd')\n    Writable\n    Shape: 2D\nout : buffer\n    Type: float64 (format 'd')\n    Writable\n    Size must equal points\n\nChecks\n------\n  points.format == 'd'  [ValueError]\n  out.format == 'd'  [ValueError]\n  out.n == points.n  [ValueError]\n  points.ndim == 2  [ValueError]\n  points.slow_axis == 0  [ValueError]\n\nOverloads\n---------\n  transform_aos(double *points, intptr_t n, double *out) (When: points.shape[1] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[0] (intptr_t)\n         out = out.ptr (double *)\n  transform_soa(double *points, intptr_t n, double *out) (When: points.shape[0] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[1] (intptr_t)\n         out = out.ptr (double *)\n\nValueError: expected [N,3] or [3,N] buffer"},
    {"_c2py_tick_frequency", (PyCFunction)__c2py_tick_frequency, METH_VARARGS,
     "return tick source frequency in Hz"},
    {"_c2py_ticks_to_ns", (PyCFunction)__c2py_ticks_to_ns, METH_VARARGS,
     "convert (ticks, freq_hz) to nanoseconds"},
    {"_c2py_perf_read", (PyCFunction)_c2py_perf_read, METH_VARARGS,
     "read perf data into uint64 buffer"},
    {"_c2py_perf_meta", (PyCFunction)_c2py_perf_meta, METH_VARARGS,
     "get perf metadata tuple"},
    {"_c2py_perf_reset", (PyCFunction)_c2py_perf_reset, METH_VARARGS,
     "reset perf counter"},
    {"_c2py_perf_get_enabled", (PyCFunction)_c2py_perf_get_enabled, METH_VARARGS,
     "get timing enabled flag"},
    {"_c2py_perf_set_enabled", (PyCFunction)_c2py_perf_set_enabled, METH_VARARGS,
     "set timing enabled flag"},
    {"_c2py_set_tick_source", (PyCFunction)__c2py_set_tick_source, METH_VARARGS,
     "set tick source (\"clock\" or \"cycle\")"},
    {NULL, NULL, 0, NULL}
};

static PyMethodDef _methods_fastcall[] = {
    {"transform", (PyCFunction)_transform_fastcall, METH_FASTCALL, "transform(points, out)\n--\n\ntransform(points: buffer, out: buffer) -> void\n\nParameters\n----------\npoints : buffer\n    Type: float64 (format 'd')\n    Writable\n    Shape: 2D\nout : buffer\n    Type: float64 (format 'd')\n    Writable\n    Size must equal points\n\nChecks\n------\n  points.format == 'd'  [ValueError]\n  out.format == 'd'  [ValueError]\n  out.n == points.n  [ValueError]\n  points.ndim == 2  [ValueError]\n  points.slow_axis == 0  [ValueError]\n\nOverloads\n---------\n  transform_aos(double *points, intptr_t n, double *out) (When: points.shape[1] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[0] (intptr_t)\n         out = out.ptr (double *)\n  transform_soa(double *points, intptr_t n, double *out) (When: points.shape[0] == 3)\n    Map: points = points.ptr (double *)\n         n = points.shape[1] (intptr_t)\n         out = out.ptr (double *)\n\nValueError: expected [N,3] or [3,N] buffer"},
    {"_c2py_tick_frequency", (PyCFunction)__c2py_tick_frequency, METH_VARARGS,
     "return tick source frequency in Hz"},
    {"_c2py_ticks_to_ns", (PyCFunction)__c2py_ticks_to_ns, METH_VARARGS,
     "convert (ticks, freq_hz) to nanoseconds"},
    {"_c2py_perf_read", (PyCFunction)_c2py_perf_read, METH_VARARGS,
     "read perf data into uint64 buffer"},
    {"_c2py_perf_meta", (PyCFunction)_c2py_perf_meta, METH_VARARGS,
     "get perf metadata tuple"},
    {"_c2py_perf_reset", (PyCFunction)_c2py_perf_reset, METH_VARARGS,
     "reset perf counter"},
    {"_c2py_perf_get_enabled", (PyCFunction)_c2py_perf_get_enabled, METH_VARARGS,
     "get timing enabled flag"},
    {"_c2py_perf_set_enabled", (PyCFunction)_c2py_perf_set_enabled, METH_VARARGS,
     "set timing enabled flag"},
    {"_c2py_set_tick_source", (PyCFunction)__c2py_set_tick_source, METH_VARARGS,
     "set tick source (\"clock\" or \"cycle\")"},
    {NULL, NULL, 0, NULL}
};

static PyModuleDef _module_def = {
    PyModuleDef_HEAD_INIT,
    "xfrm",
    "Module: xfrm\nSource: ['transform.c']\nTiming: enabled\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

static PyModuleDef_FT _module_def_ft = {
    PyModuleDef_HEAD_INIT_FT,
    "xfrm",
    "Module: xfrm\nSource: ['transform.c']\nTiming: enabled\nFree-threading: no (GIL re-enabled on 3.14t)",
    -1,
    NULL,  /* methods set at init */
    NULL,  /* m_slots = NULL (single-phase init; PyUnstable_Module_SetGIL handles FT) */
    NULL, NULL, NULL
};

C2PY_EXPORT PyObject* PyInit_xfrm(void) {
#ifdef _MSC_VER
    { const char _m[] = "c2py: PyInit_xfrm ENTER\n"; DWORD _w; WriteFile(GetStdHandle(STD_ERROR_HANDLE), _m, (DWORD)(sizeof(_m)-1), &_w, NULL); }
    __try {
#endif
    c2py_runtime_init();
#ifdef _MSC_VER
    { const char _m[] = "c2py: c2py_runtime_init done\n"; DWORD _w; WriteFile(GetStdHandle(STD_ERROR_HANDLE), _m, (DWORD)(sizeof(_m)-1), &_w, NULL); }
#endif

    PyObject *module = NULL;
    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;

    if (C2PY.is_free_threaded) {
        _module_def_ft.m_methods = methods;
        if (C2PY.Module_Create2 != NULL) {
            module = C2PY.Module_Create2((PyModuleDef*)&_module_def_ft, 3);
        }
    } else {
        _module_def.m_methods = methods;
        if (C2PY.Module_Create2 != NULL) {
            module = C2PY.Module_Create2(&_module_def, 3);
        } else {
            /* Fallback for Python 2.7 where PyModuleDef is not supported */
            module = C2PY.InitModule_2_7("xfrm", methods);
        }
    }

    if (module != NULL) {
        PyObject_SetAttrString(module, "_c2py_cycle_counter_frequency",
            PyLong_FromUnsignedLongLong(c2py_cycle_counter_frequency_hz));
        PyObject_SetAttrString(module, "_c2py_perf_ptr_transform",
            PyLong_FromVoidPtr(&_perf_transform));
        PyObject_SetAttrString(module, "_c2py_ol_ptr_transform__transform_aos",
            PyLong_FromVoidPtr(&_perf_transform__transform_aos));
        PyObject_SetAttrString(module, "_c2py_ol_ptr_transform__transform_soa",
            PyLong_FromVoidPtr(&_perf_transform__transform_soa));
    }
    return module;
#ifdef _MSC_VER
    } __except(c2py_seh_filter(GetExceptionCode(), GetExceptionInformation())) {
        return NULL;
    }
#endif
}

C2PY_EXPORT void initxfrm(void) {
    c2py_runtime_init();

    PyObject *module = C2PY.InitModule_2_7("xfrm",
        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);
    if (module != NULL) {
        PyObject_SetAttrString(module, "_c2py_cycle_counter_frequency",
            PyLong_FromUnsignedLongLong(c2py_cycle_counter_frequency_hz));
        PyObject_SetAttrString(module, "_c2py_perf_ptr_transform",
            PyLong_FromVoidPtr(&_perf_transform));
        PyObject_SetAttrString(module, "_c2py_ol_ptr_transform__transform_aos",
            PyLong_FromVoidPtr(&_perf_transform__transform_aos));
        PyObject_SetAttrString(module, "_c2py_ol_ptr_transform__transform_soa",
            PyLong_FromVoidPtr(&_perf_transform__transform_soa));
    }
}
