"""C code generator for c2py23.

Transpiles a parsed ModuleDef AST into a compilable CPython C extension source file.
Uses the nimpy-style c2py_runtime.h for Python API access.
"""
from __future__ import print_function

from c2py23.parser import (
    Var, Attr, Subscript, IntLit, StrLit, Compare, BinOp, UnaryOp,
    PyParam, CParam, COverload, FuncDef, ModuleDef,
)


def generate(module_def):
    """Generate C source code for a module wrapper.

    Args:
        module_def: ModuleDef namedtuple from parser

    Returns:
        String containing complete C source code
    """
    out = []
    _emit_header(out, module_def)
    _emit_forward_decls(out, module_def)
    if module_def.timing:
        _emit_timing_decls(out, module_def)
    for func in module_def.functions:
        _emit_function(out, func, module_def.name, module_def.timing)
    _emit_module_init(out, module_def)
    return '\n'.join(out)


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

def _emit_header(out, mod):
    out.append('/* Generated by c2py23 - do not edit by hand */')
    out.append('#include <stdio.h>')
    out.append('#include "c2py_runtime.h"')
    for h in mod.headers:
        out.append('#include "{}"'.format(h))
    out.append('')


# ---------------------------------------------------------------------------
# Forward declarations of C functions
# ---------------------------------------------------------------------------

def _emit_forward_decls(out, mod):
    seen = set()
    for func in mod.functions:
        for ol in func.overloads:
            c_name = _extract_c_name(ol.sig_str)
            if c_name not in seen:
                seen.add(c_name)
                out.append(_c_decl_from_overload(ol))
    out.append('')


def _extract_c_name(sig_str):
    """Extract the C function name from a sig string."""
    return sig_str.split('(')[0].strip().split()[-1]


def _c_decl_from_overload(ol):
    """Generate an extern declaration for the C function."""
    ret = ol.return_type if ol.return_type != 'void' else 'void'
    parts = []
    for p in ol.params:
        parts.append(p.ctype + ' ' + p.name)
    return 'extern {} {}({});'.format(ret, _extract_c_name(ol.sig_str), ', '.join(parts))


# ---------------------------------------------------------------------------
# Function wrapper generation
# ---------------------------------------------------------------------------

def _emit_timing_decls(out, mod):
    """Emit global timing declarations: enabled flag + per-func/per-overload perf structs."""
    out.append('/* ---- Performance timing ---- */')
    out.append('static int _c2py_timing_enabled = 1;')
    out.append('')
    for func in mod.functions:
        out.append('static c2py_perf_t _perf_{0};'.format(func.name))
        for ol in func.overloads:
            c_name = _extract_c_name(ol.sig_str)
            out.append('static c2py_perf_t _perf_{0}__{1};'.format(func.name, c_name))
    out.append('')


def _emit_function(out, func, module_name, timing):
    name = func.name
    out.append('/* ' + '-' * 44 + ' */')
    out.append('/* Wrapper for: {} */'.format(name))
    out.append('/* ' + '-' * 44 + ' */')
    out.append('')

    buf_params = [p for p in func.py_params if p.pytype == 'buffer']
    scalar_params = [p for p in func.py_params if p.pytype != 'buffer']

    # _impl function
    _emit_impl_func(out, func, buf_params, scalar_params, timing)

    # _wrapper function
    _emit_wrapper_func(out, func, buf_params, scalar_params, timing)


# ---------------------------------------------------------------------------
# _impl function
# ---------------------------------------------------------------------------

def _emit_impl_func(out, func, buf_params, scalar_params, timing):
    name = func.name
    params_c = []
    for p in buf_params:
        params_c.append('Py_buffer *buf_' + p.name)
    for p in scalar_params:
        if p.pytype == 'int':
            params_c.append('int c_' + p.name)
        else:
            params_c.append('double c_' + p.name)

    out.append('static PyObject*')
    out.append('_' + name + '_impl({})'.format(', '.join(params_c)))
    out.append('{')

    if timing:
        out.append('    int _c2py_do_time = _c2py_timing_enabled;')
        out.append('    uint64_t _c2py_ct0 = 0, _c2py_ct1 = 0;')
        out.append('')

    # Checks
    for check in func.checks:
        out.append('    /* check: {} */'.format(_expr_to_source(check)))
        _emit_check(out, check, buf_params, scalar_params)

    # Overload dispatch
    _emit_overload_dispatch(out, func, buf_params, scalar_params, timing)

    out.append('')
    out.append('    /* should not reach here */')
    out.append('    return NULL;')
    out.append('}')
    out.append('')


def _emit_overload_dispatch(out, func, buf_params, scalar_params, timing):
    """Emit the if/else chain for overload dispatch."""
    overloads = func.overloads
    default_raise = func.default_raise
    name = func.name

    # Single unconditional overload: emit directly wrapped in {}
    if len(overloads) == 1 and overloads[0].when_expr is None:
        out.append('    /* overload 0 (always) */')
        out.append('    {')
        _emit_c_call(out, overloads[0], buf_params, scalar_params, timing, name)
        out.append('    }')
        return

    # Multiple overloads or conditional: if/else chain
    for i, ol in enumerate(overloads):
        if i == 0:
            if ol.when_expr is not None:
                when_c = _expr_to_c(ol.when_expr, buf_params, scalar_params, ol)
                out.append('    if (' + when_c + ') {')
            else:
                out.append('    {  /* overload 0 (always) */')
        else:
            if ol.when_expr is not None:
                when_c = _expr_to_c(ol.when_expr, buf_params, scalar_params, ol)
                out.append('    } else if (' + when_c + ') {')
            else:
                out.append('    } else {  /* overload {} (always) */'.format(i))
        out.append('        /* {} */'.format(ol.sig_str))
        _emit_c_call(out, ol, buf_params, scalar_params, timing, name)

    if default_raise:
        out.append('    } else {')
        _emit_default_raise_body(out, default_raise)
    out.append('    }')


def _emit_check(out, check, buf_params, scalar_params):
    """Emit a check that raises if condition is false.

    For single-char format comparisons on old buffers (format == NULL),
    the generated expression already uses !format || ... to pass safely.
    For two-sided format comparisons, NULL == NULL passes correctly.

    Includes actual runtime values in the failure message when possible.
    """
    c_expr = _expr_to_c(check, buf_params, scalar_params, None)
    msg = _expr_to_source(check)
    diag = _make_check_diag(check, buf_params, scalar_params)
    out.append('    if (!(' + c_expr + ')) {')
    if diag:
        out.append('        ' + diag[0])
        if len(diag) > 1:
            for d in diag[1:]:
                out.append('        ' + d)
        out.append('        PyErr_SetString(PyExc_ValueError, _c2py_err);')
    else:
        out.append('        PyErr_SetString(PyExc_ValueError, "check failed: ' + _escape_c_str(msg) + '");')
    out.append('        return NULL;')
    out.append('    }')


def _make_check_diag(check, buf_params, scalar_params):
    """Generate C code to capture actual runtime values for a check failure message.

    Returns a list of C code lines (strings) that produce a diagnostic,
    ending with a snprintf into _c2py_err. Returns None if diagnostics
    cannot be generated for this expression shape.
    """
    if isinstance(check, Compare):
        return _make_compare_diag(check, buf_params, scalar_params)
    elif isinstance(check, BinOp):
        left_diag = _make_check_diag(check.left, buf_params, scalar_params)
        if left_diag is not None:
            return left_diag
        return _make_check_diag(check.right, buf_params, scalar_params)
    return None


def _make_compare_diag(compare, buf_params, scalar_params):
    """Generate diagnostic C code for a Compare expression."""
    left = compare.left
    right = compare.right
    op = compare.op

    left_c = _expr_to_c(left, buf_params, scalar_params, None)
    right_c = _expr_to_c(right, buf_params, scalar_params, None)
    source = _expr_to_source(compare)

    # Determine if either side is a format attribute
    left_is_format = isinstance(left, Attr) and left.attr == 'format'
    right_is_format = isinstance(right, Attr) and right.attr == 'format'

    # Format comparison: show actual format chars
    if left_is_format and isinstance(right, StrLit) and len(right.value) == 1:
        escaped_src = _escape_c_str(source)
        lines = [
            'char _c2py_err[256];',
            'const char *_fmt = {0} ? {0} : "";'.format(left_c),
            'char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : \'?\';',
            'snprintf(_c2py_err, sizeof(_c2py_err), '
            '"check failed: {0} (got format=\'%c\')", _got);'.format(escaped_src)
        ]
        return lines
    if right_is_format and isinstance(left, StrLit) and len(left.value) == 1:
        escaped_src = _escape_c_str(source)
        lines = [
            'char _c2py_err[256];',
            'const char *_fmt = {0} ? {0} : "";'.format(right_c),
            'char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : \'?\';',
            'snprintf(_c2py_err, sizeof(_c2py_err), '
            '"check failed: {0} (got format=\'%c\')", _got);'.format(escaped_src)
        ]
        return lines

    # Format vs format comparison
    if left_is_format and right_is_format:
        escaped_src = _escape_c_str(source)
        lines = [
            'char _c2py_err[256];',
            'const char *_fmt_l = {0} ? {0} : "";'.format(left_c),
            'const char *_fmt_r = {0} ? {0} : "";'.format(right_c),
            'char _gl = _fmt_l[0] ? _fmt_l[strlen(_fmt_l) - 1] : \'?\';',
            'char _gr = _fmt_r[0] ? _fmt_r[strlen(_fmt_r) - 1] : \'?\';',
            'snprintf(_c2py_err, sizeof(_c2py_err), '
            '"check failed: {0} (got \'%c\' vs \'%c\')", _gl, _gr);'.format(escaped_src)
        ]
        return lines

    # Generic numeric comparison: show both sides as int
    if _is_simple_expr(left) and _is_simple_expr(right):
        escaped_src = _escape_c_str(source)
        lines = [
            'char _c2py_err[256];',
            'snprintf(_c2py_err, sizeof(_c2py_err), '
            '"check failed: {0} (got %ld vs %ld)",'
            ' (long)({1}), (long)({2}));'.format(escaped_src, left_c, right_c)
        ]
        return lines

    return None


def _is_simple_expr(expr):
    """Check if an expression is simple enough to inline in a format string."""
    if isinstance(expr, (Var, IntLit)):
        return True
    if isinstance(expr, Attr) and isinstance(expr.obj, Var):
        return True  # a.n, a.len, a.ndim etc.
    return False


def _emit_c_call(out, ol, buf_params, scalar_params, timing, func_name):
    """Emit a C function call for one overload.
    
    Handles optional output scalars (ol.outputs): auto-allocates 1-element
    stack variables, passes pointers, and returns values as Python objects.
    """
    c_name = _extract_c_name(ol.sig_str)
    perf_name = '_perf_{0}__{1}'.format(func_name, c_name)
    outputs = getattr(ol, 'outputs', {}) or {}
    indent = '        '

    # Declare output variables before call
    for p in ol.params:
        if p.name in outputs:
            ctype = outputs[p.name]
            var_name = '_out_{0}'.format(p.name)
            if ctype in ('int', 'int8_t', 'int16_t', 'int32_t',
                         'uint8_t', 'uint16_t', 'uint32_t'):
                out.append(indent + 'int {0} = 0;'.format(var_name))
            elif ctype in ('int64_t', 'uint64_t'):
                out.append(indent + 'int64_t {0} = 0;'.format(var_name))
            elif ctype == 'float':
                out.append(indent + 'float {0} = 0.0f;'.format(var_name))
            elif ctype == 'double':
                out.append(indent + 'double {0} = 0.0;'.format(var_name))
            else:
                out.append(indent + '/* unknown output type: {} */'.format(ctype))
                out.append(indent + 'double {0} = 0.0;'.format(var_name))

    args = []
    for p in ol.params:
        if p.name in outputs:
            var_name = '_out_{0}'.format(p.name)
            args.append('&' + var_name)
        else:
            expr = ol.map_exprs.get(p.name)
            if expr is None:
                if p.is_pointer:
                    raise ValueError("Pointer param '{}' missing map entry".format(p.name))
                for sp in scalar_params:
                    if sp.name == p.name:
                        if p.base_type == 'int':
                            args.append('c_' + p.name)
                        elif p.base_type == 'float':
                            args.append('(float)c_' + p.name)
                        elif p.base_type == 'double':
                            args.append('c_' + p.name)
                        break
                else:
                    args.append('/* unhandled: {} */'.format(p.name))
            else:
                c_str = _expr_to_c(expr, buf_params, scalar_params, ol)
                if p.is_pointer and _is_ptr_expr(expr):
                    c_str = '(' + p.ctype + ')' + c_str
                elif not p.is_pointer and p.base_type == 'int' and _expr_is_n_count(expr):
                    c_str = '(int)(' + c_str + ')'
                elif not p.is_pointer and p.base_type == 'float':
                    c_str = '(float)(' + c_str + ')'
                args.append(c_str)

    call_str = c_name + '(' + ', '.join(args) + ')'

    # --- timing: pre-C call ---
    if timing:
        out.append(indent + 'if (_c2py_do_time) _c2py_ct0 = c2py_ticks();')

    # Determine effective return type (may have outputs appended)
    has_outputs = bool(outputs)
    has_ret = (ol.return_type and ol.return_type != 'void'
               and ol.return_type is not None)

    if not has_outputs:
        # Standard return (no outputs) - original behavior
        if ol.return_type == 'void' or ol.return_type is None:
            out.append(indent + call_str + ';')
            if timing:
                out.append(indent + 'if (_c2py_do_time) {')
                out.append(indent + '    _c2py_ct1 = c2py_ticks();')
                out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
                out.append(indent + '}')
            out.append(indent + 'Py_RETURN_NONE;')
        elif ol.return_type == 'int':
            out.append(indent + 'int _ret = ' + call_str + ';')
            if timing:
                out.append(indent + 'if (_c2py_do_time) {')
                out.append(indent + '    _c2py_ct1 = c2py_ticks();')
                out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
                out.append(indent + '}')
            out.append(indent + 'return PyLong_FromLong((long)_ret);')
        elif ol.return_type == 'float':
            out.append(indent + 'float _ret = ' + call_str + ';')
            if timing:
                out.append(indent + 'if (_c2py_do_time) {')
                out.append(indent + '    _c2py_ct1 = c2py_ticks();')
                out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
                out.append(indent + '}')
            out.append(indent + 'return PyFloat_FromDouble((double)_ret);')
        elif ol.return_type == 'double':
            out.append(indent + 'double _ret = ' + call_str + ';')
            if timing:
                out.append(indent + 'if (_c2py_do_time) {')
                out.append(indent + '    _c2py_ct1 = c2py_ticks();')
                out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
                out.append(indent + '}')
            out.append(indent + 'return PyFloat_FromDouble(_ret);')
        else:
            out.append(indent + '/* unknown return type: {} */'.format(ol.return_type))
            out.append(indent + call_str + ';')
            if timing:
                out.append(indent + 'if (_c2py_do_time) {')
                out.append(indent + '    _c2py_ct1 = c2py_ticks();')
                out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
                out.append(indent + '}')
            out.append(indent + 'Py_RETURN_NONE;')
        return

    # --- Output scalar handling ---
    out_items = []
    if has_ret:
        ret_var = '_c2py_retval'
        if ol.return_type == 'int':
            out.append(indent + 'int {0} = {1};'.format(ret_var, call_str))
        elif ol.return_type == 'float':
            out.append(indent + 'float {0} = {1};'.format(ret_var, call_str))
        elif ol.return_type == 'double':
            out.append(indent + 'double {0} = {1};'.format(ret_var, call_str))
        else:
            out.append(indent + '/* unknown return type: {} */'.format(ol.return_type))
            out.append(indent + call_str + ';')
            out.append(indent + 'int {0} = 0;'.format(ret_var))
        out_items.append(('ret', ol.return_type, ret_var))
    else:
        out.append(indent + call_str + ';')

    if timing:
        out.append(indent + 'if (_c2py_do_time) {')
        out.append(indent + '    _c2py_ct1 = c2py_ticks();')
        out.append(indent + '    c2py_perf_record_call(&{0}, _c2py_ct0, _c2py_ct1);'.format(perf_name))
        out.append(indent + '}')

    # Collect output items
    for p in ol.params:
        if p.name in outputs:
            ctype = outputs[p.name]
            var_name = '_out_{0}'.format(p.name)
            out_items.append((p.name, ctype, var_name))

    n = len(out_items)

    if n == 1:
        ctype = out_items[0][1]
        val = out_items[0][2]
        if ctype in ('int', 'int8_t', 'int16_t', 'int32_t',
                     'uint8_t', 'uint16_t', 'uint32_t'):
            out.append(indent + 'return PyLong_FromLong((long){0});'.format(val))
        elif ctype in ('int64_t', 'uint64_t'):
            out.append(indent + 'return PyLong_FromLongLong((long long){0});'.format(val))
        elif ctype in ('float', 'double'):
            out.append(indent + 'return PyFloat_FromDouble((double){0});'.format(val))
        else:
            out.append(indent + 'return PyFloat_FromDouble((double){0});'.format(val))
    else:
        out.append(indent + 'PyObject *_c2py_tup = PyTuple_New({0});'.format(n))
        out.append(indent + 'if (_c2py_tup == NULL) return NULL;')
        for i, (name, ctype, val) in enumerate(out_items):
            if ctype in ('int', 'int8_t', 'int16_t', 'int32_t',
                         'uint8_t', 'uint16_t', 'uint32_t'):
                out.append(indent + 'PyTuple_SetItem(_c2py_tup, {0}, '
                            'PyLong_FromLong((long){1}));'.format(i, val))
            elif ctype in ('int64_t', 'uint64_t'):
                out.append(indent + 'PyTuple_SetItem(_c2py_tup, {0}, '
                            'PyLong_FromLongLong((long long){1}));'.format(i, val))
            elif ctype in ('float', 'double'):
                out.append(indent + 'PyTuple_SetItem(_c2py_tup, {0}, '
                            'PyFloat_FromDouble((double){1}));'.format(i, val))
            else:
                out.append(indent + 'PyTuple_SetItem(_c2py_tup, {0}, '
                            'PyFloat_FromDouble((double){1}));'.format(i, val))
        out.append(indent + 'return _c2py_tup;')


def _is_ptr_expr(expr):
    """Check if expression is a .ptr access."""
    if isinstance(expr, Attr) and expr.attr == 'ptr':
        return True
    return False


def _expr_is_n_count(expr):
    """Check if expression computes element count (.n or .len/size)."""
    if isinstance(expr, Attr) and expr.attr in ('n', 'len'):
        return True
    return False


def _emit_default_raise_body(out, default_raise):
    """Emit the body of a default raise block."""
    if ':' in default_raise:
        exc_type, msg = default_raise.split(':', 1)
        exc_type = exc_type.strip()
        msg = msg.strip()
    else:
        exc_type = 'TypeError'
        msg = default_raise
    exc_name = 'PyExc_' + exc_type
    out.append('        PyErr_SetString(' + exc_name + ', "{}");'.format(_escape_c_str(msg)))
    out.append('        return NULL;')


# ---------------------------------------------------------------------------
# _wrapper function (arg parsing, buffer acquire, cleanup)
# ---------------------------------------------------------------------------

def _emit_wrapper_func(out, func, buf_params, scalar_params, timing):
    """Emit both VARARGS (Python < 3.12) and FASTCALL (Python >= 3.12) wrappers."""
    _emit_varargs_wrapper(out, func, buf_params, scalar_params, timing)
    _emit_fastcall_wrapper(out, func, buf_params, scalar_params, timing)


def _emit_varargs_wrapper(out, func, buf_params, scalar_params, timing):
    """Emit the METH_VARARGS wrapper (Python 2.7 through 3.11)."""
    name = func.name
    all_params = func.py_params

    out.append('static PyObject*')
    out.append('_' + name + '_wrapper(PyObject *self, PyObject *args, PyObject *kwargs)')
    out.append('{')

    # Local variables
    _emit_wrapper_locals(out, buf_params, scalar_params, timing)

    # Arg parse via PyArg_ParseTuple
    fmt_str = _build_parse_format(all_params)
    parse_args = ['args', '"' + fmt_str + '"']
    for p in all_params:
        if p.pytype == 'buffer':
            parse_args.append('&py_' + p.name)
        elif p.pytype == 'int':
            parse_args.append('&c_' + p.name)
        else:
            parse_args.append('&c_' + p.name)
    out.append('    if (!PyArg_ParseTuple({}))'.format(', '.join(parse_args)))
    out.append('        return NULL;')
    out.append('')

    # Shared body: buffer init, acquire, checks, impl, cleanup
    _emit_wrapper_body(out, func, buf_params, scalar_params, name, timing)

    out.append('}')
    out.append('')


def _emit_fastcall_wrapper(out, func, buf_params, scalar_params, timing):
    """Emit the METH_FASTCALL wrapper (Python >= 3.12)."""
    name = func.name
    all_params = func.py_params

    out.append('static PyObject*')
    out.append('_' + name + '_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)')
    out.append('{')

    # Local variables
    _emit_wrapper_locals(out, buf_params, scalar_params, timing)

    # Arg count check (handle optional params with defaults)
    total = len(all_params)
    min_req = sum(1 for p in all_params if p.default is None)
    if min_req == total:
        out.append('    if (nargs != {0}) {{'.format(total))
        out.append('        PyErr_SetString(PyExc_TypeError,')
        out.append('            \"{0} expects {1} argument{2}\");'.format(
            name, total, 's' if total != 1 else ''))
        out.append('        return NULL;')
        out.append('    }')
    else:
        out.append('    if (nargs < {0} || nargs > {1}) {{'.format(min_req, total))
        out.append('        PyErr_SetString(PyExc_TypeError,')
        out.append('            \"{0} expects {1} to {2} arguments\");'.format(
            name, min_req, total))
        out.append('        return NULL;')
        out.append('    }')
    out.append('')

    # Extract args directly from the array (only up to nargs)
    idx = 0
    for p in all_params:
        is_optional = (p.default is not None)
        if p.pytype == 'buffer':
            out.append('    py_{0} = args[{1}];'.format(p.name, idx))
        elif p.pytype == 'int':
            out.append('    /* extract int: {0} from args[{1}]{2} */'.format(
                p.name, idx, ' (optional)' if is_optional else ''))
            if is_optional:
                out.append('    if (nargs > {0}) {{'.format(idx))
            else:
                out.append('    {')
            out.append('        long _c2py_tmp = PyLong_AsLong(args[{0}]);'.format(idx))
            out.append('        if (_c2py_tmp == -1 && PyErr_Occurred()) return NULL;')
            out.append('        c_{0} = (int)_c2py_tmp;'.format(p.name))
            out.append('    }')
        else:
            out.append('    /* extract float: {0} from args[{1}]{2} */'.format(
                p.name, idx, ' (optional)' if is_optional else ''))
            if is_optional:
                out.append('    if (nargs > {0}) {{'.format(idx))
            else:
                out.append('    {')
            out.append('        double _c2py_tmp = PyFloat_AsDouble(args[{0}]);'.format(idx))
            out.append('        if (_c2py_tmp == -1.0 && PyErr_Occurred()) return NULL;')
            out.append('        c_{0} = _c2py_tmp;'.format(p.name))
            out.append('    }')
        idx += 1

    out.append('')

    # Shared body: buffer init, acquire, checks, impl, cleanup
    _emit_wrapper_body(out, func, buf_params, scalar_params, name, timing)

    out.append('}')
    out.append('')


def _emit_wrapper_locals(out, buf_params, scalar_params, timing=False):
    """Emit local variable declarations shared by both wrappers."""
    for p in buf_params:
        out.append('    PyObject *py_' + p.name + ' = NULL;')
    for p in scalar_params:
        default_val = p.default
        if p.pytype == 'int':
            if default_val is None:
                out.append('    int c_%s = 0;' % p.name)
            else:
                out.append('    int c_%s = %d;' % (p.name, int(default_val)))
        else:
            if default_val is None:
                out.append('    double c_%s = 0.0;' % p.name)
            else:
                out.append('    double c_%s = %s;' % (p.name, _float_literal(default_val)))

    for p in buf_params:
        out.append('    Py_buffer buf_{0};'.format(p.name))
        out.append('    int acq_{0} = 0;'.format(p.name))

    out.append('    PyObject *ret = NULL;')

    if timing:
        out.append('    int _c2py_do_time = _c2py_timing_enabled;')
        out.append('    uint64_t _c2py_t0 = 0, _c2py_t1 = 0, _c2py_t2 = 0;')
        out.append('    if (_c2py_do_time) _c2py_t0 = c2py_ticks();')

    out.append('')


def _emit_wrapper_body(out, func, buf_params, scalar_params, name, timing=False):
    """Emit the shared wrapper body: buffer init, acquire, checks, impl call, cleanup."""
    perf_name = '_perf_' + name

    # Initialize buffers
    for p in buf_params:
        out.append('    memset(&buf_{0}, 0, C2PY.pybuffer_size);'.format(p.name))
    out.append('')

    # Acquire buffers
    for i, p in enumerate(buf_params):
        flags = _get_buf_flags(p, func)
        want_write = 'PyBUF_WRITABLE' in flags
        write_val = 'C2PY_BUF_WRITE' if want_write else 'C2PY_BUF_READ'
        out.append('    if (c2py_acquire_buffer(py_{0}, &buf_{0}, {1}) == -1)'.format(p.name, write_val))
        if i == 0:
            out.append('        return NULL;')
        else:
            out.append('        goto cleanup;')
        out.append('    acq_{0} = 1;'.format(p.name))
        out.append('')

    # Restrict checks
    _emit_restrict_checks(out, buf_params, func)

    # Call impl (with timing ticks around it)
    impl_args = []
    for p in buf_params:
        impl_args.append('&buf_' + p.name)
    for p in scalar_params:
        impl_args.append('c_' + p.name)

    if timing:
        out.append('    if (_c2py_do_time) _c2py_t1 = c2py_ticks();')
    out.append('    ret = _{0}_impl({1});'.format(name, ', '.join(impl_args)))
    if timing:
        out.append('    if (_c2py_do_time) _c2py_t2 = c2py_ticks();')
    out.append('')

    # Cleanup
    if len(buf_params) >= 2:
        out.append('cleanup:')
    for p in reversed(buf_params):
        out.append('    if (acq_{0}) c2py_release_buffer(&buf_{0});'.format(p.name))

    if timing:
        out.append('')
        out.append('    if (_c2py_do_time) {')
        out.append('        c2py_perf_record(&{0}, _c2py_t0, _c2py_t1, _c2py_t2, c2py_ticks());'.format(perf_name))
        out.append('    }')

    out.append('    return ret;')


def _build_parse_format(py_params):
    """Build the PyArg_ParseTuple format string.

    Inserts '|' before the first optional parameter (one with a default).
    """
    fmt = ''
    hit_optional = False
    for p in py_params:
        if not hit_optional and p.default is not None:
            hit_optional = True
            fmt += '|'
        if p.pytype == 'buffer':
            fmt += 'O'
        elif p.pytype == 'int':
            fmt += 'i'
        elif p.pytype == 'float':
            fmt += 'd'
    return fmt


def _get_buf_flags(buf_param, func):
    """Determine PyObject_GetBuffer flags for a buffer param.

    Returns a string like "PyBUF_STRIDES | PyBUF_FORMAT" or 
    "PyBUF_WRITABLE | PyBUF_STRIDES | PyBUF_FORMAT".
    """
    # Check if this buffer is used as writable in any overload
    is_writable = False
    for ol in func.overloads:
        for cp in ol.params:
            if cp.is_pointer and not cp.is_const:
                # Check if this cp maps from this buffer
                expr = ol.map_exprs.get(cp.name)
                if expr is not None and _expr_refers_to(expr, buf_param.name):
                    is_writable = True
                    break
        if is_writable:
            break

    if is_writable:
        return 'PyBUF_WRITABLE | PyBUF_STRIDES | PyBUF_FORMAT'
    else:
        return 'PyBUF_STRIDES | PyBUF_FORMAT'


def _expr_refers_to(expr, buf_name):
    """Check if an expression refers to a specific buffer param."""
    if isinstance(expr, Var):
        return expr.name == buf_name
    elif isinstance(expr, Attr):
        return _expr_refers_to(expr.obj, buf_name)
    elif isinstance(expr, Subscript):
        return _expr_refers_to(expr.obj, buf_name)
    elif isinstance(expr, Compare):
        return _expr_refers_to(expr.left, buf_name) or _expr_refers_to(expr.right, buf_name)
    elif isinstance(expr, BinOp):
        return _expr_refers_to(expr.left, buf_name) or _expr_refers_to(expr.right, buf_name)
    elif isinstance(expr, UnaryOp):
        return _expr_refers_to(expr.operand, buf_name)
    return False


def _emit_restrict_checks(out, buf_params, func):
    """Emit restrict alias checks between buffers.

    Any non-const pointer must not alias with any other pointer.
    """
    # Determine which buffers are writable
    writable = set()
    const_set = set()
    for p in buf_params:
        for ol in func.overloads:
            for cp in ol.params:
                if cp.is_pointer:
                    expr = ol.map_exprs.get(cp.name)
                    if expr is not None and _expr_refers_to(expr, p.name):
                        if cp.is_const:
                            const_set.add(p.name)
                        else:
                            writable.add(p.name)

    # Check writable vs writable, and writable vs const
    checked = set()
    for wn in writable:
        for other in list(writable | const_set):
            if other == wn:
                continue
            pair = tuple(sorted([wn, other]))
            if pair in checked:
                continue
            checked.add(pair)
            out.append('    /* restrict check: {} vs {} */'.format(wn, other))
            out.append('    if (buf_{0}.buf >= buf_{1}.buf && '.format(wn, other))
            out.append('        buf_{0}.buf < buf_{1}.buf + buf_{1}.len) {{'.format(wn, other))
            out.append('        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");')
            out.append('        goto cleanup;')
            out.append('    }')
            out.append('    if (buf_{0}.buf >= buf_{1}.buf && '.format(other, wn))
            out.append('        buf_{0}.buf < buf_{1}.buf + buf_{1}.len) {{'.format(other, wn))
            out.append('        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");')
            out.append('        goto cleanup;')
            out.append('    }')
            out.append('')


# ---------------------------------------------------------------------------
# Expression transpiler: AST -> C code string
# ---------------------------------------------------------------------------

def _expr_to_c(expr, buf_params, scalar_params, current_ol):
    """Transpile an expression AST node to a C expression string."""
    if expr is None:
        return '1'  # No condition = always true

    if isinstance(expr, Var):
        name = expr.name
        # Is it a buffer param?
        for p in buf_params:
            if p.name == name:
                return 'buf_' + name
        # Is it a scalar param?
        for p in scalar_params:
            if p.name == name:
                return 'c_' + name
        return name

    elif isinstance(expr, Attr):
        obj = _expr_to_c(expr.obj, buf_params, scalar_params, current_ol)
        attr = expr.attr
        if attr == 'format':
            return obj + '->format'
        elif attr == 'ndim':
            return obj + '->ndim'
        elif attr == 'itemsize':
            return obj + '->itemsize'
        elif attr == 'len':
            return obj + '->len'
        elif attr == 'n':
            return '(' + obj + '->len / ' + obj + '->itemsize)'
        elif attr == 'ptr':
            return obj + '->buf'
        elif attr == 'shape':
            return obj + '->shape'
        elif attr == 'strides':
            return obj + '->strides'
        else:
            return obj + '->' + attr

    elif isinstance(expr, Subscript):
        obj = _expr_to_c(expr.obj, buf_params, scalar_params, current_ol)
        idx = expr.index
        return '{}[{}]'.format(obj, idx)

    elif isinstance(expr, IntLit):
        return str(expr.value)

    elif isinstance(expr, StrLit):
        return '"' + _escape_c_str(expr.value) + '"'

    elif isinstance(expr, Compare):
        left = _expr_to_c(expr.left, buf_params, scalar_params, current_ol)
        right = _expr_to_c(expr.right, buf_params, scalar_params, current_ol)
        op = expr.op

        # String comparison with format char: use last-char match for
        # PEP 3118 format strings (handles "d", "<d", "=d", etc.)
        # On old buffers (format == NULL), treat as matching (we can't check)
        if isinstance(expr.left, StrLit) or isinstance(expr.right, StrLit):
            str_lit = expr.left if isinstance(expr.left, StrLit) else expr.right
            fmt_expr = right if isinstance(expr.left, StrLit) else left
            if len(str_lit.value) == 1:
                ch = str_lit.value
                if op == '==':
                    return '(!{0} || {0}[strlen({0}) - 1] == \'{1}\')'.format(fmt_expr, ch)
                elif op == '!=':
                    return '({0} && {0}[strlen({0}) - 1] != \'{1}\')'.format(fmt_expr, ch)
            if op == '==':
                return 'strcmp({}, {}) == 0'.format(left, right)
            elif op == '!=':
                return 'strcmp({}, {}) != 0'.format(left, right)
            else:
                raise ValueError("Unsupported comparison op '{}' for strings".format(op))
        else:
            return '({}) {} ({})'.format(left, op, right)

    elif isinstance(expr, BinOp):
        left = _expr_to_c(expr.left, buf_params, scalar_params, current_ol)
        right = _expr_to_c(expr.right, buf_params, scalar_params, current_ol)
        if expr.op == 'and':
            return '({}) && ({})'.format(left, right)
        elif expr.op == 'or':
            return '({}) || ({})'.format(left, right)
        else:
            raise ValueError("Unknown binop: {}".format(expr.op))

    elif isinstance(expr, UnaryOp):
        operand = _expr_to_c(expr.operand, buf_params, scalar_params, current_ol)
        if expr.op == 'not':
            return '!({})'.format(operand)
        else:
            raise ValueError("Unknown unary op: {}".format(expr.op))

    else:
        raise ValueError("Unknown expression type: {}".format(type(expr)))


def _expr_to_source(expr):
    """Convert an AST node back to its source form (for comments/error messages)."""
    if isinstance(expr, Var):
        return expr.name
    elif isinstance(expr, Attr):
        return _expr_to_source(expr.obj) + '.' + expr.attr
    elif isinstance(expr, Subscript):
        return _expr_to_source(expr.obj) + '[' + str(expr.index) + ']'
    elif isinstance(expr, IntLit):
        return str(expr.value)
    elif isinstance(expr, StrLit):
        return "'" + expr.value + "'"
    elif isinstance(expr, Compare):
        return '{} {} {}'.format(
            _expr_to_source(expr.left), expr.op, _expr_to_source(expr.right))
    elif isinstance(expr, BinOp):
        return '({} {} {})'.format(
            _expr_to_source(expr.left), expr.op, _expr_to_source(expr.right))
    elif isinstance(expr, UnaryOp):
        return '{}({})'.format(expr.op, _expr_to_source(expr.operand))
    else:
        return str(expr)


# ---------------------------------------------------------------------------
# Module init
# ---------------------------------------------------------------------------

def _emit_constants(out, mod):
    """Emit PyObject_SetAttrString calls for module-level integer constants
    and timing perf struct pointers."""
    if not mod.constants and not mod.timing:
        return
    out.append('    if (module != NULL) {')
    if mod.constants:
        for cname, cvalue in sorted(mod.constants.items()):
            out.append('        PyObject_SetAttrString(module, "{}",'.format(_escape_c_str(cname)))
            out.append('            PyLong_FromLong({}));'.format(cvalue))
    if mod.timing:
        out.append('        PyObject_SetAttrString(module, "_c2py_timing_enabled",')
        out.append('            PyLong_FromVoidPtr(&_c2py_timing_enabled));')
        for func in mod.functions:
            out.append('        PyObject_SetAttrString(module, "_perf_{0}",'.format(func.name))
            out.append('            PyLong_FromVoidPtr(&_perf_{0}));'.format(func.name))
            for ol in func.overloads:
                c_name = _extract_c_name(ol.sig_str)
                perf_name = '_perf_{0}__{1}'.format(func.name, c_name)
                out.append('        PyObject_SetAttrString(module, "{}",'.format(perf_name))
                out.append('            PyLong_FromVoidPtr(&{}));'.format(perf_name))
    out.append('    }')


def _emit_module_init(out, mod):
    name = mod.name
    out.append('')
    out.append('/* ' + '-' * 44 + ' */')
    out.append('/* Module definition                          */')
    out.append('/* ' + '-' * 44 + ' */')
    out.append('')

    # Helper to build doc string
    def _doc(func):
        py_args = []
        for p in func.py_params:
            py_args.append('{}: {}'.format(p.name, p.pytype))
        default_doc = '{}({}) -> {}'.format(func.name, ', '.join(py_args), func.return_type)
        return func.doc if func.doc is not None else default_doc

    # --- VARARGS method table (Python < 3.12) ---
    out.append('static PyMethodDef _methods_varargs[] = {')
    for func in mod.functions:
        out.append('    {{"{}", (PyCFunction)_{}_wrapper, METH_VARARGS, "{}"}},'.format(
            func.name, func.name, _doc(func)))
    out.append('    {NULL, NULL, 0, NULL}')
    out.append('};')
    out.append('')

    # --- FASTCALL method table (Python >= 3.12) ---
    out.append('static PyMethodDef _methods_fastcall[] = {')
    for func in mod.functions:
        out.append('    {{"{}", (PyCFunction)_{}_fastcall, METH_FASTCALL, "{}"}},'.format(
            func.name, func.name, _doc(func)))
    out.append('    {NULL, NULL, 0, NULL}')
    out.append('};')
    out.append('')

    # Module definition struct - methods pointer set at init time
    out.append('static PyModuleDef _module_def = {')
    out.append('    PyModuleDef_HEAD_INIT,')
    out.append('    "{}",'.format(name))
    out.append('    NULL,')
    out.append('    -1,')
    out.append('    NULL,  /* methods set at init */')
    out.append('    NULL, NULL, NULL, NULL')
    out.append('};')
    out.append('')

    # Python 3 init
    out.append('PyObject* PyInit_{}(void) {{'.format(name))
    out.append('    c2py_runtime_init();')
    out.append('')
    out.append('    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;')
    out.append('    _module_def.m_methods = methods;')
    out.append('')
    if mod.constants or mod.timing:
        out.append('    PyObject *module;')
        out.append('    if (C2PY.Module_Create2 != NULL) {')
        out.append('        module = C2PY.Module_Create2(&_module_def, 1013);')
        out.append('    } else {')
        out.append('        /* Fallback for Python 2.7 where PyModuleDef is not supported */')
        out.append('        module = C2PY.InitModule_2_7("{}", methods);'.format(name))
        out.append('    }')
        out.append('')
        _emit_constants(out, mod)
        out.append('')
        out.append('    return module;')
    else:
        out.append('    if (C2PY.Module_Create2 != NULL) {')
        out.append('        return C2PY.Module_Create2(&_module_def, 1013);')
        out.append('    }')
        out.append('    /* Fallback for Python 2.7 where PyModuleDef is not supported */')
        out.append('    return C2PY.InitModule_2_7("{}", methods);'.format(name))
    out.append('}')
    out.append('')

    # Python 2.7 init
    out.append('void init{}(void) {{'.format(name))
    out.append('    c2py_runtime_init();')
    if mod.constants or mod.timing:
        out.append('    PyObject *module = C2PY.InitModule_2_7("{}",'.format(name))
        out.append('        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);')
        _emit_constants(out, mod)
    else:
        out.append('    C2PY.InitModule_2_7("{}",'.format(name))
        out.append('        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);')
    out.append('}')


def _escape_c_str(s):
    """Escape a string for use in a C string literal."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '\\r')
    s = s.replace('\t', '\\t')
    return s


def _float_literal(value):
    """Convert a Python float to a C double literal string.
    Handles whole-number floats (3.0 -> 3.0) and fractions."""
    s = "%.15g" % value
    if '.' not in s and 'e' not in s and 'E' not in s:
        s += ".0"
    return s
