/* Generated by c2py23 - do not edit by hand */
#include <stdio.h>
#include "c2py_runtime.h"
#include "kissfft/kiss_fft.h"
#include "kissfft/kiss_fftr.h"

extern void kissfft_rfft_forward(const float * data, float * spec, int n);
extern void kissfft_cfft_forward(const float * fin, float * fout, int n);

/* -------------------------------------------- */
/* Wrapper for: rfft_forward */
/* -------------------------------------------- */

static PyObject*
_rfft_forward_impl(Py_buffer *buf_data, Py_buffer *buf_spec)
{
    /* check: data.format == 'f' */
    if (!((!buf_data->format || buf_data->format[strlen(buf_data->format) - 1] == 'f'))) {
        char _c2py_err[256];
        const char *_fmt = buf_data->format ? buf_data->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: data.format == 'f' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: spec.format == 'f' */
    if (!((!buf_spec->format || buf_spec->format[strlen(buf_spec->format) - 1] == 'f'))) {
        char _c2py_err[256];
        const char *_fmt = buf_spec->format ? buf_spec->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: spec.format == 'f' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: data.ndim == 1 */
    if (!((buf_data->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: data.ndim == 1 (got %ld vs %ld)", (long)(buf_data->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: spec.ndim == 1 */
    if (!((buf_spec->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: spec.ndim == 1 (got %ld vs %ld)", (long)(buf_spec->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* overload 0 (always) */
    {
        if (((buf_data->len / buf_data->itemsize)) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        kissfft_rfft_forward((const float *)buf_data->buf, (float *)buf_spec->buf, (int)((buf_data->len / buf_data->itemsize)));
        Py_RETURN_NONE;
    }

    /* should not reach here */
    return NULL;
}

static PyObject*
_rfft_forward_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_data = NULL;
    PyObject *py_spec = NULL;
    Py_buffer buf_data;
    int acq_data = 0;
    Py_buffer buf_spec;
    int acq_spec = 0;
    PyObject *ret = NULL;

    if (!PyArg_ParseTuple(args, "OO", &py_data, &py_spec))
        return NULL;

    memset(&buf_data, 0, C2PY.pybuffer_size);
    memset(&buf_spec, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_data, &buf_data, C2PY_BUF_READ) == -1)
        return NULL;
    acq_data = 1;

    if (c2py_acquire_buffer(py_spec, &buf_spec, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_spec = 1;

    /* restrict check: spec vs data */
    if (buf_spec.buf >= buf_data.buf && 
        buf_spec.buf < buf_data.buf + buf_data.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_data.buf >= buf_spec.buf && 
        buf_data.buf < buf_spec.buf + buf_spec.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: data */
    do {
        int _ok = 1;
        if (buf_data.strides == NULL && buf_data.ndim <= 1) break;
        if (buf_data.ndim >= 1) {
            Py_ssize_t _expected = buf_data.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_data.ndim; _d++) {
                if (buf_data.strides[_d] < 0) { _ok = 0; break; }
                if (buf_data.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_data.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_data.itemsize;
            for (_d = buf_data.ndim - 1; _d >= 0; _d--) {
                if (buf_data.strides[_d] < 0) { _ok = 0; break; }
                if (buf_data.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_data.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: spec */
    do {
        int _ok = 1;
        if (buf_spec.strides == NULL && buf_spec.ndim <= 1) break;
        if (buf_spec.ndim >= 1) {
            Py_ssize_t _expected = buf_spec.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_spec.ndim; _d++) {
                if (buf_spec.strides[_d] < 0) { _ok = 0; break; }
                if (buf_spec.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_spec.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_spec.itemsize;
            for (_d = buf_spec.ndim - 1; _d >= 0; _d--) {
                if (buf_spec.strides[_d] < 0) { _ok = 0; break; }
                if (buf_spec.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_spec.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _rfft_forward_impl(&buf_data, &buf_spec);

cleanup:
    if (acq_spec) c2py_release_buffer(&buf_spec);
    if (acq_data) c2py_release_buffer(&buf_data);
    return ret;
}

static PyObject*
_rfft_forward_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_data = NULL;
    PyObject *py_spec = NULL;
    Py_buffer buf_data;
    int acq_data = 0;
    Py_buffer buf_spec;
    int acq_spec = 0;
    PyObject *ret = NULL;

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "rfft_forward expects 2 arguments");
        return NULL;
    }

    py_data = args[0];
    py_spec = args[1];

    memset(&buf_data, 0, C2PY.pybuffer_size);
    memset(&buf_spec, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_data, &buf_data, C2PY_BUF_READ) == -1)
        return NULL;
    acq_data = 1;

    if (c2py_acquire_buffer(py_spec, &buf_spec, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_spec = 1;

    /* restrict check: spec vs data */
    if (buf_spec.buf >= buf_data.buf && 
        buf_spec.buf < buf_data.buf + buf_data.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_data.buf >= buf_spec.buf && 
        buf_data.buf < buf_spec.buf + buf_spec.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: data */
    do {
        int _ok = 1;
        if (buf_data.strides == NULL && buf_data.ndim <= 1) break;
        if (buf_data.ndim >= 1) {
            Py_ssize_t _expected = buf_data.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_data.ndim; _d++) {
                if (buf_data.strides[_d] < 0) { _ok = 0; break; }
                if (buf_data.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_data.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_data.itemsize;
            for (_d = buf_data.ndim - 1; _d >= 0; _d--) {
                if (buf_data.strides[_d] < 0) { _ok = 0; break; }
                if (buf_data.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_data.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: spec */
    do {
        int _ok = 1;
        if (buf_spec.strides == NULL && buf_spec.ndim <= 1) break;
        if (buf_spec.ndim >= 1) {
            Py_ssize_t _expected = buf_spec.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_spec.ndim; _d++) {
                if (buf_spec.strides[_d] < 0) { _ok = 0; break; }
                if (buf_spec.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_spec.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_spec.itemsize;
            for (_d = buf_spec.ndim - 1; _d >= 0; _d--) {
                if (buf_spec.strides[_d] < 0) { _ok = 0; break; }
                if (buf_spec.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_spec.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _rfft_forward_impl(&buf_data, &buf_spec);

cleanup:
    if (acq_spec) c2py_release_buffer(&buf_spec);
    if (acq_data) c2py_release_buffer(&buf_data);
    return ret;
}

/* -------------------------------------------- */
/* Wrapper for: cfft_forward */
/* -------------------------------------------- */

static PyObject*
_cfft_forward_impl(Py_buffer *buf_fin, Py_buffer *buf_fout)
{
    /* check: fin.format == 'f' */
    if (!((!buf_fin->format || buf_fin->format[strlen(buf_fin->format) - 1] == 'f'))) {
        char _c2py_err[256];
        const char *_fmt = buf_fin->format ? buf_fin->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: fin.format == 'f' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: fout.format == 'f' */
    if (!((!buf_fout->format || buf_fout->format[strlen(buf_fout->format) - 1] == 'f'))) {
        char _c2py_err[256];
        const char *_fmt = buf_fout->format ? buf_fout->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: fout.format == 'f' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: fin.ndim == 1 */
    if (!((buf_fin->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: fin.ndim == 1 (got %ld vs %ld)", (long)(buf_fin->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: fout.ndim == 1 */
    if (!((buf_fout->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: fout.ndim == 1 (got %ld vs %ld)", (long)(buf_fout->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* overload 0 (always) */
    {
        if (((buf_fin->len / buf_fin->itemsize)) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        kissfft_cfft_forward((const float *)buf_fin->buf, (float *)buf_fout->buf, (int)((buf_fin->len / buf_fin->itemsize)));
        Py_RETURN_NONE;
    }

    /* should not reach here */
    return NULL;
}

static PyObject*
_cfft_forward_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_fin = NULL;
    PyObject *py_fout = NULL;
    Py_buffer buf_fin;
    int acq_fin = 0;
    Py_buffer buf_fout;
    int acq_fout = 0;
    PyObject *ret = NULL;

    if (!PyArg_ParseTuple(args, "OO", &py_fin, &py_fout))
        return NULL;

    memset(&buf_fin, 0, C2PY.pybuffer_size);
    memset(&buf_fout, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_fin, &buf_fin, C2PY_BUF_READ) == -1)
        return NULL;
    acq_fin = 1;

    if (c2py_acquire_buffer(py_fout, &buf_fout, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_fout = 1;

    /* restrict check: fout vs fin */
    if (buf_fout.buf >= buf_fin.buf && 
        buf_fout.buf < buf_fin.buf + buf_fin.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_fin.buf >= buf_fout.buf && 
        buf_fin.buf < buf_fout.buf + buf_fout.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: fin */
    do {
        int _ok = 1;
        if (buf_fin.strides == NULL && buf_fin.ndim <= 1) break;
        if (buf_fin.ndim >= 1) {
            Py_ssize_t _expected = buf_fin.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_fin.ndim; _d++) {
                if (buf_fin.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fin.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fin.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_fin.itemsize;
            for (_d = buf_fin.ndim - 1; _d >= 0; _d--) {
                if (buf_fin.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fin.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fin.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: fout */
    do {
        int _ok = 1;
        if (buf_fout.strides == NULL && buf_fout.ndim <= 1) break;
        if (buf_fout.ndim >= 1) {
            Py_ssize_t _expected = buf_fout.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_fout.ndim; _d++) {
                if (buf_fout.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fout.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fout.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_fout.itemsize;
            for (_d = buf_fout.ndim - 1; _d >= 0; _d--) {
                if (buf_fout.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fout.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fout.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _cfft_forward_impl(&buf_fin, &buf_fout);

cleanup:
    if (acq_fout) c2py_release_buffer(&buf_fout);
    if (acq_fin) c2py_release_buffer(&buf_fin);
    return ret;
}

static PyObject*
_cfft_forward_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_fin = NULL;
    PyObject *py_fout = NULL;
    Py_buffer buf_fin;
    int acq_fin = 0;
    Py_buffer buf_fout;
    int acq_fout = 0;
    PyObject *ret = NULL;

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "cfft_forward expects 2 arguments");
        return NULL;
    }

    py_fin = args[0];
    py_fout = args[1];

    memset(&buf_fin, 0, C2PY.pybuffer_size);
    memset(&buf_fout, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_fin, &buf_fin, C2PY_BUF_READ) == -1)
        return NULL;
    acq_fin = 1;

    if (c2py_acquire_buffer(py_fout, &buf_fout, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_fout = 1;

    /* restrict check: fout vs fin */
    if (buf_fout.buf >= buf_fin.buf && 
        buf_fout.buf < buf_fin.buf + buf_fin.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_fin.buf >= buf_fout.buf && 
        buf_fin.buf < buf_fout.buf + buf_fout.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: fin */
    do {
        int _ok = 1;
        if (buf_fin.strides == NULL && buf_fin.ndim <= 1) break;
        if (buf_fin.ndim >= 1) {
            Py_ssize_t _expected = buf_fin.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_fin.ndim; _d++) {
                if (buf_fin.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fin.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fin.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_fin.itemsize;
            for (_d = buf_fin.ndim - 1; _d >= 0; _d--) {
                if (buf_fin.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fin.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fin.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: fout */
    do {
        int _ok = 1;
        if (buf_fout.strides == NULL && buf_fout.ndim <= 1) break;
        if (buf_fout.ndim >= 1) {
            Py_ssize_t _expected = buf_fout.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_fout.ndim; _d++) {
                if (buf_fout.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fout.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fout.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_fout.itemsize;
            for (_d = buf_fout.ndim - 1; _d >= 0; _d--) {
                if (buf_fout.strides[_d] < 0) { _ok = 0; break; }
                if (buf_fout.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_fout.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _cfft_forward_impl(&buf_fin, &buf_fout);

cleanup:
    if (acq_fout) c2py_release_buffer(&buf_fout);
    if (acq_fin) c2py_release_buffer(&buf_fin);
    return ret;
}


/* -------------------------------------------- */
/* Module definition                          */
/* -------------------------------------------- */

static PyMethodDef _methods_varargs[] = {
    {"rfft_forward", (PyCFunction)_rfft_forward_wrapper, METH_VARARGS, "rfft_forward(data: buffer, spec: buffer) -> void"},
    {"cfft_forward", (PyCFunction)_cfft_forward_wrapper, METH_VARARGS, "cfft_forward(fin: buffer, fout: buffer) -> void"},
    {NULL, NULL, 0, NULL}
};

static PyMethodDef _methods_fastcall[] = {
    {"rfft_forward", (PyCFunction)_rfft_forward_fastcall, METH_FASTCALL, "rfft_forward(data: buffer, spec: buffer) -> void"},
    {"cfft_forward", (PyCFunction)_cfft_forward_fastcall, METH_FASTCALL, "cfft_forward(fin: buffer, fout: buffer) -> void"},
    {NULL, NULL, 0, NULL}
};

static PyModuleDef _module_def = {
    PyModuleDef_HEAD_INIT,
    "kissfftmod",
    NULL,
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

PyObject* PyInit_kissfftmod(void) {
    c2py_runtime_init();

    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;
    _module_def.m_methods = methods;

    if (C2PY.Module_Create2 != NULL) {
        return C2PY.Module_Create2(&_module_def, 1013);
    }
    /* Fallback for Python 2.7 where PyModuleDef is not supported */
    return C2PY.InitModule_2_7("kissfftmod", methods);
}

void initkissfftmod(void) {
    c2py_runtime_init();
    C2PY.InitModule_2_7("kissfftmod",
        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);
}
