/* Generated by c2py23 - do not edit by hand */
#include <stdio.h>
#include "c2py_runtime.h"
#include "lz4/lib/lz4.h"

extern int lz4_compress(const uint8_t * src, uint8_t * dst, int srcSize, int dstCapacity);
extern int lz4_decompress(const uint8_t * src, uint8_t * dst, int compressedSize, int dstCapacity);

/* -------------------------------------------- */
/* Wrapper for: compress */
/* -------------------------------------------- */

static PyObject*
_compress_impl(Py_buffer *buf_src, Py_buffer *buf_dst)
{
    /* check: src.format == 'B' */
    if (!((!buf_src->format || buf_src->format[strlen(buf_src->format) - 1] == 'B'))) {
        char _c2py_err[256];
        const char *_fmt = buf_src->format ? buf_src->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: src.format == 'B' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: dst.format == 'B' */
    if (!((!buf_dst->format || buf_dst->format[strlen(buf_dst->format) - 1] == 'B'))) {
        char _c2py_err[256];
        const char *_fmt = buf_dst->format ? buf_dst->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: dst.format == 'B' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: src.ndim == 1 */
    if (!((buf_src->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: src.ndim == 1 (got %ld vs %ld)", (long)(buf_src->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: dst.ndim == 1 */
    if (!((buf_dst->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: dst.ndim == 1 (got %ld vs %ld)", (long)(buf_dst->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* overload 0 (always) */
    {
        if ((buf_src->len) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        if ((buf_dst->len) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        int _ret = lz4_compress((const uint8_t *)buf_src->buf, (uint8_t *)buf_dst->buf, (int)(buf_src->len), (int)(buf_dst->len));
        return PyLong_FromLong((long)_ret);
    }

    /* should not reach here */
    return NULL;
}

static PyObject*
_compress_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_src = NULL;
    PyObject *py_dst = NULL;
    Py_buffer buf_src;
    int acq_src = 0;
    Py_buffer buf_dst;
    int acq_dst = 0;
    PyObject *ret = NULL;

    if (!PyArg_ParseTuple(args, "OO", &py_src, &py_dst))
        return NULL;

    memset(&buf_src, 0, C2PY.pybuffer_size);
    memset(&buf_dst, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_src, &buf_src, C2PY_BUF_READ) == -1)
        return NULL;
    acq_src = 1;

    if (c2py_acquire_buffer(py_dst, &buf_dst, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_dst = 1;

    /* restrict check: dst vs src */
    if (buf_dst.buf >= buf_src.buf && 
        buf_dst.buf < buf_src.buf + buf_src.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_src.buf >= buf_dst.buf && 
        buf_src.buf < buf_dst.buf + buf_dst.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: src */
    do {
        int _ok = 1;
        if (buf_src.strides == NULL && buf_src.ndim <= 1) break;
        if (buf_src.ndim >= 1) {
            Py_ssize_t _expected = buf_src.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_src.ndim; _d++) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_src.itemsize;
            for (_d = buf_src.ndim - 1; _d >= 0; _d--) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: dst */
    do {
        int _ok = 1;
        if (buf_dst.strides == NULL && buf_dst.ndim <= 1) break;
        if (buf_dst.ndim >= 1) {
            Py_ssize_t _expected = buf_dst.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_dst.ndim; _d++) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_dst.itemsize;
            for (_d = buf_dst.ndim - 1; _d >= 0; _d--) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _compress_impl(&buf_src, &buf_dst);

cleanup:
    if (acq_dst) c2py_release_buffer(&buf_dst);
    if (acq_src) c2py_release_buffer(&buf_src);
    return ret;
}

static PyObject*
_compress_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_src = NULL;
    PyObject *py_dst = NULL;
    Py_buffer buf_src;
    int acq_src = 0;
    Py_buffer buf_dst;
    int acq_dst = 0;
    PyObject *ret = NULL;

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "compress expects 2 arguments");
        return NULL;
    }

    py_src = args[0];
    py_dst = args[1];

    memset(&buf_src, 0, C2PY.pybuffer_size);
    memset(&buf_dst, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_src, &buf_src, C2PY_BUF_READ) == -1)
        return NULL;
    acq_src = 1;

    if (c2py_acquire_buffer(py_dst, &buf_dst, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_dst = 1;

    /* restrict check: dst vs src */
    if (buf_dst.buf >= buf_src.buf && 
        buf_dst.buf < buf_src.buf + buf_src.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_src.buf >= buf_dst.buf && 
        buf_src.buf < buf_dst.buf + buf_dst.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: src */
    do {
        int _ok = 1;
        if (buf_src.strides == NULL && buf_src.ndim <= 1) break;
        if (buf_src.ndim >= 1) {
            Py_ssize_t _expected = buf_src.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_src.ndim; _d++) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_src.itemsize;
            for (_d = buf_src.ndim - 1; _d >= 0; _d--) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: dst */
    do {
        int _ok = 1;
        if (buf_dst.strides == NULL && buf_dst.ndim <= 1) break;
        if (buf_dst.ndim >= 1) {
            Py_ssize_t _expected = buf_dst.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_dst.ndim; _d++) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_dst.itemsize;
            for (_d = buf_dst.ndim - 1; _d >= 0; _d--) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _compress_impl(&buf_src, &buf_dst);

cleanup:
    if (acq_dst) c2py_release_buffer(&buf_dst);
    if (acq_src) c2py_release_buffer(&buf_src);
    return ret;
}

/* -------------------------------------------- */
/* Wrapper for: decompress */
/* -------------------------------------------- */

static PyObject*
_decompress_impl(Py_buffer *buf_src, Py_buffer *buf_dst)
{
    /* check: src.format == 'B' */
    if (!((!buf_src->format || buf_src->format[strlen(buf_src->format) - 1] == 'B'))) {
        char _c2py_err[256];
        const char *_fmt = buf_src->format ? buf_src->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: src.format == 'B' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: dst.format == 'B' */
    if (!((!buf_dst->format || buf_dst->format[strlen(buf_dst->format) - 1] == 'B'))) {
        char _c2py_err[256];
        const char *_fmt = buf_dst->format ? buf_dst->format : "";
        char _got = _fmt[0] ? _fmt[strlen(_fmt) - 1] : '?';
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: dst.format == 'B' (got format='%c')", _got);
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: src.ndim == 1 */
    if (!((buf_src->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: src.ndim == 1 (got %ld vs %ld)", (long)(buf_src->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* check: dst.ndim == 1 */
    if (!((buf_dst->ndim) == (1))) {
        char _c2py_err[256];
        snprintf(_c2py_err, sizeof(_c2py_err), "check failed: dst.ndim == 1 (got %ld vs %ld)", (long)(buf_dst->ndim), (long)(1));
        PyErr_SetString(PyExc_ValueError, _c2py_err);
        return NULL;
    }
    /* overload 0 (always) */
    {
        if ((buf_src->len) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        if ((buf_dst->len) > (Py_ssize_t)INT_MAX) {
            PyErr_SetString(PyExc_ValueError,
                "buffer too large for int n (> INT_MAX elements)");
            return NULL;
        }
        int _ret = lz4_decompress((const uint8_t *)buf_src->buf, (uint8_t *)buf_dst->buf, (int)(buf_src->len), (int)(buf_dst->len));
        return PyLong_FromLong((long)_ret);
    }

    /* should not reach here */
    return NULL;
}

static PyObject*
_decompress_wrapper(PyObject *self, PyObject *args)
{
    PyObject *py_src = NULL;
    PyObject *py_dst = NULL;
    Py_buffer buf_src;
    int acq_src = 0;
    Py_buffer buf_dst;
    int acq_dst = 0;
    PyObject *ret = NULL;

    if (!PyArg_ParseTuple(args, "OO", &py_src, &py_dst))
        return NULL;

    memset(&buf_src, 0, C2PY.pybuffer_size);
    memset(&buf_dst, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_src, &buf_src, C2PY_BUF_READ) == -1)
        return NULL;
    acq_src = 1;

    if (c2py_acquire_buffer(py_dst, &buf_dst, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_dst = 1;

    /* restrict check: dst vs src */
    if (buf_dst.buf >= buf_src.buf && 
        buf_dst.buf < buf_src.buf + buf_src.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_src.buf >= buf_dst.buf && 
        buf_src.buf < buf_dst.buf + buf_dst.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: src */
    do {
        int _ok = 1;
        if (buf_src.strides == NULL && buf_src.ndim <= 1) break;
        if (buf_src.ndim >= 1) {
            Py_ssize_t _expected = buf_src.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_src.ndim; _d++) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_src.itemsize;
            for (_d = buf_src.ndim - 1; _d >= 0; _d--) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: dst */
    do {
        int _ok = 1;
        if (buf_dst.strides == NULL && buf_dst.ndim <= 1) break;
        if (buf_dst.ndim >= 1) {
            Py_ssize_t _expected = buf_dst.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_dst.ndim; _d++) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_dst.itemsize;
            for (_d = buf_dst.ndim - 1; _d >= 0; _d--) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _decompress_impl(&buf_src, &buf_dst);

cleanup:
    if (acq_dst) c2py_release_buffer(&buf_dst);
    if (acq_src) c2py_release_buffer(&buf_src);
    return ret;
}

static PyObject*
_decompress_fastcall(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *py_src = NULL;
    PyObject *py_dst = NULL;
    Py_buffer buf_src;
    int acq_src = 0;
    Py_buffer buf_dst;
    int acq_dst = 0;
    PyObject *ret = NULL;

    if (nargs != 2) {
        PyErr_SetString(PyExc_TypeError,
            "decompress expects 2 arguments");
        return NULL;
    }

    py_src = args[0];
    py_dst = args[1];

    memset(&buf_src, 0, C2PY.pybuffer_size);
    memset(&buf_dst, 0, C2PY.pybuffer_size);

    if (c2py_acquire_buffer(py_src, &buf_src, C2PY_BUF_READ) == -1)
        return NULL;
    acq_src = 1;

    if (c2py_acquire_buffer(py_dst, &buf_dst, C2PY_BUF_WRITE) == -1)
        goto cleanup;
    acq_dst = 1;

    /* restrict check: dst vs src */
    if (buf_dst.buf >= buf_src.buf && 
        buf_dst.buf < buf_src.buf + buf_src.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }
    if (buf_src.buf >= buf_dst.buf && 
        buf_src.buf < buf_dst.buf + buf_dst.len) {
        PyErr_SetString(PyExc_ValueError, "buffer aliasing forbidden");
        goto cleanup;
    }

    /* contiguity check: src */
    do {
        int _ok = 1;
        if (buf_src.strides == NULL && buf_src.ndim <= 1) break;
        if (buf_src.ndim >= 1) {
            Py_ssize_t _expected = buf_src.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_src.ndim; _d++) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_src.itemsize;
            for (_d = buf_src.ndim - 1; _d >= 0; _d--) {
                if (buf_src.strides[_d] < 0) { _ok = 0; break; }
                if (buf_src.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_src.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    /* contiguity check: dst */
    do {
        int _ok = 1;
        if (buf_dst.strides == NULL && buf_dst.ndim <= 1) break;
        if (buf_dst.ndim >= 1) {
            Py_ssize_t _expected = buf_dst.itemsize;
            int _d;
            /* check F-contiguous (column-major): first dim varies fastest */
            for (_d = 0; _d < buf_dst.ndim; _d++) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
            if (_ok) break;
            /* check C-contiguous (row-major): last dim varies fastest */
            _ok = 1;
            _expected = buf_dst.itemsize;
            for (_d = buf_dst.ndim - 1; _d >= 0; _d--) {
                if (buf_dst.strides[_d] < 0) { _ok = 0; break; }
                if (buf_dst.strides[_d] != _expected) { _ok = 0; break; }
                _expected *= buf_dst.shape[_d];
            }
        }
        if (!_ok) {
            PyErr_SetString(PyExc_ValueError,
                "buffer not contiguous (C or Fortran contiguous required)");
            goto cleanup;
        }
    } while(0);

    ret = _decompress_impl(&buf_src, &buf_dst);

cleanup:
    if (acq_dst) c2py_release_buffer(&buf_dst);
    if (acq_src) c2py_release_buffer(&buf_src);
    return ret;
}


/* -------------------------------------------- */
/* Module definition                          */
/* -------------------------------------------- */

static PyMethodDef _methods_varargs[] = {
    {"compress", (PyCFunction)_compress_wrapper, METH_VARARGS, "compress(src: buffer, dst: buffer) -> int"},
    {"decompress", (PyCFunction)_decompress_wrapper, METH_VARARGS, "decompress(src: buffer, dst: buffer) -> int"},
    {NULL, NULL, 0, NULL}
};

static PyMethodDef _methods_fastcall[] = {
    {"compress", (PyCFunction)_compress_fastcall, METH_FASTCALL, "compress(src: buffer, dst: buffer) -> int"},
    {"decompress", (PyCFunction)_decompress_fastcall, METH_FASTCALL, "decompress(src: buffer, dst: buffer) -> int"},
    {NULL, NULL, 0, NULL}
};

static PyModuleDef _module_def = {
    PyModuleDef_HEAD_INIT,
    "lz4mod",
    NULL,
    -1,
    NULL,  /* methods set at init */
    NULL, NULL, NULL, NULL
};

PyObject* PyInit_lz4mod(void) {
    c2py_runtime_init();

    PyMethodDef *methods = C2PY.use_fastcall ? _methods_fastcall : _methods_varargs;
    _module_def.m_methods = methods;

    if (C2PY.Module_Create2 != NULL) {
        return C2PY.Module_Create2(&_module_def, 1013);
    }
    /* Fallback for Python 2.7 where PyModuleDef is not supported */
    return C2PY.InitModule_2_7("lz4mod", methods);
}

void initlz4mod(void) {
    c2py_runtime_init();
    C2PY.InitModule_2_7("lz4mod",
        C2PY.use_fastcall ? _methods_fastcall : _methods_varargs);
}
