#!/usr/bin/env python
"""Generate a POSIX makefile snippet with rules for every .c2py test module.

Usage:
    python tools/generate_makefile_deps.py  > tests/test_makefile_deps.mk

Each module gets two rules:
    1. _wrapper.c  depends on .c2py + runtime headers (generate step)
    2. .so/.pyd    depends on _wrapper.c + user .c + runtime .c (compile step)

When YAML moves into C source files, only the dependency of rule 1 changes
(from .c2py to the .c file).  The compile rule never changes.

Emits POSIX make syntax (no GNU extensions).  The include files use
$(RUNTIME_SRC), $(RUNTIME_INC), and $(EXT) which are defined in the
including Makefile.
"""

from __future__ import print_function

import os
import sys
from c2py23.parser import load_c2py

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
TESTS = os.path.join(PROJECT, "tests", "cases")


def main():
    modules = []
    for d in sorted(os.listdir(TESTS)):
        case_dir = os.path.join(TESTS, d)
        if not os.path.isdir(case_dir):
            continue
        c2py_files = [f for f in os.listdir(case_dir) if f.endswith(".c2py") and not f.endswith(".c2py.py")]
        if not c2py_files:
            continue
        c2py_fn = c2py_files[0]
        c2py_path = os.path.join(case_dir, c2py_fn)

        try:
            m = load_c2py(c2py_path)
        except Exception:
            continue

        # Find C source files (take first .c)
        c_srcs = [s for s in m.sources if s.endswith(".c")]
        if not c_srcs:
            continue

        c_fn = c_srcs[0]
        dir_rel = os.path.relpath(case_dir, PROJECT)
        modules.append((dir_rel, m.name, c2py_fn, c_fn))

    rel_runtime_inc = os.path.relpath(os.path.join(PROJECT, "c2py23", "runtime"), PROJECT)
    rel_runtime_src = os.path.relpath(os.path.join(PROJECT, "c2py23", "runtime", "c2py_runtime.c"), PROJECT)

    print("# Generated by tools/generate_makefile_deps.py -- DO NOT EDIT")
    print("#")
    print("# To regenerate:  python tools/generate_makefile_deps.py > tests/test_makefile_deps.mk")
    print("#")
    print("# Each module has two rules:")
    print("#   1. _wrapper.c  <-  .c2py + runtime headers  (generate step)")
    print("#   2. .so/.pyd    <-  _wrapper.c + user .c + runtime.c  (compile)")
    print()

    for dir_rel, mod, c2py_fn, c_fn in modules:
        print(
            "{dir}/{mod}_wrapper.c: {dir}/{c2py} $(RUNTIME_HDRS)".format(
                dir=dir_rel,
                mod=mod,
                c2py=c2py_fn,
            )
        )
        print(
            "\tpython3 -m c2py23 {dir}/{c2py} -o $@".format(
                dir=dir_rel,
                c2py=c2py_fn,
            )
        )
        print()
        print(
            "{dir}/{mod}$(EXT): {dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC)".format(
                dir=dir_rel,
                mod=mod,
                c_fn=c_fn,
            )
        )
        print("\t$(CC) $(CFLAGS) -shared -I$(RUNTIME_INC) -I{dir} \\".format(dir=dir_rel))
        print(
            "\t\t{dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC) \\".format(
                dir=dir_rel,
                mod=mod,
                c_fn=c_fn,
            )
        )
        print("\t\t-o $@ $(LDFLAGS) $(LIBS)")
        print()


if __name__ == "__main__":
    main()
