#!/usr/bin/env python
"""Generate a POSIX makefile snippet with rules for every test module.

Usage:
    python tools/generate_makefile_deps.py  > tests/test_makefile_deps.mk

Each module gets two rules:
    1. _wrapper.c  depends on user .c (or .c2py) + runtime headers
    2. .so/.pyd    depends on _wrapper.c + user .c + runtime .c

Scans .c files for embedded C2PY_BEGIN blocks first, falls back to
.c2py files for modules that keep a separate interface definition.
"""

from __future__ import print_function

import os

from c2py23.parser import load_c2py

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
TESTS = os.path.join(PROJECT, "tests", "cases")


def _find_interface(case_dir):
    """Find the interface: .c with C2PY_BEGIN block, or .c2py file."""
    for fn in sorted(os.listdir(case_dir)):
        if not fn.endswith(".c") or fn.endswith("_wrapper.c"):
            continue
        fp = os.path.join(case_dir, fn)
        try:
            with open(fp) as f:
                if "C2PY_BEGIN" in f.read():
                    return fp
        except Exception:
            pass
    for fn in sorted(os.listdir(case_dir)):
        if fn.endswith(".c2py") and not fn.endswith(".c2py.py"):
            return os.path.join(case_dir, fn)
    return None


def main():
    modules = []
    for d in sorted(os.listdir(TESTS)):
        case_dir = os.path.join(TESTS, d)
        if not os.path.isdir(case_dir):
            continue
        interface_path = _find_interface(case_dir)
        if not interface_path:
            continue
        try:
            m = load_c2py(interface_path)
        except Exception:
            continue
        c_srcs = [s for s in m.sources if s.endswith(".c")]
        if not c_srcs:
            continue
        c_fn = c_srcs[0]
        dir_rel = os.path.relpath(case_dir, PROJECT)
        interface_fn = os.path.basename(interface_path)
        modules.append((dir_rel, m.name, interface_fn, c_fn))

    print("# Generated by tools/generate_makefile_deps.py -- DO NOT EDIT")
    print("#")
    print("# To regenerate:")
    print("#   python tools/generate_makefile_deps.py > tests/test_makefile_deps.mk")
    print()

    for dir_rel, mod, interface_fn, c_fn in modules:
        print("{dir}/{mod}_wrapper.c: {dir}/{ifn} $(RUNTIME_HDRS)".format(dir=dir_rel, mod=mod, ifn=interface_fn))
        print("\tpython3 -m c2py23 {dir}/{ifn} -o $@".format(dir=dir_rel, ifn=interface_fn))
        print()
        print("ifndef MSVC")
        print(
            "{dir}/{mod}$(EXT): {dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC)".format(
                dir=dir_rel, mod=mod, c_fn=c_fn
            )
        )
        print("\t$(CC) $(CFLAGS) -shared -I$(RUNTIME_INC) -I{dir} \\".format(dir=dir_rel))
        print("\t\t{dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC) \\".format(dir=dir_rel, mod=mod, c_fn=c_fn))
        print("\t\t-o $@ $(LDFLAGS) $(LIBS)")
        print("endif")
        print()
        print("ifdef MSVC")
        print(
            "{dir}/{mod}$(EXT): {dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC)".format(
                dir=dir_rel, mod=mod, c_fn=c_fn
            )
        )
        print("\t$(CC) $(CFLAGS) /LD /I$(RUNTIME_INC) /I{dir} \\".format(dir=dir_rel))
        print("\t\t{dir}/{mod}_wrapper.c {dir}/{c_fn} $(RUNTIME_SRC) \\".format(dir=dir_rel, mod=mod, c_fn=c_fn))
        print("\t\t/link /OUT:$@ $(LDFLAGS)")
        print("endif")
        print()


if __name__ == "__main__":
    main()
