name: Linux CI (pythonh)

on:
  push:
  workflow_dispatch:

jobs:
  test-pythonh-27:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python2 python2-dev python3-virtualenv
          virtualenv -p python2 ${HOME}/cp27
          source ${HOME}/cp27/bin/activate
          ${HOME}/cp27/bin/python -m pip install -U pip setuptools wheel
          echo "${HOME}/cp27/bin" >> $GITHUB_PATH

      - name: Install c2py23
        run: python -m pip install -e ".[yaml]" --quiet

      - name: Build (pythonh)
        run: python -m c2py23.cli build --pythonh tests/cases/fill/fill.c2py -o /tmp/fill_ph.so

      - name: Test import and fill()
        run: python tests/test_ph_ci_27.py

  test-pythonh-314t:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14t"
          allow-prereleases: true

      - name: Install c2py23
        run: pip install -e ".[yaml]" --quiet

      - name: Build (pythonh)
        run: python -m c2py23.cli build --pythonh tests/cases/fill/fill.c2py -o /tmp/fill_ph.so

      - name: Test import and fill()
        run: python tests/test_ph_ci_314t.py
